version: 0.0
os: linux
files:
  - source: /bms.war
    destination: /var/lib/tomcat8/webapps/
  - source: /restart_server.sh
    destination: /home/ubuntu/
hooks:
  ApplicationStart:
    - location: /restart_server.sh
      timeout: 3600

