version: 0.0
os: linux
files:
  - source: /ROOT.war
    destination: /home/ubuntu/tomcat/webapps
  - source: /kill_server.sh
    destination: /home/ubuntu
  - source: /replace_conf.sh
    destination: /home/ubuntu
  - source: /start_server.sh
    destination: /home/ubuntu
  - source: /change_conf.sh
    destination: /home/ubuntu

hooks:
  ApplicationStop:
    - location: /home/ubuntu/kill_server.sh
      timeout: 3600
      runas: ubuntu
  AfterInstall:
    - location: /home/ubuntu/change_conf.sh
      timeout: 3600
      runas: ubuntu
  ApplicationStart:
    - location: /home/ubuntu/start_server.sh
      timeout: 3600
      runas: ubuntu
