version: 0.0
os: linux
files:
  - source: /bms.war
    destination: /home/ubuntu/apache-tomcat-9.0.0.M21/webapps
  - source: /restart_server.sh
    destination: /home/ubuntu/
hooks:
  ApplicationStart:
    - location: /restart_server.sh
      timeout: 3600