version: 0.0
os: linux

files:
  - source: /bmsconsole.war
    destination: /var/lib/tomcat7/webapps/
  - source: /script.sh
    destination: /home/ubuntu/
hooks:
  ApplicationStart:
    - location: /script.sh
      timeout: 3600
