version: 0.0
os: linux
files:
  - source: /ROOT.war
    destination: /home/facilio/tomcat/webapps
  - source: /clean_server.sh
    destination: /home/facilio
  - source: /kill_server.sh
    destination: /home/facilio
  - source: /start_server.sh
    destination: /home/facilio
  - source: /change_conf.sh
    destination: /home/facilio
  - source: /move_logs.sh
    destination: /home/facilio
  - source: /setenv.sh
    destination: /home/facilio
  - source: /setenv-sp.sh
    destination: /home/facilio
  - source: /setenv-syd.sh
    destination: /home/facilio
  - source: /setenv-uk.sh
    destination: /home/facilio
  - source: /threaddump.sh
    destination: /home/facilio
  - source: /move_hprof.sh
    destination: /home/facilio
  - source: /oom.sh
    destination: /home/facilio
  - source: /monitor_server.sh
    destination: /home/facilio
  - source: /validate_health.sh
    destination: /home/facilio
  - source: /disk_alert.sh
    destination: /home/facilio

permissions:
  - object: /home/facilio
    pattern: "deployment-files"
    owner: facilio
    group: facilio
    mode: 755
    type:
      - directory

  - object: /home/facilio/tomcat/webapps
    pattern: "ROOT.war"
    owner: facilio
    group: facilio
    mode: 644

  - object: /home/facilio/deployment-files/
    pattern: "**"
    owner: facilio
    group: facilio
    mode: 644
    type:
      - file

  - object: /home/facilio
    pattern: "*.sh"
    owner: facilio
    group: facilio
    mode: 755

hooks:
  ApplicationStop:
    - location: /kill_server.sh
      timeout: 3600
      runas: facilio
  BeforeInstall:
    - location: /clean_server.sh
      timeout: 3600
      runas: facilio
  AfterInstall:
    - location: /change_conf.sh
      timeout: 3600
      runas: facilio
  ApplicationStart:
    - location: /start_server.sh
      timeout: 3600
      runas: facilio
  ValidateService:
    - location: /validate_health.sh
      runas: facilio
