version: 0.0
os: linux
files:
  - source: /ROOT.war
    destination: /home/facilio/tomcat/webapps
  - source: /clean_server.sh
    destination: /home/facilio
  - source: /kill_server.sh
    destination: /home/facilio
  - source: /start_server.sh
    destination: /home/facilio
  - source: /change_conf.sh
    destination: /home/facilio
  - source: /move_logs.sh
    destination: /home/facilio
  - source: /setenv.sh
    destination: /home/facilio
  - source: /setenv-sp.sh
    destination: /home/facilio
  - source: /threaddump.sh
    destination: /home/facilio
  - source: /move_hprof.sh
    destination: /home/facilio
  - source: /oom.sh
    destination: /home/facilio
  - source: /awsprops-scheduler.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-kinesis.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-stage.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-user.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-demo.properties
    destination: /home/facilio/deployment-files/
  - source: /log4j-user.properties
    destination: /home/facilio/deployment-files/
  - source: /log4j-stage.properties
    destination: /home/facilio/deployment-files/
  - source: /log4j-scheduler.properties
    destination: /home/facilio/deployment-files/
  - source: /log4j-kinesis.properties
    destination: /home/facilio/deployment-files/
  - source: /agentIntegration-production.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-sp-scheduler.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-sp-user.properties
    destination: /home/facilio/deployment-files/
  - source: /executors-org.xml
      destination: /home/facilio/deployment-files/
  - source: /executors-production.xml
      destination: /home/facilio/deployment-files/
  - source: /instantjobexecutors-org.yml
      destination: /home/facilio/deployment-files/
  - source: /instantjobexecutors-production.yml
      destination: /home/facilio/deployment-files/

permissions:
  - object: /home/facilio
    pattern: "deployment-files"
    owner: facilio
    group: facilio
    mode: 755
    type:
      - directory

  - object: /home/facilio/tomcat/webapps
    pattern: "ROOT.war"
    owner: facilio
    group: facilio
    mode: 644

  - object: /home/facilio/deployment-files/
    pattern: "**"
    owner: facilio
    group: facilio
    mode: 644
    type:
      - file

  - object: /home/facilio
    pattern: "*.sh"
    owner: facilio
    group: facilio
    mode: 755


hooks:
  ApplicationStop:
    - location: /kill_server.sh
      timeout: 3600
      runas: facilio
  BeforeInstall:
    - location: /clean_server.sh
      timeout: 3600
      runas: facilio
  AfterInstall:
    - location: /change_conf.sh
      timeout: 3600
      runas: facilio
  ApplicationStart:
    - location: /start_server.sh
      timeout: 3600
      runas: facilio
