version: 0.0
os: linux
files:
  - source: /ROOT.war
    destination: /home/facilio/tomcat/webapps
  - source: /clean_server.sh
    destination: /home/facilio
  - source: /kill_server.sh
    destination: /home/facilio
  - source: /start_server.sh
    destination: /home/facilio
  - source: /change_conf.sh
    destination: /home/facilio
  - source: /move_logs.sh
    destination: /home/facilio
  - source: /setenv.sh
    destination: /home/facilio
  - source: /setenv-sp.sh
    destination: /home/facilio
  - source: /setenv-syd.sh
    destination: /home/facilio
  - source: /setenv-uk.sh
    destination: /home/facilio
  - source: /threaddump.sh
    destination: /home/facilio
  - source: /move_hprof.sh
    destination: /home/facilio
  - source: /oom.sh
    destination: /home/facilio
  - source: /monitor_server.sh
    destination: /home/facilio
  - source: /validate_health.sh
    destination: /home/facilio
  - source: /disk_alert.sh
    destination: /home/facilio
  - source: /start_hydra.sh
    destination: /home/facilio
  - source: /stop_hydra.sh
    destination: /home/facilio
  - source: /awsprops-scheduler.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-ae-kafka.properties
    destination: /home/facilio/deployment-files/    
  - source: /awsprops-ae-scheduler.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-scheduler-app.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-kafka.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-syd-kafka.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-azure-user.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-azure-scheduler.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-azure-processor.properties
    destination: /home/facilio/deployment-files/    
  - source: /awsprops-azure-test-user.properties
    destination: /home/facilio/deployment-files/
  - source: /wmsGroupInfo-azure.yml
    destination: /home/facilio/deployment-files/    
  - source: /awsprops-azure-test-scheduler.properties
    destination: /home/facilio/deployment-files/            
  - source: /awsprops-stage.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-team.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-iot.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-stage2.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-user.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-preprod.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-ae-user.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-demo.properties
    destination: /home/facilio/deployment-files/
  - source: /log4j-user.properties
    destination: /home/facilio/deployment-files/
  - source: /log4j-preprod.properties
    destination: /home/facilio/deployment-files/
  - source: /log4j-stage.properties
    destination: /home/facilio/deployment-files/
  - source: /log4j-stage2.properties
    destination: /home/facilio/deployment-files/
  - source: /log4j-scheduler.properties
    destination: /home/facilio/deployment-files/
  - source: /log4j-kafka.properties
    destination: /home/facilio/deployment-files/
  - source: /log4j-syd-kafka.properties
    destination: /home/facilio/deployment-files/
  - source: /log4j-ae-kafka.properties
    destination: /home/facilio/deployment-files/
  - source: /log4j-scheduler-app.properties
    destination: /home/facilio/deployment-files/
  - source: /log4j-syd-user-critical.properties
    destination: /home/facilio/deployment-files/
  - source: /log4j-syd-scheduler-critical.properties
    destination: /home/facilio/deployment-files/
  - source: /log4j-syd-user.properties
    destination: /home/facilio/deployment-files/
  - source: /log4j-syd-scheduler.properties
    destination: /home/facilio/deployment-files/
  - source: /log4j-ae-user.properties
    destination: /home/facilio/deployment-files/
  - source: /log4j-ae-scheduler.properties
    destination: /home/facilio/deployment-files/
  - source: /log4j-uk-user.properties
    destination: /home/facilio/deployment-files/
  - source: /log4j-uk-scheduler.properties
    destination: /home/facilio/deployment-files/
  - source: /log4j-uk-kafka.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-uk-kafka.properties
    destination: /home/facilio/deployment-files/
  - source: /log4j-sp-user.properties
    destination: /home/facilio/deployment-files/
  - source: /log4j-sp-scheduler.properties
    destination: /home/facilio/deployment-files/
  - source: /log4j-sp-kafka.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-sp-kafka.properties
    destination: /home/facilio/deployment-files/    
  - source: /awsprops-sp-scheduler.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-sp-user.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-uk-scheduler.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-uk-user.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-syd-scheduler-critical.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-syd-user-critical.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-syd-scheduler.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-syd-user.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-syd-user-int.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-oci-user.properties
    destination: /home/facilio/deployment-files/
  - source: /awsprops-oci-scheduler.properties
    destination: /home/facilio/deployment-files/    
  - source: /executors-org.xml
    destination: /home/facilio/deployment-files/
  - source: /executors-org-au.xml
    destination: /home/facilio/deployment-files/
  - source: /executors-production.xml
    destination: /home/facilio/deployment-files/
  - source: /executors-production-au.xml
    destination: /home/facilio/deployment-files/
  - source: /instantjobexecutors-org.yml
    destination: /home/facilio/deployment-files/
  - source: /instantjobexecutors-org-au.yml
    destination: /home/facilio/deployment-files/
  - source: /instantjobexecutors-production.yml
    destination: /home/facilio/deployment-files/
  - source: /instantjobexecutors-production-au.yml
    destination: /home/facilio/deployment-files/
  - source: /service-stage.yml
    destination: /home/facilio/deployment-files/
  - source: /service-production.yml
    destination: /home/facilio/deployment-files/
  - source: /service-sp.yml
    destination: /home/facilio/deployment-files/
  - source: /service-syd.yml
    destination: /home/facilio/deployment-files/
  - source: /service-syd-critical.yml
    destination: /home/facilio/deployment-files/
  - source: /service-uk.yml
    destination: /home/facilio/deployment-files/
  - source: /clientAppConfig-stage.yml
    destination: /home/facilio/deployment-files/
  - source: /log4j-azure-test-user.properties
    destination: /home/facilio/deployment-files/
  - source: /log4j-azure-test-scheduler.properties
    destination: /home/facilio/deployment-files/
  - source: /log4j-azure-test-processor.properties
    destination: /home/facilio/deployment-files/
  - source: /log4j-azure-user.properties
    destination: /home/facilio/deployment-files/
  - source: /log4j-azure-scheduler.properties
    destination: /home/facilio/deployment-files/
  - source: /log4j-azure-processor.properties
    destination: /home/facilio/deployment-files/
    

permissions:
  - object: /home/facilio
    pattern: "deployment-files"
    owner: facilio
    group: facilio
    mode: 755
    type:
      - directory

  - object: /home/facilio/tomcat/webapps
    pattern: "ROOT.war"
    owner: facilio
    group: facilio
    mode: 644

  - object: /home/facilio/deployment-files/
    pattern: "**"
    owner: facilio
    group: facilio
    mode: 644
    type:
      - file

  - object: /home/facilio
    pattern: "*.sh"
    owner: facilio
    group: facilio
    mode: 755

hooks:
  ApplicationStop:
    - location: /kill_server.sh
      timeout: 3600
      runas: facilio
  BeforeInstall:
    - location: /clean_server.sh
      timeout: 3600
      runas: facilio
  AfterInstall:
    - location: /change_conf.sh
      timeout: 3600
      runas: facilio
  ApplicationStart:
    - location: /start_server.sh
      timeout: 3600
      runas: facilio
  ValidateService:
    - location: /validate_health.sh
      runas: facilio
