version: 0.0
os: linux
files:
  - source: /bms.war
    destination: /home/ubuntu/apache-tomcat-9.0.0.M21/webapps
  - source: /kill_server.sh
    destination: /home/ubuntu/
  - source: /repalce_conf.sh
    destination: /home/ubuntu/
  - source: /start_server.sh
    destination: /home/ubuntu/
hooks:
  BeforeInstall:
    - location: /kill_server.sh
      timeout: 3600
  ApplicationStart:
    - location: /start_server.sh
      timeout: 3600
