version: 0.0
os: linux
files:
  - source: /ROOT.war
    destination: /home/ubuntu/apache-tomcat-9.0.0.M21/webapps
  - source: /kill_server.sh
    destination: /home/ubuntu/
  - source: /replace_conf.sh
    destination: /home/ubuntu/
  - source: /start_server.sh
    destination: /home/ubuntu/
  - source: /change_conf.sh
    destination: /home/ubuntu/
hooks:
  ApplicationStop:
    - location: /kill_server.sh
      timeout: 3600
  AfterInstall:
    - location: /change_conf.sh
      timeout: 3600
      runas: root
  ApplicationStart:
    - location: /start_server.sh
      timeout: 3600
