version: 0.0
os: linux
files:
  - source: /ROOT.war
    destination: /home/ubuntu/tomcat/webapps
  - source: /kill_server.sh
    destination: /home/ubuntu
  - source: /start_server.sh
    destination: /home/ubuntu
  - source: /change_conf.sh
    destination: /home/ubuntu
  - source: /move_logs.sh
    destination: /home/ubuntu
  - source: /start_xvfb.sh
    destination: /home/ubuntu
  - source: /setenv.sh
    destination: /home/ubuntu
  - source: /awsprops-scheduler.properties
    destination: /home/ubuntu/deployment-files/
  - source: /awsprops-stage.properties
    destination: /home/ubuntu/deployment-files/
  - source: /awsprops-user.properties
    destination: /home/ubuntu/deployment-files/
  - source: /log4j-user.properties
    destination: /home/ubuntu/deployment-files/
  - source: /log4j-stage.properties
    destination: /home/ubuntu/deployment-files/
  - source: /log4j-scheduler.properties
    destination: /home/ubuntu/deployment-files/
  - source: /context-production.xml
    destination: /home/ubuntu/deployment-files/
  - source: /context-stage.xml
    destination: /home/ubuntu/deployment-files/

permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    mode: 644
    type:
      - directory

  - object: /home/ubuntu/tomcat/webapps
    pattern: "ROOT.war"
    owner: ubuntu
    group: ubuntu
    mode: 644

  - object: /home/ubuntu/deployment-files
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 644

  - object: /home/ubuntu
    pattern: "*.sh"
    owner: ubuntu
    group: ubuntu
    mode: 755


hooks:
  ApplicationStop:
    - location: /kill_server.sh
      timeout: 3600
      runas: ubuntu
  AfterInstall:
    - location: /change_conf.sh
      timeout: 3600
      runas: ubuntu
  ApplicationStart:
    - location: /start_server.sh
      timeout: 3600
      runas: ubuntu
