pipelines:
  custom:
    production:
      - step:
          script:
            - echo "started"
            - git checkout production
            - echo $commitid
            - git reset --hard $commitid
            - git remote set-url origin ${BITBUCKET_GIT_SSH_ORIGIN}
            - git push --force
            - echo "Finished"