version: 0.1

phases:
  build:
    commands:
      - aws s3 cp s3://repo.facilstack.com/maven_settings.xml ~/.m2/maven_settings.xml
      - mvn -s ~/.m2/maven_settings.xml package
artifacts:
  files:
    - target/ROOT.war
    - appspec.yml
    - scripts/kill_server.sh
    - scripts/start_server.sh
    - scripts/replace_conf.sh
    - scripts/change_conf.sh
    - scripts/move_logs.sh
  discard-paths: yes

