version: 0.1

phases:
  build:
    commands:
      - mvn package
artifacts:
  files:
    - target/ROOT.war
    - appspec.yml
    - scripts/kill_server.sh
    - scripts/start_server.sh
    - scripts/replace_conf.sh
    - scripts/change_conf.sh
    - scripts/move_logs.sh
    - scripts/start_xvfb.sh
  discard-paths: yes

