version: 0.1

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - gulp
      - mvn package
artifacts:
  files:
    - target/bms.war
    - appspec.yml
    - scripts/restart_server.sh
  discard-paths: yes

