version: 0.1

env:
  exported-variables:
    - CODEBUILD_BUILD_NUMBER
    - CODEBUILD_BUILD_ID

phases:
  build:
    commands:
      - export BUILD_BRANCH=$(echo $BRANCH_NAME | sed -e 's/\//_/g')
      - mvn package -Dbuild.number=$CODEBUILD_BUILD_NUMBER -Dbuild.branch=$BUILD_BRANCH -Dbuild.commitid=$COMMIT_ID
      - mvn deploy -Dbuild.type=jar -Dbuild.number=$CODEBUILD_BUILD_NUMBER -Dbuild.branch=$BUILD_BRANCH -DskipTests
artifacts:
  files:
    - target/ROOT.war
    - appspec.yml
    - scripts/kill_server.sh
    - scripts/clean_server.sh
    - scripts/disk_alert.sh
    - scripts/start_server.sh
    - scripts/change_conf.sh
    - scripts/move_logs.sh
    - scripts/setenv.sh
    - scripts/setenv-sp.sh
    - scripts/setenv-uk.sh
    - scripts/setenv-syd.sh
    - scripts/setenv-oci.sh
    - scripts/setenv-azure.sh
    - scripts/move_hprof.sh
    - scripts/oom.sh
    - scripts/threaddump.sh
    - scripts/start_hydra.sh
    - scripts/stop_hydra.sh
    - scripts/monitor_server.sh
    - scripts/validate_health.sh
    - deployment-files/*
  discard-paths: yes