version: "3.8"

networks:
  bms:
    name: bms
    driver: bridge

services:
  zookeeper:
    image: bitnami/zookeeper:3.6.2
    container_name: zookeeper
    ports:
      - '2181:2181'
    volumes:
      - ~/data/zookeeper:/bitnami/zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - bms

  kafka1:
    image: bitnami/kafka:2.7.0
    container_name: kafka1
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka1:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - ~/data/kafka:/bitnami/kafka
    ports:
      - '9092'
      - '9093'
    depends_on:
      - zookeeper
    networks:
      - bms
  bms-db:
    platform: "${PLATFORM}"
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=bmslocal
    volumes:
      - ~/data/mysql:/var/lib/mysql
    networks:
      - bms

  akhq:
    image: tchiotludo/akhq:latest
    container_name: akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka1:9092"
    ports:
      - "8000:8080"
    depends_on:
      - kafka1
    networks:
      - bms

  bms-app-1:
    environment:
      - CATALINA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    build: .
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - kafka1
      - bms-db
    networks:
      - bms

  bms-app-2:
    environment:
      - CATALINA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    build: .
    ports:
      - "8081:8080"
      - "5006:5005"
    depends_on:
      - kafka1
      - bms-db
    networks:
      - bms

