version: 1.0

widgets:
#  SUMMARY_FIELDS_WIDGET :
#    WEB:
#      - name: flexiblewebsummaryfieldswidget_2
#        displayName: Summary Fields Widget - 2
#        configType: FLEXIBLE
#        minHeight: SMALL
#        minWidth: ONE_FOURTH
#    MOBILE:
#      - name: flexiblemobilesummaryfieldswidget_2
#        displayName: Summary Fields Widget - 2
#        configType: FLEXIBLE
#        minHeight: SMALL
#        minWidth: HALF
#
#  COMMENT:
#    WEB:
#    - name: flexiblewebcomment_2
#      displayName: Comment - 2
#      configType: FLEXIBLE
#      minHeight: SMALL
#    MOBILE:
#      - name: flexiblemobilecomment_2
#        displayName: Comment - 2
#        configType: FLEXIBLE
#        minHeight: LARGE
  CONNNECTED_APP:
      WEB:
      - name: flexibleWebConnectedApp_6
        displayName: Connected App - 6
        configType: SINGLE_PAGE_WIDGET
        minHeight: LARGE



