import $helpers from 'src/util/helpers.js'

let columnConfig = {
  agentAlarm: {
    fixedColumns: [
      'subject',
      'lastOccurredTime',
      'lastCreatedTime',
      'acknowledged',
      'readingalarmcategory',
      'acknowledgedBy',
      'acknowledgedTime',
      'severity',
    ],
    fixedSelectableColumns: ['severity', 'noOfOccurrences', 'acknowledgedBy'],
    availableColumns: ['resource'],
    showLookupColumns: false,
    lookupToShow: ['asset', 'space'],
  },
  accounttype: {
    fixedColumns: ['name'],
    availableColumns: [],
  },
  site: {
    fixedColumns: ['name', 'id'],
    availableColumns: [],
    showLookupColumns: false,
    nonSelectableColumns: [
      'space1',
      'space2',
      'space3',
      'space4',
      'building',
      'floor',
      'controllerId',
      'sourceType',
      'sourceId',
      'operatingHour',
    ],
  },
  building: {
    fixedColumns: ['name', 'id'],
    availableColumns: [],
    showLookupColumns: false,
    nonSelectableColumns: [
      'space1',
      'space2',
      'space3',
      'space4',
      'building',
      'floor',
      'controllerId',
      'sourceType',
      'sourceId',
      'operatingHour',
    ],
  },
  asset: {
    fixedColumns: ['name'],
    availableColumns: [],
    nonSelectableColumns: ['hideToCustomer', 'parentAssetId', 'stateFlowId'],
    showLookupColumns: false,
  },
  failureclass: {
    fixedColumns: ['name'],
  },
  item: {
    fixedColumns: ['itemType'],
  },
  tool: {
    fixedColumns: ['toolType'],
    showLookupColumns: true,
    lookupToShow: ['toolType', 'storeRoom'],
  },
  service: {
    fixedColumns: ['name'],
    availableColumns: [
      'status',
      'description',
      'duration',
      'sellingPrice',
      'buyingPrice',
      'paymentType',
    ],
    showLookupColumns: false,
  },
  transferrequestshipment: { fixedColumns: ['transferRequest'] },
  transferrequest: {
    fixedColumns: ['requestSubject', 'id'],
  },
  workorder: {
    fixedColumns: ['subject', 'localId'],
    availableColumns: [
      'category',
      'description',
      'dueDate',
      'responseDueDate',
      'moduleState',
      'sourceType',
      'assignedTo',
      'createdTime',
      'createdBy',
      'priority',
      'resource',
      'type',
      'modifiedTime',
      'actualWorkStart',
      'actualWorkEnd',
      'totalCost',
      'siteId',
      'vendor',
      'requester',
      $helpers.isLicenseEnabled('TENANTS') ? 'tenant' : '',
      $helpers.isLicenseEnabled('CLIENT') ? 'client' : '',
      'noOfNotes',
      'noOfTasks',
      'noOfAttachments',
      'attachmentPreview',
      'jobPlan',
    ],
  },
  workpermit: {
    fixedColumns: ['name'],
    availableColumns: [],
    nonSelectableColumns: [
      'ticket',
      'approvalFlowId',
      'stateFlowId',
      'isRecurring',
      'recurringInfoId',
      'permitType',
    ],
  },
  jobplan: {
    fixedColumns: ['name'],
    availableColumns: [],
    showLookupColumns: true,
    lookupToShow: [],
  },
  inspectionTemplate: {
    fixedColumns: ['name'],
    availableColumns: [],
  },
  inspectionResponse: {
    fixedColumns: ['name'],
    availableColumns: [],
  },
  newreadingalarm: {
    fixedColumns: ['subject'],
    fixedSelectableColumns: ['severity'],
  },
  sensorrollupalarm: {
    fixedColumns: ['readingFieldId','subject'],
  
  },
  bmsalarm: { fixedColumns: ['subject'], fixedSelectableColumns: ['severity'] },
  quote: {
    fixedColumns: ['subject'],
    availableColumns: [],
    nonSelectableColumns: [
      'workorder',
      'approvalFlowId',
      'stateFlowId',
      'parentId',
    ],
  },
  requestForQuotation: {
    fixedColumns: ['name'],
  },
  purchaserequest: {
    fixedColumns: ['name', 'localId'],
    availableColumns: [],
    showLookupColumns: true,
    lookupToShow: ['vendor', 'storeRoom'],
  },
  vendorQuotes: {
    fixedColumns: ['requestForQuotation', 'id', 'vendor'],
  },
  purchaseorder: {
    fixedColumns: ['name', 'localId'],
    availableColumns: [],
    showLookupColumns: true,
    lookupToShow: ['vendor', 'storeRoom'],
  },
  receivable: {
    fixedColumns: ['poId'],
    availableColumns: [],
    showLookupColumns: true,
  },
  termsandconditions: {
    fixedColumns: ['name'],
    availableColumns: [],
    showLookupColumns: true,
    lookupToShow: [],
  },
  newreadingrules: { fixedColumns: ['id', 'name'] },
  purchasecontracts: {
    fixedColumns: ['name', 'localId'],
    availableColumns: [],
    showLookupColumns: true,
    lookupToShow: ['space', 'type'],
  },
  budget: { fixedColumns: ['name', 'localId'], availableColumns: [] },
  chartofaccount: {
    fixedColumns: ['name'],
    availableColumns: [],
    nonSelectableColumns: ['localId'],
  },
  insurance: {
    fixedColumns: ['companyName'],
    fixedSelectableColumns: ['photo'],
  },
  visitorlog: {
    fixedColumns: ['visitor', 'localId', 'visitorName'],
    availableColumns: [],
    showLookupColumns: true,
    lookupToShow: ['visitor'],
    nonSelectableColumns: ['passCode'],
  },
  invitevisitor: {
    fixedColumns: ['visitor', 'localId', 'visitorName'],
    availableColumns: [],
    showLookupColumns: false,
  },
  visitor: { fixedColumns: ['name'], availableColumns: [] },
  watchlist: { fixedColumns: ['name', 'localId'], availableColumns: [] },
  controlGroupv2: {
    fixedColumns: ['id', 'name'],
    availableColumns: [],
    showLookupColumns: false,
  },
  controlSchedule: {
    fixedColumns: ['id', 'name', 'sysCreatedTime', 'sysCreatedBy'],
    availableColumns: [],
    showLookupColumns: false,
  },
  facility: { fixedColumns: ['name'], availableColumns: [] },
  amenity: { fixedColumns: ['name'], availableColumns: [] },
  facilitybooking: { fixedColumns: ['facility'], availableColumns: [] },
  serviceRequest: { fixedColumns: ['subject'], availableColumns: [] },
  contactdirectory: {
    fixedColumns: [],
    availableColumns: [],
    nonSelectableColumns: ['approvalFlowId', 'stateFlowId'],
  },
  admindocuments: {
    fixedColumns: [],
    availableColumns: [],
    nonSelectableColumns: ['approvalFlowId', 'stateFlowId'],
  },
  announcement: { fixedColumns: ['title'], availableColumns: [] },
  neighbourhood: {
    fixedColumns: ['title'],
    availableColumns: [],
    nonSelectableColumns: ['approvalFlowId', 'stateFlowId'],
  },
  dealsandoffers: {
    fixedColumns: ['title'],
    availableColumns: [],
    nonSelectableColumns: ['approvalFlowId', 'stateFlowId'],
  },
  newsandinformation: {
    fixedColumns: ['title'],
    availableColumns: [],
    nonSelectableColumns: ['approvalFlowId', 'stateFlowId'],
  },
  audience: { fixedColumns: ['name'], availableColumns: [] },
  deliveries: { fixedColumns: ['name'], availableColumns: [] },
  deliveryArea: { fixedColumns: ['name'], availableColumns: [] },
  department: { fixedColumns: ['name'], availableColumns: [] },
  desks: { fixedColumns: ['name'], availableColumns: [] },
  gatePass: {
    fixedColumns: ['localId'],
    availableColumns: [
      'fromStoreRoom',
      'toStoreRoom',
      'parentWorkOrderId',
      'parentPoId',
      'status',
      'issuedToPhoneNumber',
      'vehicleNo',
      'isReturnable',
      'gatePassType',
      'issuedBy',
      'issuedTo',
      'returnTime',
      'issuedTime',
    ],
  },
  lockers: { fixedColumns: ['name'], availableColumns: [] },
  moves: { fixedColumns: ['employee'], availableColumns: [] },
  operationalarm: {
    fixedColumns: ['subject'],
    fixedSelectableColumns: ['severity', 'noOfOccurrences', 'acknowledgedBy'],
    availableColumns: [
      'resource',
      'lastOccurredTime',
      'lastCreatedTime',
      'acknowledgedBy',
      'acknowledged',
      'readingalarmcategory',
      'acknowledgedTime',
      'severity',
    ],
    showLookupColumns: false,
    lookupToShow: ['asset', 'space'],
  },
  parkingstall: { fixedColumns: ['name'], availableColumns: [] },
  reservation: {
    fixedColumns: ['name'],
    availableColumns: ['startTime', 'endTime'],
    showLookupColumns: false,
  },
  rooms: { fixedColumns: ['name'], availableColumns: [] },
  shift: {
    fixedColumns: ['name'],
    availableColumns: ['startTime', 'endTime', 'defaultShift'],
    showLookupColumns: false,
  },
  shiftRotation: {
    fixedColumns: ['name'],
    availableColumns: ['startTime', 'endTime', 'defaultShiftRotation'],
    showLookupColumns: false,
  },
  shipment: {
    fixedColumns: ['localId'],
    availableColumns: [
      'transferredBy',
      'receivedBy',
      'fromStore',
      'toStore',
      'status',
      'localId',
    ],
    showLookupColumns: false,
  },
  space: { fixedColumns: ['name'], fixedSelectableColumns: ['photo'] },
  alarm: {
    fixedColumns: ['subject'],
    fixedSelectableColumns: ['severity', 'acknowledgedBy', 'noOfEvents'],
    availableColumns: [
      'alarmClass',
      'alarmType',
      'previousSeverity',
      'condition',
      'modifiedTime',
      'createdTime',
      'clearedTime',
      'source',
      'resource',
    ],
    showLookupColumns: false,
    lookupToShow: ['asset', 'space'],
  },
  attendance: {
    fixedColumns: ['day'],
    availableColumns: [
      'user',
      'checkInTime',
      'checkOutTime',
      'workingHours',
      'status',
      'lastCheckInTime',
      'totalPaidBreakHrs',
      'lastBreakStartTime',
    ],
    showLookupColumns: true,
    lookupToShow: ['user'],
  },
  break: {
    fixedColumns: ['name'],
    availableColumns: ['breakTime', 'breakType'],
    showLookupColumns: false,
  },
  labourcontracts: {
    fixedColumns: ['name', 'localId'],
    availableColumns: [],
    showLookupColumns: true,
    lookupToShow: ['space', 'type'],
  },
  rentalleasecontracts: {
    fixedColumns: ['name', 'localId'],
    availableColumns: [],
    showLookupColumns: true,
    lookupToShow: ['space', 'type'],
  },
  warrantycontracts: {
    fixedColumns: ['name', 'localId'],
    availableColumns: [],
    showLookupColumns: true,
    lookupToShow: ['space', 'type'],
  },
  hazardPrecaution: {
    fixedColumns: ['precaution'],
  },
  safetyPlanHazard: {
    fixedColumns: ['hazard'],
  },
  vendorDocuments: {
    fixedColumns: ['documentName'],
  },
  contact: {
    fixedColumns: ['name', 'localId'],
    availableColumns: [],
    showLookupColumns: false,
  },
  mlAnomalyAlarm: {
    fixedColumns: ['subject'],
    fixedSelectableColumns: ['severity', 'noOfOccurrences', 'acknowledgedBy'],
    availableColumns: [
      'resource',
      'lastOccurredTime',
      'lastCreatedTime',
      'acknowledgedBy',
      'acknowledged',
      'readingalarmcategory',
      'acknowledgedTime',
      'severity',
    ],
    showLookupColumns: false,
    lookupToShow: ['asset', 'space'],
  },
  tenantunit: { fixedColumns: ['name'], fixedSelectableColumns: ['photo'] },
  DEFAULT: { fixedColumns: ['name'], fixedSelectableColumns: ['photo'] },
}

export const getColumnConfig = moduleName => {
  return columnConfig[moduleName] || columnConfig.DEFAULT
}

export const setColumnConfig = ({ moduleName, config }) => {
  columnConfig[moduleName] = config
}
