package com.facilio.bmsconsole.commands;

import org.apache.commons.chain.Command;
import org.apache.commons.chain.Context;

import com.facilio.constants.FacilioConstants;

public class ParseQRValueCommand implements Command {

	@Override
	public boolean execute(Context context) throws Exception {
		// TODO Auto-generated method stub
		String qrValue = (String) context.get(FacilioConstants.ContextNames.QR_VALUE);
		if (qrValue != null && !qrValue.isEmpty()) {
			if (qrValue.startsWith("facilio")) {
				String[] params = qrValue.split("_");
				if (params != null && params.length >= 3) {
					context.put(FacilioConstants.ContextNames.ID, params[2]);
				}
				else {
					throw new IllegalArgumentException("Malformed QR String generated by Facilio");
				}
			}
		}
		return false;
	}

}
