import * as d3 from 'd3'

export default {
  defaultMargin: {
    top: 20,
    right: 40,
    bottom: 100,
    left: 60,
  },
  colorServity: {
    high: '#ea5e5e',
    critical: '#ea5e5e',
    medium: '#f9bc3c',
    major: '#f9bc3c',
    low: '#f9ef72',
    minor: '#f9ef72',
    clear: '#b1cc5d',
    warning: '#7daeec',
  },

  defaultOptions: {
    common: {
      isWidget: true,
      isAnimated: true,
      isLableRotating: false,
      yAxisPaddingBetweenChart: 10,
    },
    pie: {
      axis: false,
      type: 'pie',
      diff: 5,
      legends: true,
      innerText: false,
      margin: {
        top: 20,
        right: 20,
        bottom: 40,
        left: 40,
      },
    },
    progress: {
      axis: false,
      type: 'progress',
      sort: 'desc',
      gColors: ['#f7768c', '#b16bbc'],
      innerText: false,
      legends: false,
      isWidget: false,
      margin: {
        top: 40,
        right: 100,
        bottom: 40,
        left: 100,
      },
    },
    funnel: {
      axis: false,
    },
    doughnut: {
      axis: false,
      type: 'doughnut',
      legends: true,
      diff: 5,
      isWidget: false,
      innerText: false,
      margin: {
        top: 20,
        right: 20,
        bottom: 40,
        left: 40,
      },
      withPoints: false,
    },
    bar: {
      isHorizontal: false,
      yAxisPaddingBetweenChart: 10,
      ease: d3.easeQuadInOut,
      animationDuration: 800,
      animationStepRatio: 70,
      interBarDelay: (d, i) => 20 * i,
      withPoints: false,
      legends: false,
    },
    line: {
      withPoints: false,
    },
    area: {
      withPoints: false,
      legends: true,
    },
    cubsim: {
      legends: false,
      yAxis: false,
    },
    stackedbar: {
      isHorizontal: false,
      yAxisPaddingBetweenChart: 10,
      ease: d3.easeQuadInOut,
      animationDuration: 800,
      animationStepRatio: 70,
      interBarDelay: (d, i) => 70 * i,
    },
    groupedbar: {
      isHorizontal: false,
      yAxisPaddingBetweenChart: 10,
      ease: d3.easeQuadInOut,
      animationDuration: 800,
      animationStepRatio: 70,
      interBarDelay: (d, i) => 70 * i,
    },
    heatMap: {
      axis: false,
      axisTop: false,
      type: 'heatmap',
      diff: 5,
      innerText: false,
      margin: {
        top: 40,
        right: 10,
        bottom: 40,
        left: 60,
      },
    },
    boolean: {
      type: 'boolean',
      axis: false,
      axisTop: false,
      diff: 5,
      innerText: false,
      margin: {
        top: 40,
        right: 10,
        bottom: 40,
        left: 60,
      },
    },
  },
  curveMap: {
    linear: d3.curveLinear,
    basis: d3.curveBasis,
    cardinal: d3.curveCardinal,
    catmullRom: d3.curveCatmullRom,
    monotoneX: d3.curveMonotoneX,
    monotoneY: d3.curveMonotoneY,
    natural: d3.curveNatural,
    step: d3.curveStep,
    stepAfter: d3.curveStepAfter,
    stepBefore: d3.curveStepBefore,
  },
  defaultCurve: 'linear',
}
