export default {
  data() {
    let tools = {
      name: {
        value: null,
        readingType: -1,
        displayName: 'Name',
        Rkey: 'dataTypeEnum',
        Rvalue: 'BOOLEAN',
        readings: null,
        inputType: 'TEXT',
        icon: {
          property: 'TEXT',
          path: 'NAME',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 4,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      runStatus: {
        value: null,
        readingType: -1,
        displayName: 'Run status',
        Rkey: 'dataTypeEnum',
        Rvalue: 'BOOLEAN',
        inputType: 'SELECT',
        readings: null,
        icon: {
          property: 'URL',
          path: 'off-on-icon.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      supplyFanVFDrunStatus: {
        value: null,
        readingType: -1,
        displayName: 'Supply FAN VFD Run status',
        Rkey: 'dataTypeEnum',
        Rvalue: 'BOOLEAN',
        inputType: 'SELECT',
        readings: null,
        icon: {
          property: 'URL',
          path: 'off-on-icon.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      exhaustFanVFDrunStatus: {
        value: null,
        readingType: -1,
        displayName: 'Exhaust FAN VFD Run status',
        Rkey: 'dataTypeEnum',
        Rvalue: 'BOOLEAN',
        inputType: 'SELECT',
        readings: null,
        icon: {
          property: 'URL',
          path: 'off-on-icon.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      runStatusValue: {
        value: null,
        readingType: -1,
        displayName: 'Supply Fan',
        Rkey: 'dataTypeEnum',
        Rvalue: 'BOOLEAN',
        inputType: 'SELECT',
        readings: null,
        icon: {
          property: 'URL',
          path: 'off-on-icon.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      percentage: {
        value: null,
        readingType: -1,
        displayName: 'Run status',
        Rkey: 'all',
        Rvalue: 'ALL',
        inputType: 'SELECT',
        readings: null,
        icon: {
          property: 'TEXT',
          path: '%',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      runStatusPercent: {
        value: null,
        readingType: -1,
        displayName: 'Run status',
        Rkey: 'all',
        Rvalue: 'ALL',
        inputType: 'SELECT',
        readings: null,
        icon: {
          property: 'URL',
          path: 'off-on-icon.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      levelPercent: {
        value: null,
        readingType: -1,
        displayName: 'Level status',
        Rkey: 'all',
        Rvalue: 'ALL',
        inputType: 'SELECT',
        readings: null,
        icon: {
          property: 'TEXT',
          path: '%',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      autoStatus: {
        value: null,
        readingType: -1,
        displayName: 'Auto/Manual',
        Rkey: 'dataTypeEnum',
        Rvalue: 'BOOLEAN',
        inputType: 'SELECT',
        enamValue: {
          true: 'Auto',
          false: 'Manual',
        },
        readings: null,
        icon: {
          property: 'TEXT',
          path: 'MANUAL',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      temperature: {
        value: null,
        readingType: -1,
        displayName: 'Temperature',
        Rkey: 'metricEnum',
        Rvalue: 'TEMPERATURE',
        inputType: 'SELECT',
        icon: {
          property: 'URL',
          path: 'thermometer.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      tripStatus: {
        value: null,
        readingType: -1,
        displayName: 'Trip Status',
        Rkey: 'dataTypeEnum',
        Rvalue: 'BOOLEAN',
        readings: null,
        inputType: 'SELECT',
        icon: {
          property: 'URL',
          path: 'bell-dot-icon.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      exhasutFantripStatus: {
        value: null,
        readingType: -1,
        displayName: 'Exhasut Fan Trip Status',
        Rkey: 'dataTypeEnum',
        Rvalue: 'BOOLEAN',
        readings: null,
        inputType: 'SELECT',
        icon: {
          property: 'URL',
          path: 'bell-dot-icon.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      supplyFantripStatus: {
        value: null,
        readingType: -1,
        displayName: 'Supply Fan Trip Status',
        Rkey: 'dataTypeEnum',
        Rvalue: 'BOOLEAN',
        readings: null,
        inputType: 'SELECT',
        icon: {
          property: 'URL',
          path: 'bell-dot-icon.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      exhasutFanvfdtripStatus: {
        value: null,
        readingType: -1,
        displayName: 'Exhasut Fan VFD Trip Status',
        Rkey: 'dataTypeEnum',
        Rvalue: 'BOOLEAN',
        readings: null,
        inputType: 'SELECT',
        icon: {
          property: 'URL',
          path: 'bell-dot-icon.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      supplyFanvfdtripStatus: {
        value: null,
        readingType: -1,
        displayName: 'Supply Fan VFD Trip Status',
        Rkey: 'dataTypeEnum',
        Rvalue: 'BOOLEAN',
        readings: null,
        inputType: 'SELECT',
        icon: {
          property: 'URL',
          path: 'bell-dot-icon.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      valveFeedback: {
        value: null,
        readingType: -1,
        displayName: 'Valve feedback',
        Rkey: 'all',
        Rvalue: 'ALL',
        readings: null,
        inputType: 'SELECT',
        icon: {
          property: 'URL',
          path: 'volve-icon.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      lightStatus: {
        value: null,
        readingType: -1,
        displayName: 'Light status',
        Rkey: 'dataTypeEnum',
        Rvalue: 'BOOLEAN',
        readings: null,
        inputType: 'SELECT',
        icon: {
          property: 'URL',
          path: 'light-bulb-on.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      levelButton: {
        value: null,
        readingType: -1,
        displayName: 'level button',
        Rkey: 'dataTypeEnum',
        Rvalue: 'ENUM',
        readings: null,
        inputType: 'SELECT',
        icon: {
          property: 'BUTTON',
          path: 'L',
          size: 'big',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      scheduledControl: {
        value: null,
        readingType: 2,
        displayName: 'Scheduled control',
        Rkey: 'dataTypeEnum',
        Rvalue: 'BOOLEAN',
        readings: null,
        inputType: 'SELECT',
        icon: {
          property: 'URL',
          path: 'clock.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      staticControl: {
        value: null,
        readingType: 2,
        displayName: 'Static control',
        Rkey: 'dataTypeEnum',
        Rvalue: 'BOOLEAN',
        readings: null,
        inputType: 'SELECT',
        icon: {
          property: 'TEXT',
          path: 'ON/OFF',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      supplyFanStatus: {
        value: null,
        readingType: -1,
        displayName: 'Supply Fan',
        Rkey: 'dataTypeEnum',
        Rvalue: 'BOOLEAN',
        inputType: 'SELECT',
        readings: null,
        icon: {
          property: 'URL',
          path: 'SupplyFanicon_on.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      exhaustFanStatus: {
        value: null,
        readingType: -1,
        displayName: 'Exhaust Fan',
        Rkey: 'dataTypeEnum',
        Rvalue: 'BOOLEAN',
        inputType: 'SELECT',
        readings: null,
        icon: {
          property: 'URL',
          path: 'ExhanustFanicon_on.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      heatWheelStatus: {
        value: null,
        readingType: -1,
        displayName: 'Heat Wheel',
        Rkey: 'dataTypeEnum',
        Rvalue: 'BOOLEAN',
        inputType: 'SELECT',
        readings: null,
        icon: {
          property: 'URL',
          path: 'HeatWheelicon_on.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      EnthalpyheatWheelStatus: {
        value: null,
        readingType: -1,
        displayName: 'Enthalpy Heat Wheel',
        Rkey: 'dataTypeEnum',
        Rvalue: 'BOOLEAN',
        inputType: 'SELECT',
        readings: null,
        icon: {
          property: 'URL',
          path: 'HeatWheelicon_on.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      SensibleheatWheelStatus: {
        value: null,
        readingType: -1,
        displayName: 'Sensible Heat Wheel',
        Rkey: 'dataTypeEnum',
        Rvalue: 'BOOLEAN',
        inputType: 'SELECT',
        readings: null,
        icon: {
          property: 'URL',
          path: 'HeatWheelicon_on.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      chilledWaterSupply: {
        value: null,
        readingType: -1,
        displayName: 'Chilled Water Supply',
        Rkey: 'metricEnum',
        Rvalue: 'TEMPERATURE',
        inputType: 'SELECT',
        icon: {
          property: 'URL',
          path: 'thermometer.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      chilledWaterReturn: {
        value: null,
        readingType: -1,
        displayName: 'Chilled Water Return',
        Rkey: 'metricEnum',
        Rvalue: 'TEMPERATURE',
        inputType: 'SELECT',
        icon: {
          property: 'URL',
          path: 'thermometer.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      coolingCoilValveFeedback: {
        value: null,
        readingType: -1,
        displayName: 'Cooling Coil Valve Feedback',
        Rkey: 'all',
        Rvalue: 'ALL',
        readings: null,
        inputType: 'SELECT',
        icon: {
          property: 'URL',
          path: 'volve-icon.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      outsideAirDamperStatus: {
        value: null,
        readingType: -1,
        displayName: 'Outside Air Damper',
        Rkey: 'dataTypeEnum',
        Rvalue: 'BOOLEAN',
        inputType: 'SELECT',
        enamValue: {
          true: 'Auto',
          false: 'Manual',
        },
        readings: null,
        icon: {
          property: 'URL',
          path: 'box_icon_on.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      supplyFanAirflow: {
        value: null,
        readingType: -1,
        displayName: 'Supply Fan Airflow',
        Rkey: 'dataTypeEnum',
        Rvalue: 'BOOLEAN',
        inputType: 'SELECT',
        readings: null,
        icon: {
          property: 'URL',
          path: 'Drop_icon_on.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      exhaustFanAirflow: {
        value: null,
        readingType: -1,
        displayName: 'Exhaust Fan Airflow',
        Rkey: 'dataTypeEnum',
        Rvalue: 'BOOLEAN',
        inputType: 'SELECT',
        readings: null,
        icon: {
          property: 'URL',
          path: 'off-on-icon.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      supplyFanHOAStatus: {
        value: null,
        readingType: -1,
        displayName: 'Supply Fan HOA Status',
        Rkey: 'dataTypeEnum',
        Rvalue: 'BOOLEAN',
        inputType: 'SELECT',
        enamValue: {
          true: 'Auto',
          false: 'Manual',
        },
        readings: null,
        icon: {
          property: 'TEXT',
          path: 'MANUAL',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      exhaustFanHOAStatus: {
        value: null,
        readingType: -1,
        displayName: 'Exhaust Fan HOA Status',
        Rkey: 'dataTypeEnum',
        Rvalue: 'BOOLEAN',
        inputType: 'SELECT',
        enamValue: {
          true: 'Auto',
          false: 'Manual',
        },
        readings: null,
        icon: {
          property: 'TEXT',
          path: 'MANUAL',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      supplyFanVFDFeedback: {
        value: null,
        readingType: -1,
        displayName: 'Supply Fan VFD Feedback',
        Rkey: 'all',
        Rvalue: 'ALL',
        readings: null,
        inputType: 'SELECT',
        icon: {
          property: 'URL',
          path: 'volve-icon.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      exhaustFanVFDFeedback: {
        value: null,
        readingType: -1,
        displayName: 'Exhaust Fan VFD Feedback',
        Rkey: 'all',
        Rvalue: 'ALL',
        readings: null,
        inputType: 'SELECT',
        icon: {
          property: 'URL',
          path: 'volve-icon.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      supplyFanVFDRuntime: {
        value: null,
        readingType: -1,
        displayName: 'Supply Fan VFD runtime',
        Rkey: 'dataTypeEnum',
        Rvalue: 'DECIMAL',
        inputType: 'SELECT',
        enamValue: {
          true: 'Auto',
          false: 'Manual',
        },
        readings: null,
        icon: {
          property: 'URL',
          path: 'clock.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      exhaustFanVFDRuntime: {
        value: null,
        readingType: -1,
        displayName: 'Exhaust Fan VFD Runtime',
        Rkey: 'dataTypeEnum',
        Rvalue: 'DECIMAL',
        inputType: 'SELECT',
        enamValue: {
          true: 'Auto',
          false: 'Manual',
        },
        readings: null,
        icon: {
          property: 'URL',
          path: 'clock.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      exhaustAirDamperStatus: {
        value: null,
        readingType: -1,
        displayName: 'Exhaust Air Damper',
        Rkey: 'dataTypeEnum',
        Rvalue: 'BOOLEAN',
        inputType: 'SELECT',
        enamValue: {
          true: 'Auto',
          false: 'Manual',
        },
        readings: null,
        icon: {
          property: 'TEXT',
          path: 'MANUAL',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      outsideAirTemperature: {
        value: null,
        readingType: -1,
        displayName: 'Outside Air Temperature',
        Rkey: 'metricEnum',
        Rvalue: 'TEMPERATURE',
        inputType: 'SELECT',
        icon: {
          property: 'URL',
          path: 'thermometer.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      supplyAirTemperature: {
        value: null,
        readingType: -1,
        displayName: 'Supply Air Temperature',
        Rkey: 'metricEnum',
        Rvalue: 'TEMPERATURE',
        inputType: 'SELECT',
        icon: {
          property: 'URL',
          path: 'thermometer.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      supplyAirTemperatureSetpoint: {
        value: null,
        readingType: -1,
        displayName: 'Supply Air Temperature Set Point',
        Rkey: 'all',
        Rvalue: 'ALL',
        inputType: 'SELECT',
        icon: {
          property: 'URL',
          path: 'thermometer.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      returnAirTemperatureAHRW: {
        value: null,
        readingType: -1,
        displayName: 'Return Air Temp After HRW',
        Rkey: 'metricEnum',
        Rvalue: 'TEMPERATURE',
        inputType: 'SELECT',
        icon: {
          property: 'URL',
          path: 'thermometer.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      supplyAirTemperatureBHW: {
        value: null,
        readingType: -1,
        displayName: 'Supply Air Temp Before Heat Wheel',
        Rkey: 'metricEnum',
        Rvalue: 'TEMPERATURE',
        inputType: 'SELECT',
        icon: {
          property: 'URL',
          path: 'thermometer.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      supplyAirTemperatureAHW: {
        value: null,
        readingType: -1,
        displayName: 'Supply Air Tempe After Heat Wheel',
        Rkey: 'metricEnum',
        Rvalue: 'TEMPERATURE',
        inputType: 'SELECT',
        icon: {
          property: 'URL',
          path: 'thermometer.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      returnAirTemperature: {
        value: null,
        readingType: -1,
        displayName: 'Return air temperature',
        Rkey: 'metricEnum',
        Rvalue: 'TEMPERATURE',
        inputType: 'SELECT',
        icon: {
          property: 'URL',
          path: 'thermometer.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      offCoiltemperature: {
        value: null,
        readingType: -1,
        displayName: 'Off Coil Temperature',
        Rkey: 'metricEnum',
        Rvalue: 'TEMPERATURE',
        inputType: 'SELECT',
        icon: {
          property: 'URL',
          path: 'thermometer.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
      onCoiltemperature: {
        value: null,
        readingType: -1,
        displayName: 'On Coil Temperature',
        Rkey: 'metricEnum',
        Rvalue: 'TEMPERATURE',
        inputType: 'SELECT',
        icon: {
          property: 'URL',
          path: 'thermometer.svg',
        },
        meta: {
          'bg-color': '#fff',
          color: '#000',
          layout: {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
          },
        },
      },
    }
    return {
      templates: {
        AHU: {
          name: tools['name'],
          runStatus: tools['runStatus'],
          autoStatus: tools['autoStatus'],
          temperature: tools['temperature'],
          tripStatus: tools['tripStatus'],
          valveFeedback: tools['valveFeedback'],
          scheduledControl: tools['scheduledControl'],
          staticControl: tools['staticControl'],
        },
        PUMP: {
          name: tools['name'],
          runStatusPercent: tools['runStatusPercent'],
          autoStatus: tools['autoStatus'],
          tripStatus: tools['tripStatus'],
        },
        PUMP1: {
          name: tools['name'],
          runStatus: tools['runStatus'],
          autoStatus: tools['autoStatus'],
          percentage: tools['percentage'],
          tripStatus: tools['tripStatus'],
        },
        LIGHT: {
          name: tools['name'],
          lightStatus: tools['lightStatus'],
          tripStatus: tools['tripStatus'],
          autoStatus: tools['autoStatus'],
          scheduledControl: tools['scheduledControl'],
          staticControl: tools['staticControl'],
        },
        WATER_TANK: {
          name: tools['name'],
          levelPercent: tools['levelPercent'],
          levelButton: tools['levelButton'],
        },
        HVAC: {
          name: tools['name'],
          supplyFanStatus: tools['supplyFanStatus'],
          exhaustFanStatus: tools['exhaustFanStatus'],
          heatWheelStatus: tools['heatWheelStatus'],
          temperature: tools['temperature'],
        },
        HVAC2: {
          name: tools['name'],
          runStatusValue: tools['runStatusValue'],
          temperature: tools['temperature'],
        },
        HVAC3: {
          name: tools['name'],
          runStatusValue: tools['runStatusValue'],
          autoStatus: tools['autoStatus'],
          valveFeedback: tools['valveFeedback'],
        },
        HVAC4: {
          name: tools['name'],
          EnthalpyheatWheelStatus: tools['EnthalpyheatWheelStatus'],
          SensibleheatWheelStatus: tools['SensibleheatWheelStatus'],
          chilledWaterSupply: tools['chilledWaterSupply'],
          chilledWaterReturn: tools['chilledWaterReturn'],
          coolingCoilValveFeedback: tools['coolingCoilValveFeedback'],
        },
        HVAC5: {
          name: tools['name'],
          outsideAirDamperStatus: tools['outsideAirDamperStatus'],
          supplyFanAirflow: tools['supplyFanAirflow'],
          supplyFanHOAStatus: tools['supplyFanHOAStatus'],
          supplyFanVFDFeedback: tools['supplyFanVFDFeedback'],
          supplyFanVFDRuntime: tools['supplyFanVFDRuntime'],
        },
        HVAC6: {
          name: tools['name'],
          exhaustAirDamperStatus: tools['exhaustAirDamperStatus'],
          exhaustFanAirflow: tools['exhaustFanAirflow'],
          exhaustFanHOAStatus: tools['exhaustFanHOAStatus'],
          exhaustFanVFDFeedback: tools['exhaustFanVFDFeedback'],
          exhaustFanVFDRuntime: tools['exhaustFanVFDRuntime'],
        },
        HVAC7: {
          name: tools['name'],
          outsideAirTemperature: tools['outsideAirTemperature'],
          supplyAirTemperature: tools['supplyAirTemperature'],
          onCoiltemperature: tools['onCoiltemperature'],
          offCoiltemperature: tools['offCoiltemperature'],
          returnAirTemperature: tools['returnAirTemperature'],
        },
        HVAC8: {
          name: tools['name'],
          supplyAirTemperature: tools['supplyAirTemperature'],
          supplyAirTemperatureSetpoint: tools['supplyAirTemperatureSetpoint'],
          returnAirTemperatureAHRW: tools['returnAirTemperatureAHRW'],
          supplyAirTemperatureBHW: tools['supplyAirTemperatureBHW'],
          supplyAirTemperatureAHW: tools['supplyAirTemperatureAHW'],
        },
        HVAC9: {
          name: tools['name'],
          exhaustFanAirflow: tools['exhaustFanAirflow'],
          exhaustFanHOAStatus: tools['exhaustFanHOAStatus'],
          exhaustFanVFDrunStatus: tools['exhaustFanVFDrunStatus'],
          exhasutFantripStatus: tools['exhasutFantripStatus'],
          exhasutFanvfdtripStatus: tools['exhasutFanvfdtripStatus'],
        },
        HVAC10: {
          name: tools['name'],
          supplyFanAirflow: tools['supplyFanAirflow'],
          supplyFanHOAStatus: tools['supplyFanHOAStatus'],
          supplyFanVFDrunStatus: tools['supplyFanVFDrunStatus'],
          supplyFantripStatus: tools['supplyFantripStatus'],
          supplyFanvfdtripStatus: tools['supplyFanvfdtripStatus'],
        },
      },
      tools: tools,
    }
  },
}
