/* Begin each App with a gap of 100 iconsto accomodate future
  requirements and keep related icons close together
*/
const icons = {
  // main app
  0: { icon: 'sidebar/maintenance1', class: 'icon-sidebar' },
  1: { icon: 'sidebar/space-management1', class: 'icon-sidebar' },
  2: { icon: 'sidebar/billsAlerts', class: 'icon-sidebar' },
  3: { icon: 'sidebar/supplier', class: 'icon-sidebar' },
  4: { icon: 'sidebar/maintenance1', class: 'icon-sidebar' },
  5: { icon: 'sidebar/analytics1', class: 'icon-sidebar' },
  6: { icon: 'sidebar/assets1', class: 'icon-sidebar' },
  7: { icon: 'sidebar/safetyplan', class: 'icon-sidebar' },
  8: { icon: 'sidebar/service-request', class: 'icon-sidebar' },
  9: { icon: 'sidebar/alarm1', class: 'icon-sidebar' },
  10: { icon: 'sidebar/energy-icon', class: 'icon-sidebar' },
  11: { icon: 'sidebar/bar-chart', class: 'icon-sidebar' },
  12: { icon: 'sidebar/tenant-icon', class: 'icon-sidebar' },
  13: { icon: 'sidebar/connectedapp', class: 'icon-sidebar' },
  14: { icon: 'sidebar/people', class: 'icon-sidebar' },
  15: { icon: 'sidebar/control_graphics', class: 'icon-sidebar' },
  16: { icon: 'sidebar/visitor', class: 'icon-sidebar' },
  17: { icon: 'sidebar/client-icon', class: 'icon-sidebar' },
  18: { icon: 'sidebar/contracts', class: 'icon-sidebar' },
  19: { icon: 'sidebar/quotation', class: 'icon-sidebar' },
  20: { icon: 'sidebar/utilities', class: 'icon-sidebar' },
  21: { icon: 'sidebar/community', class: 'icon-sidebar' },
  23: { icon: 'sidebar/budget', class: 'icon-sidebar' },
  24: { icon: 'sidebar/booking', class: 'icon-sidebar' },
  25: { icon: 'sidebar/purchase', class: 'icon-sidebar' },
  26: { icon: 'sidebar/vendor', class: 'icon-sidebar' },
  27: { icon: 'sidebar/inventory', class: 'icon-sidebar' },
  28: { icon: 'sidebar/deliveries', class: 'icon-sidebar' },
  29: { icon: 'sidebar/desk', class: 'icon-sidebar' },
  30: { icon: 'sidebar/document', class: 'icon-sidebar' },
  31: { icon: 'sidebar/floor-map', class: 'icon-sidebar' },
  32: { icon: 'sidebar/lockers', class: 'icon-sidebar' },
  33: { icon: 'sidebar/parking-stalls', class: 'icon-sidebar' },
  34: { icon: 'sidebar/inspection', class: 'icon-sidebar' },
  35: { icon: 'sidebar/induction', class: 'icon-sidebar' },
  36: { icon: 'sidebar/settings', class: 'icon-sidebar' },
  37: { icon: 'sidebar/survey', class: 'icon-sidebar' },

  // operational visibility app
  100: { icon: 'svgs/operations/home' },
  101: { icon: 'svgs/operations/building-performace' },
  102: { icon: 'svgs/operations/asset-health' },
  103: { icon: 'svgs/operations/sustainability' },
  104: { icon: 'svgs/operations/om-visibility' },
  105: { icon: 'svgs/operations/tenant-satisfaction' },
  // Portal apps
  200: { icon: 'svgs/operations/home' },
  201: { icon: 'svgs/tenantportal/workrequest' },
  202: { icon: 'svgs/tenantportal/permits' },
  203: { icon: 'svgs/tenantportal/invites' },
  204: { icon: 'svgs/tenantportal/announcements' },
  205: { icon: 'svgs/tenantportal/service' },
  206: { icon: 'svgs/agent/auditlog' },
  207: { icon: 'svgs/tenantportal/deliveries' },
  208: { icon: 'svgs/tenantportal/desk' },
  209: { icon: 'svgs/tenantportal/document' },
  210: { icon: 'svgs/tenantportal/floor-map' },
  211: { icon: 'svgs/tenantportal/lockers' },
  212: { icon: 'svgs/tenantportal/parking-stalls' },
  // Employee Portal app
  213: { icon: 'svgs/employeePortal/home' },
  214: { icon: 'svgs/employeePortal/floormap' },
  215: { icon: 'svgs/employeePortal/mybooking' },
  216: { icon: 'svgs/employeePortal/service-request' },
  217: { icon: 'svgs/employeePortal/my-request' },
  218: { icon: 'svgs/employeePortal/visitor' },
  219: { icon: 'svgs/employeePortal/deliveries' },
}

export default icons
