export const tabGroup = [
  {
    name: 'common.products.home',
    license: 'SPACE_ASSET',
    route: '/app/home',
    iconType: 1,
    permission: ['space:READ', 'dashboard:READ'],
  },
  {
    name: 'common.products.assets',
    license: 'SPACE_ASSET',
    route: '/app/at',
    iconType: 6,
    permission: ['asset:READ'],
  },
  {
    name: 'common.products.inventory',
    license: 'INVENTORY',
    route: '/app/inventory',
    iconType: 27,
    permission: [
      'inventory:READ,READ_OWN',
      'inventoryrequest:READ,READ_OWN,READ_TEAM',
      'transferrequest:READ',
    ],
  },
  {
    name: 'common.products.maintenance',
    license: 'MAINTENANCE',
    route: '/app/wo',
    iconType: 0,
    permission: [
      'workorder:READ,READ_TEAM,READ_OWN',
      'planned:READ,READ_TEAM,READ_OWN',
    ],
  },
  {
    name: 'common.products.inpsection',
    license: 'INSPECTION',
    route: '/app/inspection',
    iconType: 34,
    permission: ['inspectionTemplate:READ', 'inspectionResponse:READ'],
  },
  {
    name: 'common.products.induction',
    license: 'INDUCTION',
    route: '/app/induction',
    iconType: 35,
    permission: ['inductionTemplate:READ', 'inductionResponse:READ'],
  },
  {
    name: 'common.products.energy',
    license: 'ENERGY_STAR_INTEG',
    route: '/app/en',
    iconType: 10,
  },
  {
    name: 'common.products.analytics',
    license: 'ENERGY',
    route: '/app/em',
    iconType: 5,
    permission: [
      'energy:CREATE_EDIT_REPORTS,VIEW_REPORTS,CREATE_EDIT_DASHBOARD,EXPORT_REPORTS',
    ],
  },
  {
    name: 'common.products.diagnostics',
    license: 'ALARMS',
    route: '/app/fa',
    iconType: 9,
    permission: ['alarm:READ'],
  },
  {
    name: 'common.products.tenants',
    license: 'TENANTS',
    route: '/app/tm',
    iconType: 12,
    permission: ['tenant:READ', 'tenantunit:READ', 'quote:READ'],
  },
  {
    name: 'common.products.purchase_order',
    license: 'PURCHASE',
    route: '/app/purchase',
    iconType: 25,
    permission: [
      'purchaseorder:READ',
      'purchaserequest:READ',
      'termsandconditions:READ',
      'requestForQuotation:READ',
    ],
  },
  {
    name: 'common.header.vendors',
    license: 'VENDOR',
    route: '/app/vendor',
    iconType: 26,
    permission: ['vendors:READ'],
  },
  {
    name: 'common.products.contracts',
    license: 'CONTRACT',
    route: '/app/ct',
    iconType: 18,
    permission: ['contract:READ'],
  },
  {
    name: 'common.products.people',
    license: 'PEOPLE',
    route: '/app/pl',
    iconType: 14,
    permission: ['employee:READ'],
  },
  {
    name: 'common.products.controlsandgraphics',
    license: 'CONTROL_ACTIONS,GRAPHICS',
    route: '/app/co',
    iconType: 15,
    permission: ['asset:READ'],
  },
  {
    name: 'common.products.connectedapps',
    license: 'CONNECTEDAPPS',
    route: '/app/ca',
    iconType: 13,
    enabledOrgId: [17, 659, 1], //Investa
    permission: ['connectedapps:READ'],
  },
  {
    name: 'common.products.visitor',
    license: 'VISITOR',
    route: '/app/vi',
    iconType: 16,
    permission: [
      'visitorlog:READ',
      'invitevisitor:READ',
      'groupinvite:READ',
      'visitor:READ',
      'watchlist:READ',
    ],
  },
  {
    name: 'common.products.help_center',
    license: 'SERVICE_REQUEST',
    route: '/app/sr',
    iconType: 8,
    permission: [
      'serviceRequest:READ',
      'contactdirectory:READ',
      'admindocuments:READ',
    ],
  },
  {
    name: 'common.products.clients',
    license: 'CLIENT',
    route: '/app/cl',
    iconType: 17,
    permission: ['client:READ'],
  },
  {
    name: 'common.products.safety_plan',
    license: 'SAFETY_PLAN',
    route: '/app/sf',
    iconType: 7,
  },
  {
    name: 'common.products.community',
    license: 'COMMUNITY',
    route: '/app/cy',
    iconType: 21,
    permission: [
      'announcement:READ',
      'neighbourhood:READ',
      'dealsandoffers:READ',
      'newsandinformation:READ',
    ],
  },
  {
    name: 'common.products.budget',
    license: 'BUDGET_MONITORING',
    route: '/app/ac',
    iconType: 23,
    permission: ['budget:READ'],
  },
  {
    name: 'common.products.facilitybooking',
    license: 'FACILITY_BOOKING',
    route: '/app/bk',
    iconType: 24,
    permission: ['facility:READ', 'facilitybooking:READ'],
  },
  {
    name: 'common.products.settings',
    route: appName => `/${appName}/setup/home`,
    isSetupTab: true,
    iconType: 36,
    permission: [
      'setup:GENERAL,USER_MANAGEMENT,WORKORDER_SETTINGS,ALARM_SETTINGS,SPACE_SETTINGS,CONTROLLER,ENERGY_ANALYTICS,DATA_ADMINISTRATION,TENANT_BILLING,ASSET_SETTINGS',
    ],
  },
  {
    name: 'common.products.planning',
    license: 'ROUTES_AND_MULTI_RESOURCE',
    route: '/app/planning',
    iconType: 7,
  },
]
