version: 1.0
clientapps:
  - name: default
    baseUrl: https://static.facilio.in
    stageBaseUrl: https://static.facilio.in/dev
  - name: legacy
    baseUrl: https://static.facilio.in
    stageBaseUrl: https://static.facilio.in/dev
  - name: new-default
    baseUrl: https://static.facilio.in/newclient
    stageBaseUrl: https://static.facilio.in/newclient/dev
  - name: auth
    baseUrl: https://static.facilio.in/auth
    stageBaseUrl: https://static.facilio.in/dev
  - name: stateflow
    baseUrl: https://static.facilio.in/stateflow
    stageBaseUrl: https://static.facilio.in/dev
  - name: dataloader
    baseUrl: https://static.facilio.in/dataloader
    stageBaseUrl: https://static.facilio.in/dev
  - name: setup
    baseUrl: https://static.facilio.in/setup
    stageBaseUrl: https://static.facilio.in/setup/dev
  - name: forms
    baseUrl: https://static.facilio.in/forms
    stageBaseUrl: https://static.facilio.in/dev
  - name: dashboard
    baseUrl: https://static.facilio.in/dashboard
    stageBaseUrl: https://static.facilio.in/dev
  - name: weave-builder
    baseUrl: https://static.facilio.in/weave-builder
    stageBaseUrl: https://static.facilio.in/weave-builder/dev
  - name: dispatcher
    baseUrl: https://static.facilio.in/dispatcher
    stageBaseUrl: https://static.facilio.in/dev
  - name: pdf-builder
    baseUrl: https://static.facilio.com
    stageBaseUrl: https://static.facilio.com/dev
