export default {
  data() {
    return {
      defaultOperators: {
        ENUM: {
          ' <= ': {
            dynamicOperator: false,
            operator: ' <= ',
            operatorId: 77,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'LESS_THAN_EQUAL',
          },
          'is empty': {
            dynamicOperator: false,
            operator: 'is empty',
            operatorId: 1,
            valueNeeded: false,
            _name: 'IS_EMPTY',
          },
          ' > ': {
            dynamicOperator: false,
            operator: ' > ',
            operatorId: 78,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'GREATER_THAN',
          },
          ' = ': {
            dynamicOperator: false,
            operator: ' = ',
            operatorId: 74,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'EQUAL',
          },
          ' < ': {
            dynamicOperator: false,
            operator: ' < ',
            operatorId: 76,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'LESS_THAN',
          },
          "value isn't": {
            dynamicOperator: false,
            operator: "value isn't",
            operatorId: 53,
            valueNeeded: true,
            _name: 'VALUE_ISN_T',
          },
          'value is': {
            dynamicOperator: false,
            operator: 'value is',
            operatorId: 52,
            valueNeeded: true,
            _name: 'VALUE_IS',
          },
          is: {
            dynamicOperator: false,
            operator: 'is',
            operatorId: 54,
            valueNeeded: true,
            _name: 'IS',
          },
          'is not empty': {
            dynamicOperator: false,
            operator: 'is not empty',
            operatorId: 2,
            valueNeeded: false,
            _name: 'IS_NOT_EMPTY',
          },
          ' != ': {
            dynamicOperator: false,
            operator: ' != ',
            operatorId: 75,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'NOT_EQUAL',
          },
          "isn't": {
            dynamicOperator: false,
            operator: "isn't",
            operatorId: 55,
            valueNeeded: true,
            _name: 'ISN_T',
          },
          ' >= ': {
            dynamicOperator: false,
            operator: ' >= ',
            operatorId: 79,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'GREATER_THAN_EQUAL',
          },
        },
        NUMBER: {
          '<=': {
            dynamicOperator: false,
            operator: '<=',
            operatorId: 12,
            valueNeeded: true,
            _name: 'LESS_THAN_EQUAL',
          },
          ' > ': {
            dynamicOperator: false,
            operator: ' > ',
            operatorId: 78,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'GREATER_THAN',
          },
          ' = ': {
            dynamicOperator: false,
            operator: ' = ',
            operatorId: 74,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'EQUAL',
          },
          ' < ': {
            dynamicOperator: false,
            operator: ' < ',
            operatorId: 76,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'LESS_THAN',
          },
          'is not empty': {
            dynamicOperator: false,
            operator: 'is not empty',
            operatorId: 2,
            valueNeeded: false,
            _name: 'IS_NOT_EMPTY',
          },
          ' != ': {
            dynamicOperator: false,
            operator: ' != ',
            operatorId: 75,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'NOT_EQUAL',
          },
          ' >= ': {
            dynamicOperator: false,
            operator: ' >= ',
            operatorId: 79,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'GREATER_THAN_EQUAL',
          },
          ' <= ': {
            dynamicOperator: false,
            operator: ' <= ',
            operatorId: 77,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'LESS_THAN_EQUAL',
          },
          'is empty': {
            dynamicOperator: false,
            operator: 'is empty',
            operatorId: 1,
            valueNeeded: false,
            _name: 'IS_EMPTY',
          },
          '!=': {
            dynamicOperator: false,
            operator: '!=',
            operatorId: 10,
            valueNeeded: true,
            _name: 'NOT_EQUALS',
          },
          '<': {
            dynamicOperator: false,
            operator: '<',
            operatorId: 11,
            valueNeeded: true,
            _name: 'LESS_THAN',
          },
          '=': {
            dynamicOperator: false,
            operator: '=',
            operatorId: 9,
            valueNeeded: true,
            _name: 'EQUALS',
          },
          '>': {
            dynamicOperator: false,
            operator: '>',
            operatorId: 13,
            valueNeeded: true,
            _name: 'GREATER_THAN',
          },
          '>=': {
            dynamicOperator: false,
            operator: '>=',
            operatorId: 14,
            valueNeeded: true,
            _name: 'GREATER_THAN_EQUAL',
          },
        },
        MISC: null,
        DECIMAL: {
          '<=': {
            dynamicOperator: false,
            operator: '<=',
            operatorId: 12,
            valueNeeded: true,
            _name: 'LESS_THAN_EQUAL',
          },
          ' > ': {
            dynamicOperator: false,
            operator: ' > ',
            operatorId: 78,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'GREATER_THAN',
          },
          ' = ': {
            dynamicOperator: false,
            operator: ' = ',
            operatorId: 74,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'EQUAL',
          },
          ' < ': {
            dynamicOperator: false,
            operator: ' < ',
            operatorId: 76,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'LESS_THAN',
          },
          'is not empty': {
            dynamicOperator: false,
            operator: 'is not empty',
            operatorId: 2,
            valueNeeded: false,
            _name: 'IS_NOT_EMPTY',
          },
          ' != ': {
            dynamicOperator: false,
            operator: ' != ',
            operatorId: 75,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'NOT_EQUAL',
          },
          ' >= ': {
            dynamicOperator: false,
            operator: ' >= ',
            operatorId: 79,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'GREATER_THAN_EQUAL',
          },
          ' <= ': {
            dynamicOperator: false,
            operator: ' <= ',
            operatorId: 77,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'LESS_THAN_EQUAL',
          },
          'is empty': {
            dynamicOperator: false,
            operator: 'is empty',
            operatorId: 1,
            valueNeeded: false,
            _name: 'IS_EMPTY',
          },
          '!=': {
            dynamicOperator: false,
            operator: '!=',
            operatorId: 10,
            valueNeeded: true,
            _name: 'NOT_EQUALS',
          },
          '<': {
            dynamicOperator: false,
            operator: '<',
            operatorId: 11,
            valueNeeded: true,
            _name: 'LESS_THAN',
          },
          '=': {
            dynamicOperator: false,
            operator: '=',
            operatorId: 9,
            valueNeeded: true,
            _name: 'EQUALS',
          },
          '>': {
            dynamicOperator: false,
            operator: '>',
            operatorId: 13,
            valueNeeded: true,
            _name: 'GREATER_THAN',
          },
          '>=': {
            dynamicOperator: false,
            operator: '>=',
            operatorId: 14,
            valueNeeded: true,
            _name: 'GREATER_THAN_EQUAL',
          },
        },
        BOOLEAN: {
          ' <= ': {
            dynamicOperator: false,
            operator: ' <= ',
            operatorId: 77,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'LESS_THAN_EQUAL',
          },
          'is empty': {
            dynamicOperator: false,
            operator: 'is empty',
            operatorId: 1,
            valueNeeded: false,
            _name: 'IS_EMPTY',
          },
          ' > ': {
            dynamicOperator: false,
            operator: ' > ',
            operatorId: 78,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'GREATER_THAN',
          },
          ' = ': {
            dynamicOperator: false,
            operator: ' = ',
            operatorId: 74,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'EQUAL',
          },
          ' < ': {
            dynamicOperator: false,
            operator: ' < ',
            operatorId: 76,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'LESS_THAN',
          },
          is: {
            dynamicOperator: false,
            operator: 'is',
            operatorId: 15,
            valueNeeded: true,
            _name: 'IS',
          },
          'is not empty': {
            dynamicOperator: false,
            operator: 'is not empty',
            operatorId: 2,
            valueNeeded: false,
            _name: 'IS_NOT_EMPTY',
          },
          ' != ': {
            dynamicOperator: false,
            operator: ' != ',
            operatorId: 75,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'NOT_EQUAL',
          },
          ' >= ': {
            dynamicOperator: false,
            operator: ' >= ',
            operatorId: 79,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'GREATER_THAN_EQUAL',
          },
        },
        DATE: {
          Upcoming: {
            baseLineSupported: false,
            currentOperator: false,
            dynamicOperator: false,
            operator: 'Upcoming',
            operatorId: 73,
            valueNeeded: false,
            _name: 'UPCOMING',
          },
          ' < ': {
            dynamicOperator: false,
            operator: ' < ',
            operatorId: 76,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'LESS_THAN',
          },
          'Current year upto last month': {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'Current year upto last month',
            operatorId: 80,
            valueNeeded: false,
            _name: 'CURRENT_YEAR_UPTO_LAST_MONTH',
          },
          'is after': {
            baseLineSupported: false,
            currentOperator: false,
            dynamicOperator: false,
            operator: 'is after',
            operatorId: 19,
            valueNeeded: true,
            _name: 'IS_AFTER',
          },
          'Current N Year': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Current N Year',
            operatorId: 65,
            valueNeeded: true,
            _name: 'CURRENT_N_YEAR',
          },
          'Last N Months': {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'Last N Months',
            operatorId: 51,
            valueNeeded: true,
            _name: 'LAST_N_MONTHS',
          },
          ' <= ': {
            dynamicOperator: false,
            operator: ' <= ',
            operatorId: 77,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'LESS_THAN_EQUAL',
          },
          'Current Year': {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'Current Year',
            operatorId: 44,
            valueNeeded: false,
            _name: 'CURRENT_YEAR',
          },
          'Current Year upto now': {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'Current Year upto now',
            operatorId: 46,
            valueNeeded: false,
            _name: 'CURRENT_YEAR_UPTO_NOW',
          },
          'Within N Hours': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Within N Hours',
            operatorId: 40,
            valueNeeded: true,
            _name: 'WITHIN_HOURS',
          },
          'In N Day': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'In N Day',
            operatorId: 58,
            valueNeeded: true,
            _name: 'IN_N_DAY',
          },
          'Current Week upto now': {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'Current Week upto now',
            operatorId: 47,
            valueNeeded: false,
            _name: 'CURRENT_WEEK_UPTO_NOW',
          },
          'Age in Days': {
            baseLineSupported: false,
            currentOperator: false,
            dynamicOperator: false,
            operator: 'Age in Days',
            operatorId: 33,
            valueNeeded: true,
            _name: 'AGE_IN_DAYS',
          },
          between: {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: false,
            operator: 'between',
            operatorId: 20,
            valueNeeded: true,
            _name: 'BETWEEN',
          },
          ' = ': {
            dynamicOperator: false,
            operator: ' = ',
            operatorId: 74,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'EQUAL',
          },
          Yesterday: {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Yesterday',
            operatorId: 25,
            valueNeeded: false,
            _name: 'YESTERDAY',
          },
          'Current N Month': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Current N Month',
            operatorId: 64,
            valueNeeded: true,
            _name: 'CURRENT_N_MONTH',
          },
          is: {
            baseLineSupported: false,
            currentOperator: false,
            dynamicOperator: false,
            operator: 'is',
            operatorId: 16,
            valueNeeded: true,
            _name: 'IS',
          },
          'Next N Weeks': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Next N Weeks',
            operatorId: 60,
            valueNeeded: true,
            _name: 'NEXT_N_WEEKS',
          },
          Tomorrow: {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Tomorrow',
            operatorId: 23,
            valueNeeded: false,
            _name: 'TOMORROW',
          },
          ' >= ': {
            dynamicOperator: false,
            operator: ' >= ',
            operatorId: 79,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'GREATER_THAN_EQUAL',
          },
          'Current Week': {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'Current Week',
            operatorId: 31,
            valueNeeded: false,
            _name: 'CURRENT_WEEK',
          },
          'Next N Months': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Next N Months',
            operatorId: 59,
            valueNeeded: true,
            _name: 'NEXT_N_MONTHS',
          },
          'Current N Day': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Current N Day',
            operatorId: 62,
            valueNeeded: true,
            _name: 'CURRENT_N_DAY',
          },
          'Till Yesterday': {
            baseLineSupported: false,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Till Yesterday',
            operatorId: 26,
            valueNeeded: false,
            _name: 'TILL_YESTERDAY',
          },
          'Last Quarter': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Last Quarter',
            operatorId: 69,
            valueNeeded: false,
            _name: 'LAST_QUARTER',
          },
          'Last Month': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Last Month',
            operatorId: 27,
            valueNeeded: false,
            _name: 'LAST_MONTH',
          },
          'Due in Days': {
            baseLineSupported: false,
            currentOperator: false,
            dynamicOperator: false,
            operator: 'Due in Days',
            operatorId: 34,
            valueNeeded: true,
            _name: 'DUE_IN_DAYS',
          },
          'Next N Days': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Next N Days',
            operatorId: 61,
            valueNeeded: true,
            _name: 'NEXT_N_DAYS',
          },
          ' > ': {
            dynamicOperator: false,
            operator: ' > ',
            operatorId: 78,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'GREATER_THAN',
          },
          'Last N Hours': {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'Last N Hours',
            operatorId: 42,
            valueNeeded: true,
            _name: 'LAST_N_HOURS',
          },
          'Last Months': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Last Months',
            operatorId: 39,
            valueNeeded: true,
            _name: 'LAST_MONTHS',
          },
          'Last N Minutes': {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'Last N Minutes',
            operatorId: 56,
            valueNeeded: true,
            _name: 'LAST_N_MINUTES',
          },
          'Current N Quarter': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Current N Quarter',
            operatorId: 67,
            valueNeeded: true,
            _name: 'CURRENT_N_QUARTER',
          },
          'is not empty': {
            dynamicOperator: false,
            operator: 'is not empty',
            operatorId: 2,
            valueNeeded: false,
            _name: 'IS_NOT_EMPTY',
          },
          'Next N Hours': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Next N Hours',
            operatorId: 41,
            valueNeeded: true,
            _name: 'NEXT_HOURS',
          },
          ' != ': {
            dynamicOperator: false,
            operator: ' != ',
            operatorId: 75,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'NOT_EQUAL',
          },
          "isn't": {
            baseLineSupported: false,
            currentOperator: false,
            dynamicOperator: false,
            operator: "isn't",
            operatorId: 17,
            valueNeeded: true,
            _name: 'ISN_T',
          },
          'is before': {
            baseLineSupported: false,
            currentOperator: false,
            dynamicOperator: false,
            operator: 'is before',
            operatorId: 18,
            valueNeeded: true,
            _name: 'IS_BEFORE',
          },
          'Starting Tomorrow': {
            baseLineSupported: false,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Starting Tomorrow',
            operatorId: 24,
            valueNeeded: false,
            _name: 'STARTING_TOMORROW',
          },
          'Last Week': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Last Week',
            operatorId: 30,
            valueNeeded: false,
            _name: 'LAST_WEEK',
          },
          'Current N Week': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Current N Week',
            operatorId: 63,
            valueNeeded: true,
            _name: 'CURRENT_N_WEEK',
          },
          'Hour Start Time': {
            baseLineSupported: false,
            currentOperator: false,
            dynamicOperator: false,
            operator: 'Hour Start Time',
            operatorId: 71,
            valueNeeded: true,
            _name: 'HOUR_START_TIME',
          },
          'Next Month': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Next Month',
            operatorId: 29,
            valueNeeded: false,
            _name: 'NEXT_MONTH',
          },
          'not between': {
            baseLineSupported: false,
            currentOperator: false,
            dynamicOperator: false,
            operator: 'not between',
            operatorId: 21,
            valueNeeded: true,
            _name: 'NOT_BETWEEN',
          },
          'Past Nth day': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Past Nth day',
            operatorId: 57,
            valueNeeded: true,
            _name: 'PAST_N_DAY',
          },
          'Last N Weeks': {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'Last N Weeks',
            operatorId: 50,
            valueNeeded: true,
            _name: 'LAST_N_WEEKS',
          },
          'Last Year': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Last Year',
            operatorId: 45,
            valueNeeded: false,
            _name: 'LAST_YEAR',
          },
          'today upto now': {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'today upto now',
            operatorId: 43,
            valueNeeded: false,
            _name: 'TODAY_UPTO_NOW',
          },
          'This Quarter': {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'This Quarter',
            operatorId: 68,
            valueNeeded: false,
            _name: 'THIS_QUARTER',
          },
          'Last N Days': {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'Last N Days',
            operatorId: 49,
            valueNeeded: true,
            _name: 'LAST_N_DAYS',
          },
          'is empty': {
            dynamicOperator: false,
            operator: 'is empty',
            operatorId: 1,
            valueNeeded: false,
            _name: 'IS_EMPTY',
          },
          Today: {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'Today',
            operatorId: 22,
            valueNeeded: false,
            _name: 'TODAY',
          },
          'This Month Till Yesterday': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'This Month Till Yesterday',
            operatorId: 66,
            valueNeeded: false,
            _name: 'THIS_MONTH_TILL_YESTERDAY',
          },
          'Till Now': {
            baseLineSupported: false,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Till Now',
            operatorId: 72,
            valueNeeded: false,
            _name: 'TILL_NOW',
          },
          'Current Month upto now': {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'Current Month upto now',
            operatorId: 48,
            valueNeeded: false,
            _name: 'CURRENT_MONTH_UPTO_NOW',
          },
          'Next Week': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Next Week',
            operatorId: 32,
            valueNeeded: false,
            _name: 'NEXT_WEEK',
          },
          'LAST N Quarters': {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'LAST N Quarters',
            operatorId: 70,
            valueNeeded: true,
            _name: 'LAST_N_QUARTERS',
          },
          'Current Month': {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'Current Month',
            operatorId: 28,
            valueNeeded: false,
            _name: 'CURRENT_MONTH',
          },
        },
        LOOKUP: {
          ' <= ': {
            dynamicOperator: false,
            operator: ' <= ',
            operatorId: 77,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'LESS_THAN_EQUAL',
          },
          lookup: {
            dynamicOperator: false,
            operator: 'lookup',
            operatorId: 35,
            valueNeeded: true,
            _name: 'LOOKUP',
          },
          'is empty': {
            dynamicOperator: false,
            operator: 'is empty',
            operatorId: 1,
            valueNeeded: false,
            _name: 'IS_EMPTY',
          },
          building_is: {
            dynamicOperator: true,
            operator: 'building_is',
            operatorId: 38,
            valueNeeded: true,
            _name: 'BUILDING_IS',
          },
          ' > ': {
            dynamicOperator: false,
            operator: ' > ',
            operatorId: 78,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'GREATER_THAN',
          },
          ' = ': {
            dynamicOperator: false,
            operator: ' = ',
            operatorId: 74,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'EQUAL',
          },
          ' < ': {
            dynamicOperator: false,
            operator: ' < ',
            operatorId: 76,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'LESS_THAN',
          },
          is: {
            dynamicOperator: true,
            operator: 'is',
            operatorId: 36,
            valueNeeded: true,
            _name: 'IS',
          },
          'is not empty': {
            dynamicOperator: false,
            operator: 'is not empty',
            operatorId: 2,
            valueNeeded: false,
            _name: 'IS_NOT_EMPTY',
          },
          ' != ': {
            dynamicOperator: false,
            operator: ' != ',
            operatorId: 75,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'NOT_EQUAL',
          },
          "isn't": {
            dynamicOperator: true,
            operator: "isn't",
            operatorId: 37,
            valueNeeded: true,
            _name: 'ISN_T',
          },
          ' >= ': {
            dynamicOperator: false,
            operator: ' >= ',
            operatorId: 79,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'GREATER_THAN_EQUAL',
          },
        },
        STRING: {
          ' > ': {
            dynamicOperator: false,
            operator: ' > ',
            operatorId: 78,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'GREATER_THAN',
          },
          ' = ': {
            dynamicOperator: false,
            operator: ' = ',
            operatorId: 74,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'EQUAL',
          },
          "doesn't contain": {
            dynamicOperator: false,
            operator: "doesn't contain",
            operatorId: 6,
            valueNeeded: true,
            _name: 'DOESNT_CONTAIN',
          },
          ' < ': {
            dynamicOperator: false,
            operator: ' < ',
            operatorId: 76,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'LESS_THAN',
          },
          'ends with': {
            dynamicOperator: false,
            operator: 'ends with',
            operatorId: 8,
            valueNeeded: true,
            _name: 'ENDS_WITH',
          },
          is: {
            dynamicOperator: false,
            operator: 'is',
            operatorId: 3,
            valueNeeded: true,
            _name: 'IS',
          },
          'is not empty': {
            dynamicOperator: false,
            operator: 'is not empty',
            operatorId: 2,
            valueNeeded: false,
            _name: 'IS_NOT_EMPTY',
          },
          ' != ': {
            dynamicOperator: false,
            operator: ' != ',
            operatorId: 75,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'NOT_EQUAL',
          },
          "isn't": {
            dynamicOperator: false,
            operator: "isn't",
            operatorId: 4,
            valueNeeded: true,
            _name: 'ISN_T',
          },
          ' >= ': {
            dynamicOperator: false,
            operator: ' >= ',
            operatorId: 79,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'GREATER_THAN_EQUAL',
          },
          ' <= ': {
            dynamicOperator: false,
            operator: ' <= ',
            operatorId: 77,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'LESS_THAN_EQUAL',
          },
          'is empty': {
            dynamicOperator: false,
            operator: 'is empty',
            operatorId: 1,
            valueNeeded: false,
            _name: 'IS_EMPTY',
          },
          contains: {
            dynamicOperator: false,
            operator: 'contains',
            operatorId: 5,
            valueNeeded: true,
            _name: 'CONTAINS',
          },
          'starts with': {
            dynamicOperator: false,
            operator: 'starts with',
            operatorId: 7,
            valueNeeded: true,
            _name: 'STARTS_WITH',
          },
        },
        DATE_TIME: {
          Upcoming: {
            baseLineSupported: false,
            currentOperator: false,
            dynamicOperator: false,
            operator: 'Upcoming',
            operatorId: 73,
            valueNeeded: false,
            _name: 'UPCOMING',
          },
          ' < ': {
            dynamicOperator: false,
            operator: ' < ',
            operatorId: 76,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'LESS_THAN',
          },
          'Current year upto last month': {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'Current year upto last month',
            operatorId: 80,
            valueNeeded: false,
            _name: 'CURRENT_YEAR_UPTO_LAST_MONTH',
          },
          'is after': {
            baseLineSupported: false,
            currentOperator: false,
            dynamicOperator: false,
            operator: 'is after',
            operatorId: 19,
            valueNeeded: true,
            _name: 'IS_AFTER',
          },
          'Current N Year': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Current N Year',
            operatorId: 65,
            valueNeeded: true,
            _name: 'CURRENT_N_YEAR',
          },
          'Last N Months': {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'Last N Months',
            operatorId: 51,
            valueNeeded: true,
            _name: 'LAST_N_MONTHS',
          },
          ' <= ': {
            dynamicOperator: false,
            operator: ' <= ',
            operatorId: 77,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'LESS_THAN_EQUAL',
          },
          'Current Year': {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'Current Year',
            operatorId: 44,
            valueNeeded: false,
            _name: 'CURRENT_YEAR',
          },
          'Current Year upto now': {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'Current Year upto now',
            operatorId: 46,
            valueNeeded: false,
            _name: 'CURRENT_YEAR_UPTO_NOW',
          },
          'Within N Hours': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Within N Hours',
            operatorId: 40,
            valueNeeded: true,
            _name: 'WITHIN_HOURS',
          },
          'In N Day': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'In N Day',
            operatorId: 58,
            valueNeeded: true,
            _name: 'IN_N_DAY',
          },
          'Current Week upto now': {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'Current Week upto now',
            operatorId: 47,
            valueNeeded: false,
            _name: 'CURRENT_WEEK_UPTO_NOW',
          },
          'Age in Days': {
            baseLineSupported: false,
            currentOperator: false,
            dynamicOperator: false,
            operator: 'Age in Days',
            operatorId: 33,
            valueNeeded: true,
            _name: 'AGE_IN_DAYS',
          },
          between: {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: false,
            operator: 'between',
            operatorId: 20,
            valueNeeded: true,
            _name: 'BETWEEN',
          },
          ' = ': {
            dynamicOperator: false,
            operator: ' = ',
            operatorId: 74,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'EQUAL',
          },
          Yesterday: {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Yesterday',
            operatorId: 25,
            valueNeeded: false,
            _name: 'YESTERDAY',
          },
          'Current N Month': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Current N Month',
            operatorId: 64,
            valueNeeded: true,
            _name: 'CURRENT_N_MONTH',
          },
          is: {
            baseLineSupported: false,
            currentOperator: false,
            dynamicOperator: false,
            operator: 'is',
            operatorId: 16,
            valueNeeded: true,
            _name: 'IS',
          },
          'Next N Weeks': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Next N Weeks',
            operatorId: 60,
            valueNeeded: true,
            _name: 'NEXT_N_WEEKS',
          },
          Tomorrow: {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Tomorrow',
            operatorId: 23,
            valueNeeded: false,
            _name: 'TOMORROW',
          },
          ' >= ': {
            dynamicOperator: false,
            operator: ' >= ',
            operatorId: 79,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'GREATER_THAN_EQUAL',
          },
          'Current Week': {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'Current Week',
            operatorId: 31,
            valueNeeded: false,
            _name: 'CURRENT_WEEK',
          },
          'Next N Months': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Next N Months',
            operatorId: 59,
            valueNeeded: true,
            _name: 'NEXT_N_MONTHS',
          },
          'Current N Day': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Current N Day',
            operatorId: 62,
            valueNeeded: true,
            _name: 'CURRENT_N_DAY',
          },
          'Till Yesterday': {
            baseLineSupported: false,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Till Yesterday',
            operatorId: 26,
            valueNeeded: false,
            _name: 'TILL_YESTERDAY',
          },
          'Last Quarter': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Last Quarter',
            operatorId: 69,
            valueNeeded: false,
            _name: 'LAST_QUARTER',
          },
          'Last Month': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Last Month',
            operatorId: 27,
            valueNeeded: false,
            _name: 'LAST_MONTH',
          },
          'Due in Days': {
            baseLineSupported: false,
            currentOperator: false,
            dynamicOperator: false,
            operator: 'Due in Days',
            operatorId: 34,
            valueNeeded: true,
            _name: 'DUE_IN_DAYS',
          },
          'Next N Days': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Next N Days',
            operatorId: 61,
            valueNeeded: true,
            _name: 'NEXT_N_DAYS',
          },
          ' > ': {
            dynamicOperator: false,
            operator: ' > ',
            operatorId: 78,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'GREATER_THAN',
          },
          'Last N Hours': {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'Last N Hours',
            operatorId: 42,
            valueNeeded: true,
            _name: 'LAST_N_HOURS',
          },
          'Last Months': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Last Months',
            operatorId: 39,
            valueNeeded: true,
            _name: 'LAST_MONTHS',
          },
          'Last N Minutes': {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'Last N Minutes',
            operatorId: 56,
            valueNeeded: true,
            _name: 'LAST_N_MINUTES',
          },
          'Current N Quarter': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Current N Quarter',
            operatorId: 67,
            valueNeeded: true,
            _name: 'CURRENT_N_QUARTER',
          },
          'is not empty': {
            dynamicOperator: false,
            operator: 'is not empty',
            operatorId: 2,
            valueNeeded: false,
            _name: 'IS_NOT_EMPTY',
          },
          'Next N Hours': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Next N Hours',
            operatorId: 41,
            valueNeeded: true,
            _name: 'NEXT_HOURS',
          },
          ' != ': {
            dynamicOperator: false,
            operator: ' != ',
            operatorId: 75,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'NOT_EQUAL',
          },
          "isn't": {
            baseLineSupported: false,
            currentOperator: false,
            dynamicOperator: false,
            operator: "isn't",
            operatorId: 17,
            valueNeeded: true,
            _name: 'ISN_T',
          },
          'is before': {
            baseLineSupported: false,
            currentOperator: false,
            dynamicOperator: false,
            operator: 'is before',
            operatorId: 18,
            valueNeeded: true,
            _name: 'IS_BEFORE',
          },
          'Starting Tomorrow': {
            baseLineSupported: false,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Starting Tomorrow',
            operatorId: 24,
            valueNeeded: false,
            _name: 'STARTING_TOMORROW',
          },
          'Last Week': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Last Week',
            operatorId: 30,
            valueNeeded: false,
            _name: 'LAST_WEEK',
          },
          'Current N Week': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Current N Week',
            operatorId: 63,
            valueNeeded: true,
            _name: 'CURRENT_N_WEEK',
          },
          'Hour Start Time': {
            baseLineSupported: false,
            currentOperator: false,
            dynamicOperator: false,
            operator: 'Hour Start Time',
            operatorId: 71,
            valueNeeded: true,
            _name: 'HOUR_START_TIME',
          },
          'Next Month': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Next Month',
            operatorId: 29,
            valueNeeded: false,
            _name: 'NEXT_MONTH',
          },
          'not between': {
            baseLineSupported: false,
            currentOperator: false,
            dynamicOperator: false,
            operator: 'not between',
            operatorId: 21,
            valueNeeded: true,
            _name: 'NOT_BETWEEN',
          },
          'Past Nth day': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Past Nth day',
            operatorId: 57,
            valueNeeded: true,
            _name: 'PAST_N_DAY',
          },
          'Last N Weeks': {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'Last N Weeks',
            operatorId: 50,
            valueNeeded: true,
            _name: 'LAST_N_WEEKS',
          },
          'Last Year': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Last Year',
            operatorId: 45,
            valueNeeded: false,
            _name: 'LAST_YEAR',
          },
          'today upto now': {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'today upto now',
            operatorId: 43,
            valueNeeded: false,
            _name: 'TODAY_UPTO_NOW',
          },
          'This Quarter': {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'This Quarter',
            operatorId: 68,
            valueNeeded: false,
            _name: 'THIS_QUARTER',
          },
          'Last N Days': {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'Last N Days',
            operatorId: 49,
            valueNeeded: true,
            _name: 'LAST_N_DAYS',
          },
          'is empty': {
            dynamicOperator: false,
            operator: 'is empty',
            operatorId: 1,
            valueNeeded: false,
            _name: 'IS_EMPTY',
          },
          Today: {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'Today',
            operatorId: 22,
            valueNeeded: false,
            _name: 'TODAY',
          },
          'This Month Till Yesterday': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'This Month Till Yesterday',
            operatorId: 66,
            valueNeeded: false,
            _name: 'THIS_MONTH_TILL_YESTERDAY',
          },
          'Till Now': {
            baseLineSupported: false,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Till Now',
            operatorId: 72,
            valueNeeded: false,
            _name: 'TILL_NOW',
          },
          'Current Month upto now': {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'Current Month upto now',
            operatorId: 48,
            valueNeeded: false,
            _name: 'CURRENT_MONTH_UPTO_NOW',
          },
          'Next Week': {
            baseLineSupported: true,
            currentOperator: false,
            dynamicOperator: true,
            operator: 'Next Week',
            operatorId: 32,
            valueNeeded: false,
            _name: 'NEXT_WEEK',
          },
          'LAST N Quarters': {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'LAST N Quarters',
            operatorId: 70,
            valueNeeded: true,
            _name: 'LAST_N_QUARTERS',
          },
          'Current Month': {
            baseLineSupported: true,
            currentOperator: true,
            dynamicOperator: true,
            operator: 'Current Month',
            operatorId: 28,
            valueNeeded: false,
            _name: 'CURRENT_MONTH',
          },
        },
        ID: {
          '<=': {
            dynamicOperator: false,
            operator: '<=',
            operatorId: 12,
            valueNeeded: true,
            _name: 'LESS_THAN_EQUAL',
          },
          ' > ': {
            dynamicOperator: false,
            operator: ' > ',
            operatorId: 78,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'GREATER_THAN',
          },
          ' = ': {
            dynamicOperator: false,
            operator: ' = ',
            operatorId: 74,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'EQUAL',
          },
          ' < ': {
            dynamicOperator: false,
            operator: ' < ',
            operatorId: 76,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'LESS_THAN',
          },
          'is not empty': {
            dynamicOperator: false,
            operator: 'is not empty',
            operatorId: 2,
            valueNeeded: false,
            _name: 'IS_NOT_EMPTY',
          },
          ' != ': {
            dynamicOperator: false,
            operator: ' != ',
            operatorId: 75,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'NOT_EQUAL',
          },
          ' >= ': {
            dynamicOperator: false,
            operator: ' >= ',
            operatorId: 79,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'GREATER_THAN_EQUAL',
          },
          ' <= ': {
            dynamicOperator: false,
            operator: ' <= ',
            operatorId: 77,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'LESS_THAN_EQUAL',
          },
          'is empty': {
            dynamicOperator: false,
            operator: 'is empty',
            operatorId: 1,
            valueNeeded: false,
            _name: 'IS_EMPTY',
          },
          '!=': {
            dynamicOperator: false,
            operator: '!=',
            operatorId: 10,
            valueNeeded: true,
            _name: 'NOT_EQUALS',
          },
          '<': {
            dynamicOperator: false,
            operator: '<',
            operatorId: 11,
            valueNeeded: true,
            _name: 'LESS_THAN',
          },
          '=': {
            dynamicOperator: false,
            operator: '=',
            operatorId: 9,
            valueNeeded: true,
            _name: 'EQUALS',
          },
          '>': {
            dynamicOperator: false,
            operator: '>',
            operatorId: 13,
            valueNeeded: true,
            _name: 'GREATER_THAN',
          },
          '>=': {
            dynamicOperator: false,
            operator: '>=',
            operatorId: 14,
            valueNeeded: true,
            _name: 'GREATER_THAN_EQUAL',
          },
        },
        FILE: {
          ' <= ': {
            dynamicOperator: false,
            operator: ' <= ',
            operatorId: 77,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'LESS_THAN_EQUAL',
          },
          'is empty': {
            dynamicOperator: false,
            operator: 'is empty',
            operatorId: 1,
            valueNeeded: false,
            _name: 'IS_EMPTY',
          },
          ' > ': {
            dynamicOperator: false,
            operator: ' > ',
            operatorId: 78,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'GREATER_THAN',
          },
          ' = ': {
            dynamicOperator: false,
            operator: ' = ',
            operatorId: 74,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'EQUAL',
          },
          ' < ': {
            dynamicOperator: false,
            operator: ' < ',
            operatorId: 76,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'LESS_THAN',
          },
          'is not empty': {
            dynamicOperator: false,
            operator: 'is not empty',
            operatorId: 2,
            valueNeeded: false,
            _name: 'IS_NOT_EMPTY',
          },
          ' != ': {
            dynamicOperator: false,
            operator: ' != ',
            operatorId: 75,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'NOT_EQUAL',
          },
          ' >= ': {
            dynamicOperator: false,
            operator: ' >= ',
            operatorId: 79,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'GREATER_THAN_EQUAL',
          },
        },
        COUNTER: {
          ' <= ': {
            dynamicOperator: false,
            operator: ' <= ',
            operatorId: 77,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'LESS_THAN_EQUAL',
          },
          'is empty': {
            dynamicOperator: false,
            operator: 'is empty',
            operatorId: 1,
            valueNeeded: false,
            _name: 'IS_EMPTY',
          },
          ' > ': {
            dynamicOperator: false,
            operator: ' > ',
            operatorId: 78,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'GREATER_THAN',
          },
          ' = ': {
            dynamicOperator: false,
            operator: ' = ',
            operatorId: 74,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'EQUAL',
          },
          ' < ': {
            dynamicOperator: false,
            operator: ' < ',
            operatorId: 76,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'LESS_THAN',
          },
          'is not empty': {
            dynamicOperator: false,
            operator: 'is not empty',
            operatorId: 2,
            valueNeeded: false,
            _name: 'IS_NOT_EMPTY',
          },
          ' != ': {
            dynamicOperator: false,
            operator: ' != ',
            operatorId: 75,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'NOT_EQUAL',
          },
          ' >= ': {
            dynamicOperator: false,
            operator: ' >= ',
            operatorId: 79,
            placeHoldersMandatory: true,
            valueNeeded: false,
            _name: 'GREATER_THAN_EQUAL',
          },
        },
        SYSTEM_ENUM: null,
      },
    }
  },
  methods: {},
}
