<template>
  <el-card class="box-card fc-first-sec-card">
    <div class="flex-middle">
      <div class="fc-pink-circle-img" :style="'background-color:' + '#0eaa95'">
        <inline-svg
          :src="'svgs/employeePortal/quote'"
          iconClass="icon text-center icon-md vertical-bottom"
        ></inline-svg>
      </div>
      <div class="fc-portal-txt-16 pL10">{{ 'Quote of the day' }}</div>
    </div>
    <div class="flex-middle">
      <div class="fc-portal-txt-16 pL10 quest-text">{{ todayQutes }}</div>
    </div>
  </el-card>
</template>
<script>
export default {
  methods: {
    getRandomNumber() {
      let min = 1
      let max = this.quests.length
      return Math.floor(Math.random() * (max - min)) + min
    },
  },
  computed: {
    todayQutes() {
      return this.quests[this.getRandomNumber()] || '---'
    },
  },
  data() {
    return {
      quests: [
        'There are two ways of spreading light: to be the candle or the mirror that reflects it.” – Edith Wharton',
        'You do not find the happy life. You make it.” – Camilla Eyring Kimball',
        'The most wasted of days is one without laughter.” – E.E. Cummings',
        'Stay close to anything that makes you glad you are alive.” – Hafez',
        'Make each day your masterpiece.” – John Wooden',
        'Happiness often sneaks in through a door you didn’t know you left open.” – John Barrymore',
        'Happiness is not by chance, but by choice.” – Jim Rohn',
        'Life changes very quickly, in a very positive way, if you let it.” – Lindsey Vonn',
        'Keep your face to the sunshine and you cannot see a shadow.” – Helen Keller',
        'Impossible is for the unwilling.” – John Keats',
        'No pressure, no diamonds.” – Thomas Carlyle',
        'Believe you can and you’re halfway there.” – Theodore Roosevelt',
        'Failure is the condiment that gives success its flavor.” – Truman Capote',
        'It is never too late to be what you might have been.” – George Eliot',
        'When you have a dream, you’ve got to grab it and never let go.” – Carol Burnett',
        'You must be the change you wish to see in the world.” – Mahatma Gandhi',
        'Stay foolish to stay sane.” – Maxime Lagacé',
        'Stay hungry. Stay foolish.” – Steve Jobs',
        'Whatever you are, be a good one.” – Abraham Lincoln',
        'You must do the things you think you cannot do.” – Eleanor Roosevelt',
        'Wherever you go, go with all your heart.” – Confucius',
        'Be faithful to that which exists within yourself.” – André Gide',
        'Dream big and dare to fail.” – Norman Vaughan',
        'My mission in life is not merely to survive, but to thrive.” – Maya Angelou',
        'You are enough just as you are.” – Meghan Markle',
        'To be the best, you must be able to handle the worst.” – Wilson Kanadi',
        'No matter what you’re going through, there’s a light at the end of the tunnel.” – Demi Lovato',
        'Life is like riding a bicycle. To keep your balance, you must keep moving.” – Albert Einstein',
        'Every moment is a fresh beginning.” – T.S. Eliot',
        'No guts, no story.” – Chris Brady',
        'Keep going. Be all in.” – Bryan Hutchinson',
        'Leave no stone unturned.” – Euripides',
        'Nothing is impossible. The word itself says “I’m possible!” – Audrey Hepburn',
        'It isn’t where you came from. It’s where you’re going that counts.” – Ella Fitzgerald',
        'If it matters to you, you’ll find a way.” – Charlie Gilkey',
        'Tough times never last, but tough people do.” – Dr. Robert Schuller',
        'Turn your wounds into wisdom.” – Oprah Winfrey',
        'The journey of a thousand miles begins with a single step.” – Lao Tzu',
        'If you’re going through hell, keep going.” – Winston Churchill',
        'Don’t wait, the time will never be just right.” – Napoleon Hill',
        'If I cannot do great things, I can do small things in a great way.” – Martin Luther King Jr.',
        'Life is fragile. We’re not guaranteed a tomorrow so give it everything you’ve got.” – Tim Cook',
        'The bad news is time flies. The good news is you’re the pilot.” – Michael Altshuler',
        'Try to be a rainbow in someone’s cloud.” – Maya Angelou',
        'Some people look for a beautiful place. Others make a place beautiful.” – Hazrat Inayat Khan',
        'Never let your sense of morals prevent you from doing what is right.” – Isaac Asimov',
        'Simplicity is the ultimate sophistication.” – Leonardo da Vinci',
        'We have a responsibility to help those around us and help others in need.” – Virginia Williams',
        'No one is useless in this world who lightens the burdens of others.” – Charles Dickens (see more Charles Dickens quotes)',
        'No one has ever become poor by giving.” – Anne Frank',
        'Try Again. Fail again. Fail better.” – Samuel Beckett',
        'The only thing that can grow is the thing you give energy to.” – Ralph Waldo Emerson',
        'Good things happen to those who hustle.” – Anaïs Nin',
        'No greater gift there is, than a generous heart.” – Yoda',
        'Solitary trees, if they grow at all, grow strong.” – Winston Churchill',
        'A hero is someone who has given his or her life to something bigger than oneself.” – Joseph Campbell',
        'You can if you think you can.” – George Reeves',
        'Worrying is like paying a debt you don’t owe.” – Mark Twain',
        'The wisest mind has something yet to learn.” – George Santanaya',
        'Get to the point where you get allergic to average! You don’t think average!” – Eric Thomas',
        'Be yourself; everyone else is already taken.” – Oscar Wilde',
        'It’s no use going back to yesterday because I was a different person then.”― Lewis Carroll',
        'You can’t cross the sea merely by standing and staring at the water.” – Rabindranath Tagore',
        'I’d rather be hated for who I am than loved for who I am not.”― Kurt Cobain',
        'We can do anything we want to if we stick to it long enough.” – Helen Keller',
        'Don’t judge each day by the harvest you reap but by the seeds that you plant.” – Robert Louis Stevenson',
        'I don’t think of all the misery, but of the beauty that still remains.”― Anne Frank',
        'In the middle of every difficulty lies opportunity.” – Albert Einstein',
        'He who has a why to live can bear almost any how.” – Friedrich Nietzsche',
        'If you don’t like the road you’re walking, start paving another one.” – Dolly Parton',
        'Persistence guarantees that results are inevitable.” – Paramahansa Yogananda',
        'Life isn’t about finding yourself. Life is about creating yourself.” – George Bernard Shaw',
        'Dwell on the beauty of life. Watch the stars, and see yourself running with them.” – Marcus Aurelius',
        'Hate cannot drive out hate: only love can do that.” – Martin Luther King Jr.',
        'There is no saint without a past, no sinner without a future.” – Augustine of Hippo',
        'Always do what you are afraid to do.” – Ralph Waldo Emerson',
        'Every noble work is at first impossible.” – Thomas Carlyle',
        'If you can dream it, you can do it.” – Walt Disney',
        'Defeat may serve as well as victory to shake the soul and let the glory out.” – Edwin Markham',
        'Rise above the storm and you will find the sunshine.” – Mario Fernández',
        'Do what you feel in your heart to be right – for you’ll be criticized anyway.“ – Eleanor Roosevelt',
        'Mastering others is strength. Mastering yourself is true power.” – Lao Tzu',
        'Pain is temporary. Quitting lasts forever.“ – Lance Armstrong',
        'The bird a nest, the spider a web, man friendship.” – William Blake',
        'When one door of happiness closes, another opens.“ – Helen Keller',
        'The question is not what you look at, but what you see.”― Henry David Thoreau',
        'It is not the mountain we conquer but ourselves.” – Edmund Hillary',
        'Begin anywhere.” – John Cage',
        'Have faith in yourself and in the future.” – Ted Kennedy',
        'Despite the forecast, live like it’s spring.” – Lily Pulitzer',
        'Do it Now!” – Napoleon Hill',
        'The best way to prepare for life is to begin to live.” – Elbert Hubbard',
        'No great thing is created suddenly.” —Epictetus',
        'And in the end, it’s not the years in your life that count. It is the life in your years.” – Abraham Lincoln',
        'Life is really simple, but we insist on making it complicated.”—Confucius',
        'Life can only be understood backwards, but it must be lived forward.” – Soren Kierkegaard',
        'Man doesn’t know what he is capable of until he is asked.” – Kofi Annan',
        'Courage is fear that has said its prayers.” – Dorothy Bernard',
        'Life is as easy or as hard as you think it is.”– Jonathan Lockwood Huie',
        'Live your dreams.” – Les Brown',
        'The true vocation of man is to find his way for himself.” – Hermann Hesse',
        'A life of sacrifice is the pinnacle of art, and is full of true joy.” – Mahatma Gandhi',
        'No wind favors he who has no destined port.” —Montaigne',
        'It’s not what you look at that matters, it’s what you see.” – Henry David Thoreau',
        'Only a life lived for others is a life worthwhile.” – Albert Einstein',
        'To know oneself, one should assert oneself.” – Albert Camus',
        'Men do less than they ought unless they do all they can.” – Thomas Carlyle',
        'People living deeply have no fear of death.” – Anais Nin',
        'A clever man commits no minor blunders.” – Johann Wolfgang von Goethe',
        'Be not afraid of going slowly, be afraid only of standing still.” – Chinese Proverb',
        'If I’m gonna tell a real story, I’m gonna start with my name.” – Kendrick Lamar',
        'Wake up with determination. Go to bed with satisfaction.”– George Horace Lorimer',
        'All limitations are self-imposed.” – Oliver Wendell Holmes',
        'When you make a choice, you change the future.”– Deepak Chopra',
        'Determine your priorities and focus on them.” – Eileen McDargh',
        'Words are your paintbrush, and your life is the canvas. You can paint whatever you want to paint.”― Miguel Ruiz',
        'Trees that are slow to grow bear the best fruit.”― Moliere',
        'Luck is a matter of preparation meeting opportunity.” – Oprah Winfrey',
        'Let the beauty of what you love be what you do.” – Rumi',
        'Be sure what you want and be sure about yourself.” – Adriana Lima',
        'If you tell the truth you don’t have to remember anything.” – Mark Twain',
        'Re-examine all you have been told. Dismiss what insults your soul.”',
        'Have enough courage to start and enough heart to finish.” – Jessica N. S. Yourko',
        'With our thoughts, we make the world.” – Buddhist proverb',
        'Be so good they can’t ignore you.” – Steve Martin',
        'If opportunity doesn’t knock, build a door.”– Milton Berle',
        'Don’t you know your imperfections is a blessing?” – Kendrick Lamar',
        'Who you are tomorrow begins with what you do today.” – Tim Fargo',
        'Happiness depends upon ourselves.” – Aristotle',
        'You can’t have everything. Where would you put it?” – Steven Wright',
        'Tough times never last but tough people do.” – Robert H. Schiuller',
        'Magic always happens when you direct your inner powers to the object you want to change.”– Bangambiki Habyarimana',
        'I could agree with you but then we’d both be wrong.” – Harvey Specter',
        'The only impossible journey is the one you never begin.”– Tony Robbins',
        'Yesterday you said tomorrow. Just do it.” – Nike',
        'Those at the top of the mountain didn’t fall there.”– Marcus Washling',
        'There is no substitute for hard work.” – Thomas Edison',
        'Mostly, the world sees you the way you see yourself.”– Lisa Nichols',
        'The meaning of life is to give life meaning.” – Ken Hudgins',
        'The elevator to success is out of order. You’ll have to use the stairs, one step at a time.” – Joe Girard',
        'Live as if you were to die tomorrow. Learn as if you were to live forever.” – Mahatma Gandhi',
        'We accept the love we think we deserve.” – Stephen Chbosky',
        'Imperfection is beauty, madness is genius and it’s better to be absolutely ridiculous than absolutely boring.” – Marilyn Monroe',
        'We are all in the gutter, but some of us are looking at the stars.” – Oscar Wilde',
        'There is no greater agony than bearing an untold story inside you.” – Maya Angelou',
        'Everything you can imagine is real.” – Pablo Picasso',
        'Do what you can, with what you have, where you are.” – Theodore Roosevelt',
        'It’s the possibility of having a dream come true that makes life interesting.” – Paulo Coelho',
        'May you live every day of your life.”― Jonathan Swift',
        'Life is too short to waste your time on people who don’t respect, appreciate, and value you.” – Roy T. Bennett',
        'Two wrongs don’t make a right, but they make a good excuse.”― Thomas Szasz',
        'When in doubt, throw doubt out and have a little faith….” – E.A. Bucchianeri',
        'Don’t worry about the challenges. Get excited about the rewards of crushing them.” – Hiral Nagda',
        'Keep going. Is not as difficult as you feel it is. Don’t give up.” – Brandon Sanderson',
        'I may stumble. I may fall. I may cry. But I’ll NEVER give up! Tomorrow, I rise again.” – Steve Maraboli',
        'If my life is going to mean anything, I have to live it myself.”― Rick Riordan',
        'Keep going like there’s a big rock rolling behind you. Never stop until you find ways to dodge it!” – I’m salmiah',
        'There are a thousand reasons to live this life, every one of them is sufficient.” – Marilynne Robinson',
        'If beautiful lilies bloom in ugly waters, you too can blossom in ugly situations.” – Matshona Dhliwayo',
        'Concern yourself not with what you tried and failed in, but with what is still possible to do.” – Hillary Rodham Clinton',
        'Isn’t it nice to think that tomorrow is a new day with no mistakes in it yet?”― L.M. Montgomery',
        'Even a mistake may turn out to be the one thing necessary to a worthwhile achievement.” – Henry Ford',
        'Enjoy the little things, for one day you may look back and realize they were the big things.” – Robert Breault',
        'Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.” – Christian D. Larson',
        'Our greatest glory is not in never falling, but in rising every time we fall.” – Confucius',
        'Dream big, stay positive, work hard, and enjoy the journey.” – Urijah Faber',
        'Nothing is impossible to a willing heart.” – John Heywood',
        'Pain is inevitable. Suffering is optional.”― Haruki Murakami',
        'Don’t get so busy making a living that you forget to make a life.” – Dolly Parton',
        'As soon as you trust yourself, you will know how to live.” – Johann Wolfgang von Goethe',
        'My life is my message.” – Mahatma Gandhi',
        'Nothing can dim the light which shines from within.” – Maya Angelou',
        'Never regret anything that made you smile.” – Mark Twain',
        'You receive from the world what you give to the world.” – Oprah Winfrey',
        'Everything has beauty, but not everyone sees it.” – Confucius',
        'In a gentle way, you can shake the world.” – Mahatma Gandhi',
        'Aim for the moon. If you miss, you may hit a star.” – W. Clement Stone',
        'All progress takes place outside of your comfort zone.” – Michael John Bobak',
        'It always seems impossible until it’s done.” – Nelson Mandela',
        'None but ourselves can free our minds.”― Bob Marley',
        'I don’t need it to be easy, I need it to be worth it.” – Lil Wayne',
        'In the middle of difficulty lies opportunity.” – Albert Einstein',
        'If you love life, don’t waste time, for time is what life is made up of.” – Bruce Lee',
        'He that can have patience can have what he will.” – Benjamin Franklin',
        'Life becomes easier and more beautiful when we can see the good in other people.”― Roy T. Bennett',
        'Don’t quit. Suffer now and live the rest of your life as a champion.” – Muhammad Ali',
        'It’s not whether you get knocked down; it’s whether you get up.” – Vince Lombardi',
        'The only real mistake is the one from which we learn nothing.” – Henry Ford',
        'Surround yourself with only people who are going to lift you higher.” – Oprah Winfrey',
        'Energy and initiative count as much as talent and luck.” – Will Peters',
        'As we are liberated from our own fear, our presence automatically liberates others.“ –',
        'Keep your face always toward the sunshine, and shadows will fall behind you.”— Walt Whitman',
        'There is nothing impossible to they who will try.”— Alexander the Great',
        'Success is not final, failure is not fatal: it is the courage to continue that counts.”– Winston Churchill',
        'You define your own life. Don’t let other people write your script.”— Oprah Winfrey',
        'You are never too old to set another goal or to dream a new dream.”— Malala Yousafzai',
        'Spread love everywhere you go.”— Mother Teresa',
        'You can be everything. You can be the infinite amount of things that people are.”— Kesha',
        'Belief creates the actual fact.”— William James',
        'It is during our darkest moments that we must focus to see the light.”— Aristotle',
        'When we give cheerfully and accept gratefully, everyone is blessed.” – Maya Angelou',
        'There can be glory in failure and despair in success.” – Abraham Lincoln',
        'A wise man will make more opportunities than he finds.” – Francis Bacon',
        'None preaches better than the ant, and she says nothing.” – Benjamin Franklin',
        'A man’s true wealth is the good he does in the world.” – Kahlil Gibran',
        'Ask for what you want and be prepared to get it!”― Maya Angelou',
        'Positive anything is better than negative nothing.” – Elbert Hubbard',
        'If you want to see a rainbow you have to learn to see the rain.” – Paulo Coelho',
        'I’m a slow walker, but I never walk back.” – Abraham Lincoln',
        'You can’t live an exceptional life by being “normal.”” – Nick Maley',
        'Learn as if you will live forever, live like you will die tomorrow.” — Mahatma Gandhi',
        'Don’t let yesterday take up too much of today.” — Will Rogers',
        'To know how much there is to know is the beginning of learning to live.” —Dorothy West',
        'Success usually comes to those who are too busy looking for it.” — Henry David Thoreau',
        'Goal setting is the secret to a compelling future.” — Tony Robbins',
        'It is better to fail in originality than to succeed in imitation.” — Herman Melville',
        'Setting goals is the first step in turning the invisible into the visible.” — Tony Robbins',
        'I never dreamed about success. I worked for it.” —Estée Lauder',
        'Either you run the day or the day runs you.” — Jim Rohn',
        'No act of kindness, no matter how small, is ever wasted.” — Aesop',
        'A place for everything, everything in its place.” — Benjamin Franklin',
        'Every story I create, creates me. I write to create myself.” — Octavia E. Butler',
        'We can’t help everyone, but everyone can help someone.” — Ronald Reagan',
        'We know what we are, but know not what we may be.” — William Shakespeare',
        'We will either find a way, or make one.” – Hannibal',
        'Ah, but a man’s reach should exceed his grasp, Or what’s a heaven for?” — Robert Browning',
        'If I have seen further than others, it is by standing upon the shoulders of giants.” — Isaac Newton',
        'We must let go of the life we have planned, so as to accept the one that is waiting for us.” — Joseph Campbell',
        'Two roads diverged in a wood and I—I took the one less traveled by, and that has made all the difference.” — Robert Frost',
        'I’m a greater believer in luck, and I find the harder I work the more I have of it.” – Thomas Jefferson',
        'Everything should be made as simple as possible but not simpler.” —Albert Einstein',
        'Whether you think you can, or you think you can’t – you’re right.” – Henry Ford',
        'The world you desire can be won. It exists.. it is real.. it is possible.. it’s yours.” —Ayn Rand',
        'Don’t wish it were easier. Wish you were better.” – Jim Rohn',
        'The best way out is always through.” —Robert Frost',
        'Do the hard jobs first. The easy jobs will take care of themselves.” – Dale Carnegie',
        'It’s kind of fun to do the impossible.”― Walt Disney',
        'To think too long about doing a thing often becomes its undoing.” – Eva Young',
        'In matters of style, swim with the current; in matters of principle, stand like a rock.” — Thomas Jefferson',
        'The mind is everything. What you think you become.” – Buddha',
        'Every strike brings me closer to the next home run.” – Babe Ruth',
        'I don’t walk away from things I think are unfinished.” – Arnold Schwarzenegger',
        'Shoot for the moon, even if you fail, you’ll land among the stars.”― Cecelia Ahern',
        'Change the way you look at things and the things you look at change.”― Wayne W. Dyer',
        'The most common way people give up their power is by thinking they don’t have any.” – Alice Walker',
        'Life shrinks or expands in proportion to one’s courage.” – Anais Nin',
        'You miss 100% of the shots you don’t take.” – Wayne Gretzky',
        'You’ll never find a rainbow if you’re looking down.”― Charlie Chaplin',
        'Great things happen to those who don’t stop believing, trying, learning, and being grateful.”― Roy T. Bennett',
        'Write it on your heart that every day is the best day in the year.”― Ralph Waldo Emerson',
        'I kept always two books in my pocket, one to read, one to write in.”― Robert Louis Stevenson',
        'The higher we soar the smaller we appear to those who cannot fly.”― Friedrich Nietzsche',
        'If you want to be happy, be.”― Tolstoy Leo',
        'There is no good and evil, there is only power and those too weak to seek it.”',
        'I am a part of all that I have met.” ― Alfred Tennyson',
        'No one really knows why they are alive until they know what they’d die for.”',
        'Imagination is everything. It is the preview of life’s coming attractions.”― Albert Einstein',
        'A man with outward courage dares to die; a man with inner courage dares to live.” ― Lao Tzu',
        'The future belongs to those who believe in the beauty of their dreams.” – Eleanor Roosevelt',
        'Follow your dreams, they know the way.” – Kobe Yamada',
        'There is only one thing that makes a dream impossible to achieve: the fear of failure.” – Paulo Coelho',
        'It may be that those who do most, dream most.” – Stephen Butler Leacock',
        'Nothing happens unless we first dream.” – Carl Sandburg',
        'Dream as if you’ll live forever, live as if you’ll die today.” – James Dean',
        'Dreams don’t work unless you do.” – John C. Maxwell',
        'Life without dreams is like a bird with a broken wing – it can’t fly.” – Dan Peña',
        'If your dreams don’t scare you, they are too small.” – Richard Branson',
        'Dream no small dreams for they have no power to move the hearts of men.” – Johann Wolfgang von Goethe',
      ],
    }
  },
}
</script>
<style>
.quest-text {
  padding-top: 10px;
  line-height: 20px;
  -webkit-box-pack: center;
  -ms-flex-pack: center;
  justify-content: center;
  color: #a9aeb8 !important;
  font-size: 13px;
  font-weight: 500;
  font-stretch: normal;
  font-style: normal;
  line-height: normal;
  letter-spacing: 0.3px;
  text-align: justify;
  color: #585e68;
  display: block;
  position: absolute;
  top: 60px;
  line-height: 16px;
}
</style>
