-- Create Jobs Table
CREATE TABLE IF NOT EXISTS Jobs2 (
		  JOBID BIGINT AUTO_INCREMENT PRIMARY KEY,
		  ORGID VARCHAR(50),
		  JOBNAME VARCHAR(50),
		  ISPERIODIC BOOLEAN,
		  PERIOD INT,
		  NEXTEXECUTIONTIME BIGINT,
		  EXECUTORNAME VARCHAR(50)
);
