CREATE TABLE IF NOT EXISTS Organizations (
	ORGID BIGINT AUTO_INCREMENT PRIMARY KEY,
	ORGNAME VARCHAR(50),
	FACILIODOMAINNAME VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS Users (
	USERID BIGINT AUTO_INCREMENT PRIMARY KEY,
	COGNITO_ID BIGINT ,
	USER_VERIFIED BOOLEAN,
	EMAIL VARCHAR(150)
);
CREATE TABLE IF NOT EXISTS ORG_Users (
	ORG_USERID BIGINT AUTO_INCREMENT PRIMARY KEY,
	USERID BIGINT ,
	ORGID BIGINT ,
	INVITEDTIME BIGINT,
	INVITATION_ACCEPT_STATUS BOOLEAN
);
CREATE TABLE IF NOT EXISTS Global_Domain_Index (
	DOMAINNAME VARCHAR(50),
	ORGID BIGINT 
);

-- Create Jobs Table
CREATE TABLE IF NOT EXISTS Jobs (
	JOBID BIGINT AUTO_INCREMENT PRIMARY KEY,
	ORGID BIGINT,
	JOBNAME VARCHAR(50),
	ISPERIODIC BOOLEAN,
	PERIOD INT,
	NEXTEXECUTIONTIME BIGINT,
	EXECUTORNAME VARCHAR(50),
	CONSTRAINT JOBS_FK_ORGID FOREIGN KEY (ORGID) REFERENCES Organizations(ORGID)
);

-- Create Tickets Table
CREATE TABLE IF NOT EXISTS Tickets (
	TICKETID BIGINT AUTO_INCREMENT PRIMARY KEY,
	ORGID BIGINT,
	REQUESTOR VARCHAR(50),
	SUBJECT VARCHAR(50),
	DESCRIPTION VARCHAR(1000),
	STATUS TINYINT,
	AGENTID BIGINT,
	FAILED_ASSET BIGINT, 
	DUE_DATE BIGINT,
	CONSTRAINT TICKETS_FK_ORGID FOREIGN KEY (ORGID) REFERENCES Organizations(ORGID),
	CONSTRAINT TICKETS_FK_AGENTID FOREIGN KEY (AGENTID) REFERENCES Users(USERID)
);