INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME, TABLE_NAME) VALUES (${orgId}, 'location', 'Locationsde', 'Locations');
SET @LOCATION_MODULE_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE, IS_MAIN_FIELD) VALUES (${orgId}, @LOCATION_MODULE_ID, 'name', 'Name', 'NAME', 1, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @LOCATION_MODULE_ID, 'street', 'Street', 'STREET', 1);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @LOCATION_MODULE_ID, 'city', 'City', 'CITY', 1);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @LOCATION_MODULE_ID, 'state', 'State / Province', 'STATE', 1);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @LOCATION_MODULE_ID, 'zip', 'Zip / Postal Code', 'ZIP', 1);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @LOCATION_MODULE_ID, 'country', 'Country', 'COUNTRY', 1);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @LOCATION_MODULE_ID, 'lat', 'Latitude', 'LAT', 3);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @LOCATION_MODULE_ID, 'lng', 'Longitude', 'LNG', 3);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @LOCATION_MODULE_ID, 'contact', 'Contact', 'CONTACT', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @LOCATION_MODULE_ID, 'phone', 'Phone', 'PHONE', 1);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @LOCATION_MODULE_ID, 'faxPhone', 'Fax Phone', 'FAX_PHONE', 1);

INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME, TABLE_NAME) VALUES (${orgId}, 'skill', 'Skills', 'Skills');
SET @SKILL_MODULE_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @SKILL_MODULE_ID, 'name', 'Name', 'NAME', 1);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @SKILL_MODULE_ID, 'isActive', 'Active', 'IS_ACTIVE', 4);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @SKILL_MODULE_ID, 'description', 'Description', 'DESCRIPTION', 1);

INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME, TABLE_NAME) VALUES (${orgId}, 'ticketstatus', 'Ticket Status', 'TicketStatus');
SET @TICKET_STATUS_MODULE_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT, IS_MAIN_FIELD) VALUES (${orgId}, @TICKET_STATUS_MODULE_ID, 'status', 'Status', 1, 'STATUS', 1, true, false, true, true);

INSERT INTO TicketStatus (ORGID, MODULEID, STATUS) VALUES (${orgId}, @TICKET_STATUS_MODULE_ID, 'Submitted');
INSERT INTO TicketStatus (ORGID, MODULEID, STATUS) VALUES (${orgId}, @TICKET_STATUS_MODULE_ID, 'Ready');
INSERT INTO TicketStatus (ORGID, MODULEID, STATUS) VALUES (${orgId}, @TICKET_STATUS_MODULE_ID, 'Assigned');
INSERT INTO TicketStatus (ORGID, MODULEID, STATUS) VALUES (${orgId}, @TICKET_STATUS_MODULE_ID, 'Work in Progress');
INSERT INTO TicketStatus (ORGID, MODULEID, STATUS) VALUES (${orgId}, @TICKET_STATUS_MODULE_ID, 'Resolved');
INSERT INTO TicketStatus (ORGID, MODULEID, STATUS) VALUES (${orgId}, @TICKET_STATUS_MODULE_ID, 'Complete');

INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME, TABLE_NAME) VALUES (${orgId}, 'ticketpriority', 'Ticket Priority', 'TicketPriority');
SET @TICKET_PRIORITY_MODULE_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT, IS_MAIN_FIELD) VALUES (${orgId}, @TICKET_PRIORITY_MODULE_ID, 'priority', 'Priority', 1, 'PRIORITY', 1, true, false, true, true);

INSERT INTO TicketPriority (ORGID, MODULEID, PRIORITY) VALUES (${orgId}, @TICKET_PRIORITY_MODULE_ID, 'Critical');
INSERT INTO TicketPriority (ORGID, MODULEID, PRIORITY) VALUES (${orgId}, @TICKET_PRIORITY_MODULE_ID, 'High');
INSERT INTO TicketPriority (ORGID, MODULEID, PRIORITY) VALUES (${orgId}, @TICKET_PRIORITY_MODULE_ID, 'Moderate');
INSERT INTO TicketPriority (ORGID, MODULEID, PRIORITY) VALUES (${orgId}, @TICKET_PRIORITY_MODULE_ID, 'Low');
INSERT INTO TicketPriority (ORGID, MODULEID, PRIORITY) VALUES (${orgId}, @TICKET_PRIORITY_MODULE_ID, 'Planning');

INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME, TABLE_NAME) VALUES (${orgId}, 'ticket', 'Tickets', 'Tickets');
SET @TICKET_MODULE_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @TICKET_MODULE_ID, 'requester', 'Requester', 8, 'REQUESTER', 1, true, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT, IS_MAIN_FIELD) VALUES (${orgId}, @TICKET_MODULE_ID, 'subject', 'Subject', 1, 'SUBJECT', 1, true, false, true, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, PLACE_HOLDER, IS_DEFAULT) VALUES (${orgId}, @TICKET_MODULE_ID, 'description', 'Description', 2, 'DESCRIPTION', 1, true, false, "More about the problem...", true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @TICKET_MODULE_ID, 'status', 'Status', 10, 'STATUS_ID', 7, false, false, true);
INSERT INTO LookupFields (FIELDID, LOOKUP_MODULE_ID) VALUES ((SELECT LAST_INSERT_ID()), @TICKET_STATUS_MODULE_ID);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @TICKET_MODULE_ID, 'priority', 'Priority', 10, 'PRIORITY_ID', 7, false, false, true);
INSERT INTO LookupFields (FIELDID, LOOKUP_MODULE_ID) VALUES ((SELECT LAST_INSERT_ID()), @TICKET_PRIORITY_MODULE_ID);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @TICKET_MODULE_ID, 'assignedTo', 'Assigned To', 11, 'ASSIGNED_TO_ID', 7, false, false, true);
INSERT INTO LookupFields (FIELDID, SPECIAL_TYPE) VALUES ((SELECT LAST_INSERT_ID()), 'users');
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @TICKET_MODULE_ID, 'assetId', 'Asset ID', 9, 'ASSET_ID', 2, false, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @TICKET_MODULE_ID, 'dueDate', 'Due Date', 7, 'DUE_DATE', 6, false, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @TICKET_MODULE_ID, 'areaId', 'Area ID', 9, 'AREA_ID', 2, false, false, true);

INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME, TABLE_NAME) VALUES (${orgId}, 'task', 'Tasks', 'Tasks');
SET @TASK_MODULE_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT, IS_MAIN_FIELD) VALUES (${orgId}, @TASK_MODULE_ID, 'subject', 'Subject', 1, 'SUBJECT', 1, true, false, true, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @TASK_MODULE_ID, 'description', 'Description', 2, 'DESCRIPTION', 1, true, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @TASK_MODULE_ID, 'status', 'Status', 10, 'STATUS_ID', 7, false, false, true);
INSERT INTO LookupFields (FIELDID, LOOKUP_MODULE_ID) VALUES ((SELECT LAST_INSERT_ID()), @TICKET_STATUS_MODULE_ID);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @TASK_MODULE_ID, 'assignmentGroup', 'Assignment Group', 11, 'ASSIGNMENT_GROUP_ID', 7, false, false, true);
INSERT INTO LookupFields (FIELDID, SPECIAL_TYPE) VALUES ((SELECT LAST_INSERT_ID()), 'groups');
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @TASK_MODULE_ID, 'assignedTo', 'Assigned To', 11, 'ASSIGNED_TO_ID', 7, false, false, true);
INSERT INTO LookupFields (FIELDID, SPECIAL_TYPE) VALUES ((SELECT LAST_INSERT_ID()), 'users');
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @TASK_MODULE_ID, 'scheduleId', 'Schedule ID', 9, 'SCHEDULE_ID', 2, false, false, true);

INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME, TABLE_NAME) VALUES (${orgId}, 'campus', 'Campus', 'Campus');
SET @CAMPUS_MODULE_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT, IS_MAIN_FIELD) VALUES (${orgId}, @CAMPUS_MODULE_ID, 'name', 'Name', 1, 'NAME', 1, true, false, true, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @CAMPUS_MODULE_ID, 'currentOccupancy', 'Current Occupancy', 9, 'CURRENT_OCCUPANCY', 2, false, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @CAMPUS_MODULE_ID, 'maxOccupancy', 'Max Occupancy', 9, 'MAX_OCCUPANCY', 2, false, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @CAMPUS_MODULE_ID, 'area', 'Area', 9, 'AREA', 2, false, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @CAMPUS_MODULE_ID, 'location', 'Location', 11, 'LOCATION_ID', 7, false, false, true);
INSERT INTO LookupFields (FIELDID, LOOKUP_MODULE_ID) VALUES ((SELECT LAST_INSERT_ID()), @LOCATION_MODULE_ID);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @CAMPUS_MODULE_ID, 'managedBy', 'Managed By', 11, 'MANAGED_BY', 7, false, false, true);
INSERT INTO LookupFields (FIELDID, SPECIAL_TYPE) VALUES ((SELECT LAST_INSERT_ID()), 'users');
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @CAMPUS_MODULE_ID, 'description', 'Description', 2, 'DESCRIPTION', 1, false, false, true);

INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME, TABLE_NAME) VALUES (${orgId}, 'building', 'Building', 'Building');
SET @BUILDING_MODULE_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT, IS_MAIN_FIELD) VALUES (${orgId}, @BUILDING_MODULE_ID, 'name', 'Name', 1, 'NAME', 1, true, false, true, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @BUILDING_MODULE_ID, 'campus', 'Campus', 11, 'CAMPUS_ID', 7, false, false, true);
INSERT INTO LookupFields (FIELDID, LOOKUP_MODULE_ID) VALUES ((SELECT LAST_INSERT_ID()), @CAMPUS_MODULE_ID);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @BUILDING_MODULE_ID, 'floors', 'Floors', 9, 'FLOORS', 2, false, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @BUILDING_MODULE_ID, 'location', 'Location', 11, 'LOCATION_ID', 7, false, false, true);
INSERT INTO LookupFields (FIELDID, LOOKUP_MODULE_ID) VALUES ((SELECT LAST_INSERT_ID()), @LOCATION_MODULE_ID);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @BUILDING_MODULE_ID, 'area', 'Area', 9, 'AREA', 2, false, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @BUILDING_MODULE_ID, 'currentOccupancy', 'Current Occupancy', 9, 'CURRENT_OCCUPANCY', 2, false, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @BUILDING_MODULE_ID, 'maxOccupancy', 'Max Occupancy', 9, 'MAX_OCCUPANCY', 2, false, false, true);

INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME, TABLE_NAME) VALUES (${orgId}, 'floor', 'Floor', 'Floor');
SET @FLOOR_MODULE_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT, IS_MAIN_FIELD) VALUES (${orgId}, @FLOOR_MODULE_ID, 'name', 'Name', 1, 'NAME', 1, true, false, true, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FLOOR_MODULE_ID, 'building', 'Building', 11, 'BUILDING_ID', 7, false, false, true);
INSERT INTO LookupFields (FIELDID, LOOKUP_MODULE_ID) VALUES ((SELECT LAST_INSERT_ID()), @BUILDING_MODULE_ID);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FLOOR_MODULE_ID, 'mainLevel', 'Main Level', 5, 'MAIN_LEVEL', 4, false, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FLOOR_MODULE_ID, 'Area', 'Area', 9, 'AREA', 2, false, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FLOOR_MODULE_ID, 'currentOccupancy', 'Current Occupancy', 9, 'CURRENT_OCCUPANCY', 2, false, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FLOOR_MODULE_ID, 'maxOccupancy', 'Max Occupancy', 9, 'MAX_OCCUPANCY', 2, false, false, true);

INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME, TABLE_NAME) VALUES (${orgId}, 'spacecategory', 'Space Category', 'Space_Category');
SET @SPACE_CATEGORY_MODULE_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT, IS_MAIN_FIELD) VALUES (${orgId}, @SPACE_CATEGORY_MODULE_ID, 'name', 'Name', 1, 'NAME', 1, true, false, true, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @SPACE_CATEGORY_MODULE_ID, 'description', 'Description', 2, 'DESCRIPTION', 1, true, false, true);

INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME, TABLE_NAME) VALUES (${orgId}, 'space', 'Space', 'Space');
SET @SPACE_MODULE_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT, IS_MAIN_FIELD) VALUES (${orgId}, @SPACE_MODULE_ID, 'displayName', 'Display Name', 1, 'DISPLAY_NAME', 1, true, false, true, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @SPACE_MODULE_ID, 'name', 'Name', 1, 'NAME', 1, true, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @SPACE_MODULE_ID, 'building', 'Building', 11, 'BUILDING_ID', 7, false, false, true);
INSERT INTO LookupFields (FIELDID, LOOKUP_MODULE_ID) VALUES ((SELECT LAST_INSERT_ID()), @BUILDING_MODULE_ID);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @SPACE_MODULE_ID, 'floor', 'Floor', 11, 'FLOOR_ID', 7, false, false, true);
INSERT INTO LookupFields (FIELDID, LOOKUP_MODULE_ID) VALUES ((SELECT LAST_INSERT_ID()), @FLOOR_MODULE_ID);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @SPACE_MODULE_ID, 'area', 'Area', 9, 'AREA', 2, false, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @SPACE_MODULE_ID, 'spaceCategory', 'Space Category', 11, 'SPACE_CATEGORY_ID', 7, false, false, true);
INSERT INTO LookupFields (FIELDID, LOOKUP_MODULE_ID) VALUES ((SELECT LAST_INSERT_ID()), @SPACE_CATEGORY_MODULE_ID);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @SPACE_MODULE_ID, 'availability', 'availability', 9, 'AVAILABILITY', 2, false, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @SPACE_MODULE_ID, 'currentOccupancy', 'Current Occupancy', 9, 'CURRENT_OCCUPANCY', 2, false, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @SPACE_MODULE_ID, 'maxOccupancy', 'Max Occupancy', 9, 'MAX_OCCUPANCY', 2, false, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @SPACE_MODULE_ID, 'occupiable', 'Occupiable', 5, 'OCCUPIABLE', 4, false, false, true);

INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME, TABLE_NAME) VALUES (${orgId}, 'zone', 'Zone', 'Zone');
SET @ZONE_MODULE_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT, IS_MAIN_FIELD) VALUES (${orgId}, @ZONE_MODULE_ID, 'name', 'Name', 1, 'NAME', 1, true, false, true, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @ZONE_MODULE_ID, 'shortDescription', 'Short Description', 2, 'SHORT_DESCRIPTION', 1, false, false, true);