-- dashbaord population starts

INSERT INTO Dashboard (ORGID,MODULEID,DASHBOARD_NAME,PUBLISH_STATUS,LINK_NAME) VALUES (${orgId},${workOrderModuleId},'Overview',0,'overview');
SET @OVERVIEW_DASHBOARD_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Dashboard (ORGID,MODULEID,DASHBOARD_NAME,PUBLISH_STATUS,LINK_NAME) VALUES (${orgId},${workOrderModuleId},'My Workload',0,'myworkload');
SET @TECHNICIAN_DASHBOARD_ID := (SELECT LAST_INSERT_ID());

-- static or list widget population starts
INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT) VALUES (${orgId},${workOrderModuleId},'Workorder Summary',0,100,'Workorder Summary');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Static (ID,STATIC_KEY) VALUES (@WIDGET_ID,'workordersummary');

INSERT INTO Dashboard_vs_Widget (DASHBOARD_ID,WIDGET_ID,LAYOUT_WIDTH,LAYOUT_HEIGHT,X_POSITION,Y_POSITION,LAYOUT_POSITION) VALUES (@OVERVIEW_DASHBOARD_ID,@WIDGET_ID,3,4,9,0,3);


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT) VALUES (${orgId},${workOrderModuleId},'Recent Workorders',2,100,'Recent Workorders');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_List_View (ID,MODULE_NAME,VIEW_NAME) VALUES (@WIDGET_ID,'workorder','open');

INSERT INTO Dashboard_vs_Widget (DASHBOARD_ID,WIDGET_ID,LAYOUT_WIDTH,LAYOUT_HEIGHT,X_POSITION,Y_POSITION,LAYOUT_POSITION) VALUES (@OVERVIEW_DASHBOARD_ID,@WIDGET_ID,8,4,0,4,4);


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT) VALUES (${orgId},${workOrderModuleId},'My Workorder Summary',0,100,'My Workorder Summary');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Static (ID,STATIC_KEY) VALUES (@WIDGET_ID,'mywosummary');

INSERT INTO Dashboard_vs_Widget (DASHBOARD_ID,WIDGET_ID,LAYOUT_WIDTH,LAYOUT_HEIGHT,X_POSITION,Y_POSITION,LAYOUT_POSITION) VALUES (@TECHNICIAN_DASHBOARD_ID,@WIDGET_ID,3,4,0,0,3);

INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT) VALUES (${orgId},${workOrderModuleId},'My Open Workorders',0,100,'My Open Workorders');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_List_View (ID,MODULE_NAME,VIEW_NAME) VALUES (@WIDGET_ID,'workorder','myopen');

INSERT INTO Dashboard_vs_Widget (DASHBOARD_ID,WIDGET_ID,LAYOUT_WIDTH,LAYOUT_HEIGHT,X_POSITION,Y_POSITION,LAYOUT_POSITION) VALUES (@TECHNICIAN_DASHBOARD_ID,@WIDGET_ID,8,4,0,4,4);

-- static or list widget population ends

-- dashboard population ends

INSERT INTO Report_Field (FIELD_LABEL,MODULE_FIELD_ID) VALUES ('wo_status',${workorder_status});
SET @WO_STATUS_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (FIELD_LABEL,MODULE_FIELD_ID) VALUES ('wo_category',${workorder_category});
SET @WO_CATEGORY_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (FIELD_LABEL,MODULE_FIELD_ID) VALUES ('wo_assignedTo',${workorder_assignedTo});
SET @WO_ASSIGNED_TO_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (FIELD_LABEL,MODULE_FIELD_ID) VALUES ('wo_createdTime',${workorder_createdTime});
SET @WO_CREATED_TIME_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (FIELD_LABEL,MODULE_FIELD_ID) VALUES ('wo_priority',${workorder_priority});
SET @WO_PRIORITY_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (FIELD_LABEL,MODULE_FIELD_ID) VALUES ('wo_requester',${workorder_requester});
SET @WO_REQUESTER_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (FIELD_LABEL,MODULE_FIELD_ID) VALUES ('wo_actualWorkEnd',${workorder_actualWorkEnd});
SET @WO_ACTUAL_WORK_END_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (FIELD_LABEL,MODULE_FIELD_ID) VALUES ('wo_noOfNotes',${workorder_noOfNotes});
SET @WO_NO_OF_NOTES_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (FIELD_LABEL,MODULE_FIELD_ID) VALUES ('wo_type',${workorder_type});
SET @WO_TYPE_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (FIELD_LABEL,MODULE_FIELD_ID) VALUES ('wo_assignmentGroup',${workorder_assignmentGroup});
SET @WO_GROUP_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (FIELD_LABEL,MODULE_FIELD_ID) VALUES ('wo_dueDate',${workorder_dueDate});
SET @WO_DUE_DATE_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (FIELD_LABEL,MODULE_FIELD_ID) VALUES ('wo_resource',${workorder_resource});
SET @WO_RESOURCE_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (FIELD_LABEL,MODULE_FIELD_ID) VALUES ('wo_sourceType',${workorder_sourceType});
SET @WO_SOURCE_TYPE_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Formula_Field (ORGID,NAME,DATA_TYPE,FORMULA) VALUES (${orgId},'workorder avg completion date by mins',1,'(ACTUAL_WORK_END-ACTUAL_WORK_START)/1000/60');
INSERT INTO Report_Field (FIELD_LABEL,FORMULA_FIELD_ID) VALUES ('workorder avg completion date by mins',(SELECT LAST_INSERT_ID()));
SET @WO_AVG_COMPLETION_TIME_FF_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Formula_Field (ORGID,NAME,DATA_TYPE,FORMULA) VALUES (${orgId},'workorder overdue status',1,'IF((DUE_DATE-ACTUAL_WORK_END) >= 0,''Ontime'',''Overdue'')');
INSERT INTO Report_Field (FIELD_LABEL,FORMULA_FIELD_ID) VALUES ('workorder overdue status',(SELECT LAST_INSERT_ID()));
SET @WO_OVER_DUE_STATUS_FF_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Formula_Field (ORGID,NAME,DATA_TYPE,FORMULA) VALUES (${orgId},'workorder type',1,'IF((Tickets.SOURCE_TYPE) = 5,''Planned'',''Unplanned'')');
INSERT INTO Report_Field (FIELD_LABEL,FORMULA_FIELD_ID) VALUES ('workorder type',(SELECT LAST_INSERT_ID()));
SET @WO_TYPE_FF_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Formula_Field (ORGID,NAME,DATA_TYPE,FORMULA) VALUES (${orgId},'workorder assigened status',1,'if(ASSIGNED_TO_ID is null,''Unassigned'',''Assigned'')');
INSERT INTO Report_Field (FIELD_LABEL,FORMULA_FIELD_ID) VALUES ('workorder assigened status',(SELECT LAST_INSERT_ID()));
SET @WO_ASIGNED_STATUS_FF_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Formula_Field (ORGID,NAME,DATA_TYPE,FORMULA) VALUES (${orgId},'open workorder status',1,'IF((DUE_DATE-(UNIX_TIMESTAMP()*1000)) >= 0,''Intime'',''Overdue'')');
INSERT INTO Report_Field (FIELD_LABEL,FORMULA_FIELD_ID) VALUES ('open workorder status',(SELECT LAST_INSERT_ID()));
SET @WO_OPEN_STATUS_FF_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Formula_Field (ORGID,NAME,DATA_TYPE,FORMULA) VALUES (${orgId},'workorder avg completion date by hour',1,'(ACTUAL_WORK_END-ACTUAL_WORK_START)/1000/60/60');
INSERT INTO Report_Field (FIELD_LABEL,FORMULA_FIELD_ID) VALUES ('workorder avg completion date by hour',(SELECT LAST_INSERT_ID()));
SET @WO_AVG_COMPLETION_TIME_BY_HOUR_FF_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

-- portfolio report starts

INSERT INTO Report_Folder (ORGID, MODULEID,NAME) VALUES (${orgId}, ${workOrderModuleId},'Portfolio');
SET @REPORT_FOLDER_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AXIS_LABEL,Y1_AXIS_LABEL,GROUP_BY,GROUP_BY_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Open Workorders by Team','Open Workorders by Team',4,@WO_GROUP_REPORT_FIELD_ID,'Team','No of Workorders',@WO_STATUS_REPORT_FIELD_ID,'Status');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 1)');

INSERT INTO Report_Criteria (REPORT_ID,CRITERIA_ID) VALUES (@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_createdTime},28);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AXIS_LABEL,Y1_AXIS,Y1_AGGREGATE_FUNCTION,Y1_AXIS_LABEL,Y1_AXIS_UNIT) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Avg Resolution Time by Team','Avg Resolution Time by Team',9,@WO_GROUP_REPORT_FIELD_ID,'Team',@WO_AVG_COMPLETION_TIME_BY_HOUR_FF_REPORT_FIELD_ID,2,'Avg Resolution Time','minute');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1 and 2 and 3 and 4)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 2)');
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,2,'workorder.actualworkstart','Tickets.ACTUAL_WORK_START',2,'Tickets.ACTUAL_WORK_START IS NOT NULL');
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,3,'workorder.actualworkend','Tickets.ACTUAL_WORK_END',2,'Tickets.ACTUAL_WORK_END IS NOT NULL');
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,4,'workorder.asignedGroup','Tickets.ASSIGNMENT_GROUP_ID',2,'Tickets.ASSIGNMENT_GROUP_ID IS NOT NULL');

INSERT INTO Report_Criteria (REPORT_ID,CRITERIA_ID) VALUES (@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_createdTime},28);

INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AXIS_LABEL,Y1_AXIS_LABEL,GROUP_BY,GROUP_BY_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Closed Workorders by Team','Closed Workorders by Team',4,@WO_GROUP_REPORT_FIELD_ID,'Team','No of Workorders',@WO_PRIORITY_REPORT_FIELD_ID,'Category');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 2)');

INSERT INTO Report_Criteria (REPORT_ID,CRITERIA_ID) VALUES (@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_actualWorkEnd},28);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AXIS_LABEL,Y1_AXIS_LABEL,GROUP_BY,GROUP_BY_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Workorder Volume by Team','Workorder Volume by Team',4,@WO_GROUP_REPORT_FIELD_ID,'Team','No of Workorders',@WO_PRIORITY_REPORT_FIELD_ID,'Category');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_createdTime},28);

-- portfolio report ends

-- open workorders report starts

INSERT INTO Report_Folder (ORGID, MODULEID,NAME) VALUES (${orgId}, ${workOrderModuleId},'Open Workorders');
SET @REPORT_FOLDER_ID := (SELECT LAST_INSERT_ID());


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Open Workorders by Category','Open Workorders by Category',1,@WO_CATEGORY_REPORT_FIELD_ID);
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 1)');

INSERT INTO Report_Criteria (REPORT_ID,CRITERIA_ID) VALUES (@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_createdTime},28);


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT) VALUES (${orgId},${workOrderModuleId},'Open Workorder by Category',1,100,'Open Workorder by Category');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ID,REPORT_ID) VALUES (@WIDGET_ID,@REPORT_ID);

INSERT INTO Dashboard_vs_Widget (DASHBOARD_ID,WIDGET_ID,LAYOUT_WIDTH,LAYOUT_HEIGHT,X_POSITION,Y_POSITION,LAYOUT_POSITION) VALUES (@OVERVIEW_DASHBOARD_ID,@WIDGET_ID,4,4,0,8,6);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Open Workorders by Priority','Open Workorders by Priority',2,@WO_PRIORITY_REPORT_FIELD_ID);
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 1)');

INSERT INTO Report_Criteria (REPORT_ID,CRITERIA_ID) VALUES (@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_createdTime},28);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Open Workorders by Type','Open Workorders by Type',2,@WO_TYPE_REPORT_FIELD_ID);
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 1)');

INSERT INTO Report_Criteria (REPORT_ID,CRITERIA_ID) VALUES (@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_createdTime},28);


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT) VALUES (${orgId},${workOrderModuleId},'Open Workorder by Category',1,100,'Open Workorder by Category');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ID,REPORT_ID) VALUES (@WIDGET_ID,@REPORT_ID);

INSERT INTO Dashboard_vs_Widget (DASHBOARD_ID,WIDGET_ID,LAYOUT_WIDTH,LAYOUT_HEIGHT,X_POSITION,Y_POSITION,LAYOUT_POSITION) VALUES (@OVERVIEW_DASHBOARD_ID,@WIDGET_ID,4,4,4,8,7);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Open Workorders by Techinician','Open Workorders by Techinician',3,@WO_ASSIGNED_TO_REPORT_FIELD_ID);
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 1)');

INSERT INTO Report_Criteria (REPORT_ID,CRITERIA_ID) VALUES (@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_createdTime},28);


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT) VALUES (${orgId},${workOrderModuleId},'Open Workorders by Techinician',1,100,'Open Workorders by Techinician');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ID,REPORT_ID) VALUES (@WIDGET_ID,@REPORT_ID);

INSERT INTO Dashboard_vs_Widget (DASHBOARD_ID,WIDGET_ID,LAYOUT_WIDTH,LAYOUT_HEIGHT,X_POSITION,Y_POSITION,LAYOUT_POSITION) VALUES (@OVERVIEW_DASHBOARD_ID,@WIDGET_ID,4,4,8,8,8);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Open Workorders by Team','Open Workorders by Team',2,@WO_GROUP_REPORT_FIELD_ID);
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 1)');

INSERT INTO Report_Criteria (REPORT_ID,CRITERIA_ID) VALUES (@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_createdTime},28);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Open Workorders by Due Date','Open Workorders by Due Date',3,@WO_DUE_DATE_REPORT_FIELD_ID,12);
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 1)');

INSERT INTO Report_Criteria (REPORT_ID,CRITERIA_ID) VALUES (@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_dueDate},28);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Open Workorders by Created Date','Open Workorders by Created Date',3,@WO_CREATED_TIME_REPORT_FIELD_ID,12);
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 1)');

INSERT INTO Report_Criteria (REPORT_ID,CRITERIA_ID) VALUES (@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_createdTime},28);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Open Workorders by Status','Open Workorders by Status',3,@WO_STATUS_REPORT_FIELD_ID);
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 1)');

INSERT INTO Report_Criteria (REPORT_ID,CRITERIA_ID) VALUES (@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_createdTime},28);


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT) VALUES (${orgId},${workOrderModuleId},'Open Workorders',1,100,'Open Workorders');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ID,REPORT_ID) VALUES (@WIDGET_ID,@REPORT_ID);

INSERT INTO Dashboard_vs_Widget (DASHBOARD_ID,WIDGET_ID,LAYOUT_WIDTH,LAYOUT_HEIGHT,X_POSITION,Y_POSITION,LAYOUT_POSITION) VALUES (@OVERVIEW_DASHBOARD_ID,@WIDGET_ID,4,4,0,0,1);

-- open workorders report ends

INSERT INTO Report_Folder (ORGID, MODULEID,NAME) VALUES (${orgId}, ${workOrderModuleId},'Closed Workorders');
SET @REPORT_FOLDER_ID := (SELECT LAST_INSERT_ID());


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Closed Workorders by Type','Closed Workorders by Type',1,@WO_TYPE_REPORT_FIELD_ID,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 2)');

INSERT INTO Report_Criteria (REPORT_ID,CRITERIA_ID) VALUES (@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_actualWorkEnd},28);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());


INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Closed Workorders by Team','Closed Workorders by Team',3,@WO_GROUP_REPORT_FIELD_ID,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 2)');

INSERT INTO Report_Criteria (REPORT_ID,CRITERIA_ID) VALUES (@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_actualWorkEnd},28);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Closed Workorders by Category','Closed Workorders by Category',6,@WO_CATEGORY_REPORT_FIELD_ID,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 2)');

INSERT INTO Report_Criteria (REPORT_ID,CRITERIA_ID) VALUES (@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_actualWorkEnd},28);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Closed Workorders by Priority','Closed Workorders by Priority',3,@WO_PRIORITY_REPORT_FIELD_ID,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 2)');

INSERT INTO Report_Criteria (REPORT_ID,CRITERIA_ID) VALUES (@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_actualWorkEnd},28);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Closed Workorders by Due Date','Closed Workorders by Due Date',12,@WO_DUE_DATE_REPORT_FIELD_ID,12,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 2)');

INSERT INTO Report_Criteria (REPORT_ID,CRITERIA_ID) VALUES (@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_actualWorkEnd},28);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Closed Workorders by Created Date','Closed Workorders by Created Date',12,@WO_CREATED_TIME_REPORT_FIELD_ID,12,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 2)');

INSERT INTO Report_Criteria (REPORT_ID,CRITERIA_ID) VALUES (@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_actualWorkEnd},28);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Closed Workorders by Techinician','Closed Workorders by Techinician',1,@WO_ASSIGNED_TO_REPORT_FIELD_ID,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 2)');

INSERT INTO Report_Criteria (REPORT_ID,CRITERIA_ID) VALUES (@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_actualWorkEnd},28);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION,X_AXIS_LABEL,Y1_AXIS_LABEL,GROUP_BY,GROUP_BY_LABEL) VALUES(${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Closed Workorders Trend','Closed Workorders Trend',3,@WO_ASSIGNED_TO_REPORT_FIELD_ID,12,'Date','No of Workorders',@WO_OVER_DUE_STATUS_FF_REPORT_FIELD_ID,'Actual Work End');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 2)');

INSERT INTO Report_Criteria (REPORT_ID,CRITERIA_ID) VALUES (@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_actualWorkEnd},28);


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT) VALUES (${orgId},${workOrderModuleId},'Closed Workorders Trend',1,100,'Closed Workorders Trend');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ID,REPORT_ID) VALUES (@WIDGET_ID,@REPORT_ID);

INSERT INTO Dashboard_vs_Widget (DASHBOARD_ID,WIDGET_ID,LAYOUT_WIDTH,LAYOUT_HEIGHT,X_POSITION,Y_POSITION,LAYOUT_POSITION) VALUES (@OVERVIEW_DASHBOARD_ID,@WIDGET_ID,5,4,4,0,2);

-- closed workorders report ends

-- All workorders report starts

INSERT INTO Report_Folder (ORGID, MODULEID,NAME) VALUES (${orgId}, ${workOrderModuleId},'All Workorders');
SET @REPORT_FOLDER_ID := (SELECT LAST_INSERT_ID());


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'All Workorders by Category','All Workorders by Category',1,@WO_CATEGORY_REPORT_FIELD_ID,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_createdTime},28);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'All Workorders by Priority','All Workorders by Priority',1,@WO_PRIORITY_REPORT_FIELD_ID,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_createdTime},28);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'All Workorders by Type','All Workorders by Type',1,@WO_TYPE_REPORT_FIELD_ID,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_createdTime},28);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'All Workorders by Techinician','All Workorders by Techinician',1,@WO_ASSIGNED_TO_REPORT_FIELD_ID,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_createdTime},28);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'All Workorders by Team','All Workorders by Team',1,@WO_GROUP_REPORT_FIELD_ID,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_createdTime},28);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'All Workorders by Due Date','All Workorders by Due Date',1,@WO_DUE_DATE_REPORT_FIELD_ID,12,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_createdTime},28);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'All Workorders by Created Date','All Workorders by Created Date',1,@WO_CREATED_TIME_REPORT_FIELD_ID,12,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_createdTime},28);


-- All workorders report ends

-- Top N reports starts

INSERT INTO Report_Folder (ORGID, MODULEID,NAME) VALUES (${orgId}, ${workOrderModuleId},'Top N Reports');
SET @REPORT_FOLDER_ID := (SELECT LAST_INSERT_ID());


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Top N Technicians','Top N Technicians',1,@WO_ASSIGNED_TO_REPORT_FIELD_ID,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_createdTime},28);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Top N Categories','Top N Categories',1,@WO_CATEGORY_REPORT_FIELD_ID,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_createdTime},28);

-- Top N reports ends

-- Efficiency reports starts

INSERT INTO Report_Folder (ORGID, MODULEID,NAME) VALUES (${orgId}, ${workOrderModuleId},'Efficiency');
SET @REPORT_FOLDER_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AXIS_LABEL,Y1_AXIS,Y1_AGGREGATE_FUNCTION,Y1_AXIS_LABEL,Y1_AXIS_UNIT) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Avg Resolution Time by Technician','Avg Resolution Time by Technician',9,@WO_ASSIGNED_TO_REPORT_FIELD_ID,'Technician',@WO_AVG_COMPLETION_TIME_BY_HOUR_FF_REPORT_FIELD_ID,2,'Avg Resolution Time','Hrs');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_createdTime},28);

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1 and 2 and 3 and 4)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,1,'workorder.status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 2)');
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,2,'workorder.actualworkstart','Tickets.ACTUAL_WORK_START',2,'Tickets.ACTUAL_WORK_START IS NOT NULL');
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,3,'workorder.actualworkend','Tickets.ACTUAL_WORK_END',2,'Tickets.ACTUAL_WORK_END IS NOT NULL');
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,4,'workorder.asignedto','Tickets.ASSIGNED_TO_ID',2,'Tickets.ASSIGNED_TO_ID IS NOT NULL');

INSERT INTO Report_Criteria (REPORT_ID,CRITERIA_ID) VALUES (@REPORT_ID,@CRITERIA_ID);


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT) VALUES (${orgId},${workOrderModuleId},'Avg Resolution Time by Technician',1,100,'Avg Resolution Time by Technician');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ID,REPORT_ID) VALUES (@WIDGET_ID,@REPORT_ID);

INSERT INTO Dashboard_vs_Widget (DASHBOARD_ID,WIDGET_ID,LAYOUT_WIDTH,LAYOUT_HEIGHT,X_POSITION,Y_POSITION,LAYOUT_POSITION) VALUES (@OVERVIEW_DASHBOARD_ID,@WIDGET_ID,4,4,8,4,5);

-- Efficiency reports ends

-- Inflow trends starts

INSERT INTO Report_Folder (ORGID, MODULEID,NAME) VALUES (${orgId}, ${workOrderModuleId},'Inflow Trend');
SET @REPORT_FOLDER_ID := (SELECT LAST_INSERT_ID());


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Work Orders Inflow Trend - By date','Work Orders Inflow Trend - By date',3,@WO_CREATED_TIME_REPORT_FIELD_ID,12);
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_createdTime},28);


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT) VALUES (${orgId},${workOrderModuleId},'Workorder Inflow Trend',1,100,'Workorder Inflow Trend');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ID,REPORT_ID) VALUES (@WIDGET_ID,@REPORT_ID);

INSERT INTO Dashboard_vs_Widget (DASHBOARD_ID,WIDGET_ID,LAYOUT_WIDTH,LAYOUT_HEIGHT,X_POSITION,Y_POSITION,LAYOUT_POSITION) VALUES (@OVERVIEW_DASHBOARD_ID,@WIDGET_ID,12,4,0,12,9);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Work Orders Inflow Trend - By Month','Work Orders Inflow Trend - By Month',3,@WO_CREATED_TIME_REPORT_FIELD_ID,10);
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_createdTime},44);

-- Inflow trends end

-- My Reports starts

INSERT INTO Report_Folder (ORGID, MODULEID,NAME) VALUES (${orgId}, ${workOrderModuleId},'My Reports');
SET @REPORT_FOLDER_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Open Workorders by Category','Open Workorders by Category',1,@WO_CATEGORY_REPORT_FIELD_ID);
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1 and 2)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 1)');
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,VAL,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,2,'assignedTo','Tickets.ASSIGNED_TO_ID',36,'${LOGGED_USER}','Tickets.ASSIGNED_TO_ID = ?');

INSERT INTO Report_Criteria (REPORT_ID,CRITERIA_ID) VALUES (@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_createdTime},28);


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT) VALUES (${orgId},${workOrderModuleId},'My Open Workorders by Category',1,100,'My Open Workorders by Category');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ID,REPORT_ID) VALUES (@WIDGET_ID,@REPORT_ID);

INSERT INTO Dashboard_vs_Widget (DASHBOARD_ID,WIDGET_ID,LAYOUT_WIDTH,LAYOUT_HEIGHT,X_POSITION,Y_POSITION,LAYOUT_POSITION) VALUES (@TECHNICIAN_DASHBOARD_ID,@WIDGET_ID,4,4,8,4,2);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Open Workorders by Priority','Open Workorders by Priority',2,@WO_PRIORITY_REPORT_FIELD_ID);
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1 and 2)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 1)');
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,VAL,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,2,'assignedTo','Tickets.ASSIGNED_TO_ID',36,'${LOGGED_USER}','Tickets.ASSIGNED_TO_ID = ?');

INSERT INTO Report_Criteria (REPORT_ID,CRITERIA_ID) VALUES (@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_createdTime},28);


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT) VALUES (${orgId},${workOrderModuleId},'Open Workorders by Priority',1,100,'Open Workorders by Priority');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ID,REPORT_ID) VALUES (@WIDGET_ID,@REPORT_ID);

INSERT INTO Dashboard_vs_Widget (DASHBOARD_ID,WIDGET_ID,LAYOUT_WIDTH,LAYOUT_HEIGHT,X_POSITION,Y_POSITION,LAYOUT_POSITION) VALUES (@TECHNICIAN_DASHBOARD_ID,@WIDGET_ID,4,4,3,0,5);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION,X_AXIS_LABEL,GROUP_BY,GROUP_BY_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Closed Workorders Trend','Closed Workorders Trend',3,@WO_ACTUAL_WORK_END_REPORT_FIELD_ID,12,'Actual Work End',@WO_OVER_DUE_STATUS_FF_REPORT_FIELD_ID,'Actual Work End');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1 and 2)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 1)');
INSERT INTO Conditions (PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,VAL,COMPUTED_WHERE_CLAUSE) VALUES (@CRITERIA_ID,2,'assignedTo','Tickets.ASSIGNED_TO_ID',36,'${LOGGED_USER}','Tickets.ASSIGNED_TO_ID = ?');

INSERT INTO Report_Criteria (REPORT_ID,CRITERIA_ID) VALUES (@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (REPORT_ID,FIELD_ID,OPERATOR) VALUES (@REPORT_ID,${workorder_actualWorkEnd},28);

INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT) VALUES (${orgId},${workOrderModuleId},'My Closed Workorders Trend',1,100,'My Closed Workorders Trend');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ID,REPORT_ID) VALUES (@WIDGET_ID,@REPORT_ID);

INSERT INTO Dashboard_vs_Widget (DASHBOARD_ID,WIDGET_ID,LAYOUT_WIDTH,LAYOUT_HEIGHT,X_POSITION,Y_POSITION,LAYOUT_POSITION) VALUES (@TECHNICIAN_DASHBOARD_ID,@WIDGET_ID,5,4,7,0,4);

-- My Reports ends

