INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME) VALUES (${orgId}, 'Tickets', 'Tickets');
SET @TICKET_MODULE_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @TICKET_MODULE_ID, 'ticketId', 'Ticket ID', 'TICKETID', 0);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @TICKET_MODULE_ID, 'requester', 'Requester', 'REQUESTER', 1);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @TICKET_MODULE_ID, 'subject', 'Subject', 'SUBJECT', 1);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @TICKET_MODULE_ID, 'description', 'Description', 'DESCRIPTION', 1);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @TICKET_MODULE_ID, 'statusCode', 'Status', 'STATUS', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @TICKET_MODULE_ID, 'assignedToId', 'Assigned To ID', 'ASSIGNED_TO_ID', 7);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @TICKET_MODULE_ID, 'assetId', 'Asset ID', 'ASSET_ID', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @TICKET_MODULE_ID, 'dueDate', 'Due Date', 'DUE_DATE', 6);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @TICKET_MODULE_ID, 'areaId', 'Area ID', 'AREA_ID', 2);

INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME) VALUES (${orgId}, 'Tasks', 'Tasks');
SET @TASK_MODULE_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @TASK_MODULE_ID, 'taskId', 'Task ID', 'TASKID', 0);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @TASK_MODULE_ID, 'subject', 'Subject', 'SUBJECT', 1);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @TASK_MODULE_ID, 'description', 'Description', 'DESCRIPTION', 1);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @TASK_MODULE_ID, 'statusCode', 'Status', 'STATUS', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @TASK_MODULE_ID, 'assignmentGroupId', 'Assignment Group ID', 'ASSIGNMENT_GROUP_ID', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @TASK_MODULE_ID, 'assignedToId', 'Assigned To ID', 'ASSIGNED_TO_ID', 7);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @TASK_MODULE_ID, 'scheduleId', 'Schedule ID', 'SCHEDULE_ID', 2);

INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME) VALUES (${orgId}, 'Campus', 'Campus');
SET @CAMPUS_MODULE_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @CAMPUS_MODULE_ID, 'campusId', 'Campus ID', 'CAMPUS_ID', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @CAMPUS_MODULE_ID, 'name', 'Name', 'NAME', 1);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @CAMPUS_MODULE_ID, 'currentOccupancy', 'Current Occupancy', 'CURRENT_OCCUPANCY', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @CAMPUS_MODULE_ID, 'maxOccupancy', 'Max Occupancy', 'MAX_OCCUPANCY', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @CAMPUS_MODULE_ID, 'area', 'Area', 'AREA', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @CAMPUS_MODULE_ID, 'locationId', 'Location ID', 'LOCATION_ID', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @CAMPUS_MODULE_ID, 'managedBy', 'Managed By', 'MANAGED_BY', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @CAMPUS_MODULE_ID, 'description', 'Description', 'DESCRIPTION', 1);

INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME) VALUES (${orgId}, 'Building', 'Building');
SET @BUILDING_MODULE_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @BUILDING_MODULE_ID, 'buildingId', 'Building ID', 'BUILDING_ID', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @BUILDING_MODULE_ID, 'name', 'Name', 'NAME', 1);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @BUILDING_MODULE_ID, 'campusId', 'Campus ID', 'CAMPUS_ID', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @BUILDING_MODULE_ID, 'floors', 'Floors', 'FLOORS', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @BUILDING_MODULE_ID, 'locationId', 'Location ID', 'LOCATION_ID', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @BUILDING_MODULE_ID, 'area', 'Area', 'AREA', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @BUILDING_MODULE_ID, 'currentOccupancy', 'Current Occupancy', 'CURRENT_OCCUPANCY', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @BUILDING_MODULE_ID, 'maxOccupancy', 'Max Occupancy', 'MAX_OCCUPANCY', 2);

INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME) VALUES (${orgId}, 'Floor', 'Floor');
SET @FLOOR_MODULE_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @FLOOR_MODULE_ID, 'floorId', 'Floor ID', 'FLOOR_ID', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @FLOOR_MODULE_ID, 'name', 'Name', 'NAME', 1);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @FLOOR_MODULE_ID, 'buildingId', 'Building ID', 'BUILDING_ID', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @FLOOR_MODULE_ID, 'mainLevel', 'Main Level', 'MAIN_LEVEL', 4);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @FLOOR_MODULE_ID, 'Area', 'Area', 'AREA', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @FLOOR_MODULE_ID, 'currentOccupancy', 'Current Occupancy', 'CURRENT_OCCUPANCY', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @FLOOR_MODULE_ID, 'maxOccupancy', 'Max Occupancy', 'MAX_OCCUPANCY', 2);

INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME) VALUES (${orgId}, 'Space_Category', 'Space Category');
SET @SPACE_CATEGORY_MODULE_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @SPACE_CATEGORY_MODULE_ID, 'spaceCategoryId', 'Space Category ID', 'SPACE_CATEGORY_ID', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @SPACE_CATEGORY_MODULE_ID, 'name', 'Name', 'NAME', 1);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @SPACE_CATEGORY_MODULE_ID, 'description', 'Description', 'DESCRIPTION', 1);

INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME) VALUES (${orgId}, 'Space', 'Space');
SET @SPACE_MODULE_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @SPACE_MODULE_ID, 'spaceId', 'Space ID', 'SPACE_ID', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @SPACE_MODULE_ID, 'displayName', 'Display Name', 'DISPLAY_NAME', 1);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @SPACE_MODULE_ID, 'name', 'Name', 'NAME', 1);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @SPACE_MODULE_ID, 'buildingId', 'Building ID', 'BUILDING_ID', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @SPACE_MODULE_ID, 'floorId', 'Floor ID', 'FLOOR_ID', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @SPACE_MODULE_ID, 'area', 'Area', 'AREA', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @SPACE_MODULE_ID, 'spaceCategoryId', 'Space Category ID', 'SPACE_CATEGORY_ID', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @SPACE_MODULE_ID, 'availability', 'availability', 'AVAILABILITY', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @SPACE_MODULE_ID, 'currentOccupancy', 'Current Occupancy', 'CURRENT_OCCUPANCY', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @SPACE_MODULE_ID, 'maxOccupancy', 'Max Occupancy', 'MAX_OCCUPANCY', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @SPACE_MODULE_ID, 'occupiable', 'Occupiable', 'OCCUPIABLE', 4);

INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME) VALUES (${orgId}, 'Zone', 'Zone');
SET @ZONE_MODULE_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @ZONE_MODULE_ID, 'zoneId', 'Zone ID', 'ZONE_ID', 0);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @ZONE_MODULE_ID, 'name', 'Name', 'NAME', 1);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @ZONE_MODULE_ID, 'shortDescription', 'Short Description', 'SHORT_DESCRIPTION', 1);

INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME) VALUES (${orgId}, 'Location', 'Location');
SET @LOCATION_MODULE_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @LOCATION_MODULE_ID, 'locationId', 'Location ID', 'LOCATION_ID', 0);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @LOCATION_MODULE_ID, 'name', 'Name', 'NAME', 1);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @LOCATION_MODULE_ID, 'street', 'Street', 'STREET', 1);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @LOCATION_MODULE_ID, 'city', 'City', 'CITY', 1);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @LOCATION_MODULE_ID, 'state', 'State / Province', 'STATE', 1);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @LOCATION_MODULE_ID, 'zip', 'Zip / Postal Code', 'ZIP', 1);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @LOCATION_MODULE_ID, 'country', 'Country', 'COUNTRY', 1);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @LOCATION_MODULE_ID, 'lat', 'Latitude', 'LAT', 3);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @LOCATION_MODULE_ID, 'lng', 'Longitude', 'LNG', 3);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @LOCATION_MODULE_ID, 'contact', 'Contact', 'CONTACT', 2);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @LOCATION_MODULE_ID, 'phone', 'Phone', 'PHONE', 1);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @LOCATION_MODULE_ID, 'faxPhone', 'Fax Phone', 'FAX_PHONE', 1);

INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME) VALUES (${orgId}, 'Skill', 'Skill');
SET @SKILL_MODULE_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @SKILL_MODULE_ID, 'skillId', 'Skill ID', 'SKILL_ID', 0);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @SKILL_MODULE_ID, 'name', 'Name', 'NAME', 1);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @SKILL_MODULE_ID, 'isActive', 'Active', 'IS_ACTIVE', 4);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, COLUMN_NAME, DATA_TYPE) VALUES (${orgId}, @SKILL_MODULE_ID, 'description', 'Description', 'DESCRIPTION', 1);