CREATE TABLE IF NOT EXISTS LeedConfiguration (
	ID BIGINT PRIMARY KEY,
	ORGID BIGINT NOT NULL,
	MODULEID BIGINT NOT NULL,
	LEEDID BIGINT,
	BUILDINGSTATUS VARCHAR(50),
	LEEDSCORE BIGINT,
	ENERGYSCORE BIGINT,
	WATERSCORE BIGINT,
	WASTESCORE BIGINT,
	HUMANEXPERIENCESCORE BIGINT,
	TRANSPORTSCORE BIGINT,	
	CONSTRAINT LEEDCONFIGURATION_BUILDING_FK FOREIGN KEY(ID) REFERENCES Building(ID) ON DELETE CASCADE,
	CONSTRAINT LEEDCONFIGURATION_FK_ORGID FOREIGN KEY (ORGID) REFERENCES Organizations(ORGID),
	CONSTRAINT LEEDCONFIGURATION_FK_MODULEID FOREIGN KEY (MODULEID) REFERENCES Modules(MODULEID)
);

CREATE TABLE IF NOT EXISTS FuelType (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	FUELID BIGINT,
	FUELTYPE VARCHAR(50),
	SUBTYPE VARCHAR(50),
	KIND VARCHAR(50),
	RESOURCE VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS LeedEnergyMeter (
	ID BIGINT PRIMARY KEY,
	FUEL_ID BIGINT,
  	METERID BIGINT,
  	SERVICEPROVIDER VARCHAR(50),
  	UNIT VARCHAR(50),
  	CONTACTPERSON VARCHAR(50),
  	CONTACTEMAIL VARCHAR(50),
  	CONSTRAINT LEEDENERGYMETER_ENERGYMETER_FK FOREIGN KEY (ID) REFERENCES Energy_Meter(ID),
  	CONSTRAINT LEEDENERGYMETER_FUELTYPE_FK FOREIGN KEY (FUEL_ID) REFERENCES FuelType(ID)
);


CREATE TABLE IF NOT EXISTS ConsumptionInfo (
	ID BIGINT PRIMARY KEY,
	CONSUMPTIONID BIGINT,
	STARTDATE BIGINT,
	CONSTRAINT CONSUMPTIONINFO_ENERGYDATA_FK FOREIGN KEY (ID) REFERENCES Energy_Data(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ArcCredential (
	ORGID BIGINT PRIMARY KEY,
	USERNAME VARCHAR(50),
	PASSWORD VARCHAR(50),
	SUBSCRIPTIONKEY VARCHAR(100),
	AUTHKEY VARCHAR(100),
	AUTHUPDATETIME BIGINT,
	ARCPROTOCOL VARCHAR(50),
	ARCHOST  VARCHAR(100),
	ARCPORT VARCHAR(50),
	CONSTRAINT ARCCREDENTIAL_ORG_FK FOREIGN KEY (ORGID) REFERENCES Organizations(ORGID)
);

