CREATE TABLE IF NOT EXISTS LeedConfiguration (
	BUILDINGID BIGINT PRIMARY KEY,
	LEEDID BIGINT,
	BUILDINGSTATUS VARCHAR(50),
	LEEDSCORE BIGINT,
	ENERGYSCORE BIGINT,
	WATERSCORE BIGINT,
	WASTESCORE BIGINT,
	HUMANEXPERIENCESCORE BIGINT,
	TRANSPORTSCORE BIGINT,	
	CONSTRAINT LEEDCONFIGURATION_BUILDING_FK FOREIGN KEY(BUILDINGID) REFERENCES Building(ID)
);

CREATE TABLE IF NOT EXISTS LeedEnergyMeter (
	DEVICE_ID BIGINT PRIMARY KEY,
	FUELTYPE BIGINT,
  	METERID BIGINT,
  	CONSTRAINT LEEDENERGYMETER_DEVICE_FK FOREIGN KEY (DEVICE_ID) REFERENCES Device(DEVICE_ID)
);

CREATE TABLE IF NOT EXISTS ConsumptionInfo (
	ENERGYDATAID BIGINT PRIMARY KEY,
	CONSUMPTIONID BIGINT,
	STARTDATE BIGINT,
	CONSTRAINT CONSUMPTIONINFO_ENERGYDATA_FK FOREIGN KEY (ENERGYDATAID) REFERENCES Energy_Data(ENERGY_DATA_ID)
);
