version: 1.0
services:
  - serviceName: iam
    instanceName: default
    dbName: default

  - serviceName: default
    instanceName: default
    dbName: default

  - serviceName: jobs
    instanceName: default
    dbName: default

#  - serviceName: tempjobs
#    instanceName: default
#    dbName: bms_jobs

  - serviceName: instantJob
    instanceName: default
    dbName: default

  - serviceName: agent
    instanceName: default
    dbName: default

  - serviceName: auditlogs
    instanceName: default
    dbName: accesslog

  - serviceName: clickhouse
    instanceName: default
    dbName: bms
    publicAccess: false

  - serviceName: app
    handlerClass: com.facilio.accounts.util.AppDataSourceImpl