

-- dashbaord population starts

INSERT INTO Dashboard (ORGID,MODULEID,DASHBOARD_NAME,PUBLISH_STATUS,LINK_NAME,DISPLAY_ORDER) VALUES (${orgId},${workOrderModuleId},'Overview',0,'overview',1);
SET @OVERVIEW_DASHBOARD_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Dashboard (ORGID,MODULEID,DASHBOARD_NAME,PUBLISH_STATUS,LINK_NAME,DISPLAY_ORDER) VALUES (${orgId},${workOrderModuleId},'My Workload',0,'myworkload',2);
SET @TECHNICIAN_DASHBOARD_ID := (SELECT LAST_INSERT_ID());

-- static or list widget population starts
INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${workOrderModuleId},'Workorder Summary',0,100,'Workorder Summary',@OVERVIEW_DASHBOARD_ID,'{"layoutWidth":24,"layoutHeight":32,"xPosition":72,"yPosition":0,"layoutPosition":3}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Static (ORGID,ID,STATIC_KEY) VALUES (${orgId},@WIDGET_ID,'workordersummary');

INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${workOrderModuleId},'Recent Workorders',2,100,'Recent Workorders',@OVERVIEW_DASHBOARD_ID,'{"layoutWidth":64,"layoutHeight":32,"xPosition":0,"yPosition":32,"layoutPosition":4}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_List_View (ORGID,ID,MODULE_NAME,VIEW_NAME) VALUES (${orgId},@WIDGET_ID,'workorder','open');

INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${workOrderModuleId},'My Workorder Summary',0,100,'My Workorder Summary',@TECHNICIAN_DASHBOARD_ID,'{"layoutWidth":24,"layoutHeight":32,"xPosition":0,"yPosition":0,"layoutPosition":3}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Static (ORGID,ID,STATIC_KEY) VALUES (${orgId},@WIDGET_ID,'mywosummary');

INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${workOrderModuleId},'My Open Workorders',0,100,'My Open Workorders',@TECHNICIAN_DASHBOARD_ID,'{"layoutWidth":64,"layoutHeight":32,"xPosition":0,"yPosition":32,"layoutPosition":4}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_List_View (ORGID,ID,MODULE_NAME,VIEW_NAME) VALUES (${orgId},@WIDGET_ID,'workorder','myopen');

-- static or list widget population ends

-- dashboard population ends

INSERT INTO Report_Field (ORGID,FIELD_LABEL,MODULE_FIELD_ID) VALUES (${orgId},'wo_status',${workorder_status});
SET @WO_STATUS_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (ORGID,FIELD_LABEL,MODULE_FIELD_ID) VALUES (${orgId},'wo_category',${workorder_category});
SET @WO_CATEGORY_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (ORGID,FIELD_LABEL,MODULE_FIELD_ID) VALUES (${orgId},'wo_assignedTo',${workorder_assignedTo});
SET @WO_ASSIGNED_TO_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (ORGID,FIELD_LABEL,MODULE_FIELD_ID) VALUES (${orgId},'wo_createdTime',${workorder_createdTime});
SET @WO_CREATED_TIME_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (ORGID,FIELD_LABEL,MODULE_FIELD_ID) VALUES (${orgId},'wo_priority',${workorder_priority});
SET @WO_PRIORITY_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (ORGID,FIELD_LABEL,MODULE_FIELD_ID) VALUES (${orgId},'wo_requester',${workorder_requester});
SET @WO_REQUESTER_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (ORGID,FIELD_LABEL,MODULE_FIELD_ID) VALUES (${orgId},'wo_actualWorkEnd',${workorder_actualWorkEnd});
SET @WO_ACTUAL_WORK_END_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (ORGID,FIELD_LABEL,MODULE_FIELD_ID) VALUES (${orgId},'wo_noOfNotes',${workorder_noOfNotes});
SET @WO_NO_OF_NOTES_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (ORGID,FIELD_LABEL,MODULE_FIELD_ID) VALUES (${orgId},'wo_type',${workorder_type});
SET @WO_TYPE_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (ORGID,FIELD_LABEL,MODULE_FIELD_ID) VALUES (${orgId},'wo_assignmentGroup',${workorder_assignmentGroup});
SET @WO_GROUP_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (ORGID,FIELD_LABEL,MODULE_FIELD_ID) VALUES (${orgId},'wo_dueDate',${workorder_dueDate});
SET @WO_DUE_DATE_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (ORGID,FIELD_LABEL,MODULE_FIELD_ID) VALUES (${orgId},'wo_resource',${workorder_resource});
SET @WO_RESOURCE_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (ORGID,FIELD_LABEL,MODULE_FIELD_ID) VALUES (${orgId},'wo_sourceType',${workorder_sourceType});
SET @WO_SOURCE_TYPE_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Formula_Field (ORGID,MODULEID,NAME,DATA_TYPE,FORMULA) VALUES (${orgId},${workOrderModuleId},'Resolution Time by mins',2,'(ACTUAL_WORK_END-ACTUAL_WORK_START)/1000/60');
INSERT INTO Report_Field (ORGID,FIELD_LABEL,FORMULA_FIELD_ID) VALUES (${orgId},'Resolution Time by mins',(SELECT LAST_INSERT_ID()));
SET @WO_AVG_COMPLETION_TIME_FF_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Formula_Field (ORGID,MODULEID,NAME,DATA_TYPE,FORMULA) VALUES (${orgId},${workOrderModuleId},'Resolution Time by hour',2,'(ACTUAL_WORK_END-ACTUAL_WORK_START)/1000/60/60');
INSERT INTO Report_Field (ORGID,FIELD_LABEL,FORMULA_FIELD_ID) VALUES (${orgId},'Resolution Time by hour',(SELECT LAST_INSERT_ID()));
SET @WO_AVG_COMPLETION_TIME_BY_HOUR_FF_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Formula_Field (ORGID,MODULEID,NAME,DATA_TYPE,FORMULA) VALUES (${orgId},${workOrderModuleId},'workorder overdue status',1,'IF((DUE_DATE-ACTUAL_WORK_END) >= 0,''Ontime'',''Overdue'')');
INSERT INTO Report_Field (ORGID,FIELD_LABEL,FORMULA_FIELD_ID) VALUES (${orgId},'workorder overdue status',(SELECT LAST_INSERT_ID()));
SET @WO_OVER_DUE_STATUS_FF_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Formula_Field (ORGID,MODULEID,NAME,DATA_TYPE,FORMULA) VALUES (${orgId},${workOrderModuleId},'workorder type',1,'IF((Tickets.SOURCE_TYPE) = 5,''Planned'',''Unplanned'')');
INSERT INTO Report_Field (ORGID,FIELD_LABEL,FORMULA_FIELD_ID) VALUES (${orgId},'workorder type',(SELECT LAST_INSERT_ID()));
SET @WO_TYPE_FF_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Formula_Field (ORGID,MODULEID,NAME,DATA_TYPE,FORMULA) VALUES (${orgId},${workOrderModuleId},'workorder assigened status',1,'if(ASSIGNED_TO_ID is null,''Unassigned'',''Assigned'')');
INSERT INTO Report_Field (ORGID,FIELD_LABEL,FORMULA_FIELD_ID) VALUES (${orgId},'workorder assigened status',(SELECT LAST_INSERT_ID()));
SET @WO_ASIGNED_STATUS_FF_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Formula_Field (ORGID,MODULEID,NAME,DATA_TYPE,FORMULA) VALUES (${orgId},${workOrderModuleId},'open workorder status',1,'IF((DUE_DATE-(UNIX_TIMESTAMP()*1000)) >= 0,''Intime'',''Overdue'')');
INSERT INTO Report_Field (ORGID,FIELD_LABEL,FORMULA_FIELD_ID) VALUES (${orgId},'open workorder status',(SELECT LAST_INSERT_ID()));
SET @WO_OPEN_STATUS_FF_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

-- portfolio report starts

INSERT INTO Report_Folder (ORGID, MODULEID,NAME) VALUES (${orgId}, ${workOrderModuleId},'Portfolio');
SET @REPORT_FOLDER_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AXIS_LABEL,Y1_AXIS_LABEL,GROUP_BY,GROUP_BY_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Open Workorders by Team','Open Workorders by Team',4,@WO_GROUP_REPORT_FIELD_ID,'Team','No of Workorders',@WO_STATUS_REPORT_FIELD_ID,'Status');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 1)');

INSERT INTO Report_Criteria (ORGID,REPORT_ID,CRITERIA_ID) VALUES (${orgId},@REPORT_ID,@CRITERIA_ID);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AXIS_LABEL,Y1_AXIS,Y1_AGGREGATE_FUNCTION,Y1_AXIS_LABEL,Y1_AXIS_UNIT) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Avg Resolution Time by Team','Avg Resolution Time by Team',9,@WO_GROUP_REPORT_FIELD_ID,'Team',@WO_AVG_COMPLETION_TIME_BY_HOUR_FF_REPORT_FIELD_ID,2,'Avg Resolution Time','minute');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1 and 2 and 3 and 4)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 2)');
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,2,'workorder.actualworkstart','Tickets.ACTUAL_WORK_START',2,'Tickets.ACTUAL_WORK_START IS NOT NULL');
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,3,'workorder.actualworkend','Tickets.ACTUAL_WORK_END',2,'Tickets.ACTUAL_WORK_END IS NOT NULL');
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,4,'workorder.asignedGroup','Tickets.ASSIGNMENT_GROUP_ID',2,'Tickets.ASSIGNMENT_GROUP_ID IS NOT NULL');

INSERT INTO Report_Criteria (ORGID,REPORT_ID,CRITERIA_ID) VALUES (${orgId},@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${workorder_createdTime},49,'30');

INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AXIS_LABEL,Y1_AXIS_LABEL,GROUP_BY,GROUP_BY_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Closed Workorders by Team','Closed Workorders by Team',4,@WO_GROUP_REPORT_FIELD_ID,'Team','No of Workorders',@WO_PRIORITY_REPORT_FIELD_ID,'Category');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 2)');

INSERT INTO Report_Criteria (ORGID,REPORT_ID,CRITERIA_ID) VALUES (${orgId},@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${workorder_actualWorkEnd},49,'30');


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AXIS_LABEL,Y1_AXIS_LABEL,GROUP_BY,GROUP_BY_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Workorder Volume by Team','Workorder Volume by Team',4,@WO_GROUP_REPORT_FIELD_ID,'Team','No of Workorders',@WO_PRIORITY_REPORT_FIELD_ID,'Category');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${workorder_createdTime},49,'30');

-- portfolio report ends

-- open workorders report starts

INSERT INTO Report_Folder (ORGID, MODULEID,NAME) VALUES (${orgId}, ${workOrderModuleId},'Open Workorders');
SET @REPORT_FOLDER_ID := (SELECT LAST_INSERT_ID());


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Open Workorders by Category','Open Workorders by Category',1,@WO_CATEGORY_REPORT_FIELD_ID);
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 1)');

INSERT INTO Report_Criteria (ORGID,REPORT_ID,CRITERIA_ID) VALUES (${orgId},@REPORT_ID,@CRITERIA_ID);


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${workOrderModuleId},'Open Workorder by Category',1,100,'Open Workorder by Category',@OVERVIEW_DASHBOARD_ID,'{"layoutWidth":32,"layoutHeight":32,"xPosition":0,"yPosition":64,"layoutPosition":6}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ORGID,ID,REPORT_ID) VALUES (${orgId},@WIDGET_ID,@REPORT_ID);

INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Open Workorders by Priority','Open Workorders by Priority',2,@WO_PRIORITY_REPORT_FIELD_ID);
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 1)');

INSERT INTO Report_Criteria (ORGID,REPORT_ID,CRITERIA_ID) VALUES (${orgId},@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${workorder_createdTime},49,'30');


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Open Workorders by Type','Open Workorders by Type',2,@WO_TYPE_REPORT_FIELD_ID);
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 1)');

INSERT INTO Report_Criteria (ORGID,REPORT_ID,CRITERIA_ID) VALUES (${orgId},@REPORT_ID,@CRITERIA_ID);


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${workOrderModuleId},'Open Workorder by Type',1,100,'Open Workorder by Type',@OVERVIEW_DASHBOARD_ID,'{"layoutWidth":32,"layoutHeight":32,"xPosition":32,"yPosition":64,"layoutPosition":7}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ORGID,ID,REPORT_ID) VALUES (${orgId},@WIDGET_ID,@REPORT_ID);

INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Open Workorders by Techinician','Open Workorders by Techinician',3,@WO_ASSIGNED_TO_REPORT_FIELD_ID);
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 1)');

INSERT INTO Report_Criteria (ORGID,REPORT_ID,CRITERIA_ID) VALUES (${orgId},@REPORT_ID,@CRITERIA_ID);


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${workOrderModuleId},'Open Workorders by Techinician',1,100,'Open Workorders by Techinician',@OVERVIEW_DASHBOARD_ID,'{"layoutWidth":32,"layoutHeight":32,"xPosition":64,"yPosition":64,"layoutPosition":8}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ORGID,ID,REPORT_ID) VALUES (${orgId},@WIDGET_ID,@REPORT_ID);

INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Open Workorders by Team','Open Workorders by Team',2,@WO_GROUP_REPORT_FIELD_ID);
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 1)');

INSERT INTO Report_Criteria (ORGID,REPORT_ID,CRITERIA_ID) VALUES (${orgId},@REPORT_ID,@CRITERIA_ID);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Open Workorders by Due Date','Open Workorders by Due Date',3,@WO_DUE_DATE_REPORT_FIELD_ID,12);
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 1)');

INSERT INTO Report_Criteria (ORGID,REPORT_ID,CRITERIA_ID) VALUES (${orgId},@REPORT_ID,@CRITERIA_ID);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Open Workorders by Created Date','Open Workorders by Created Date',3,@WO_CREATED_TIME_REPORT_FIELD_ID,12);
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 1)');

INSERT INTO Report_Criteria (ORGID,REPORT_ID,CRITERIA_ID) VALUES (${orgId},@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${workorder_createdTime},49,'30');


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Open Workorders by Status','Open Workorders by Status',3,@WO_STATUS_REPORT_FIELD_ID);
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 1)');

INSERT INTO Report_Criteria (ORGID,REPORT_ID,CRITERIA_ID) VALUES (${orgId},@REPORT_ID,@CRITERIA_ID);


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${workOrderModuleId},'Open Workorders',1,100,'Open Workorders',@OVERVIEW_DASHBOARD_ID,'{"layoutWidth":32,"layoutHeight":32,"xPosition":0,"yPosition":0,"layoutPosition":1}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ORGID,ID,REPORT_ID) VALUES (${orgId},@WIDGET_ID,@REPORT_ID);

-- open workorders report ends

INSERT INTO Report_Folder (ORGID, MODULEID,NAME) VALUES (${orgId}, ${workOrderModuleId},'Closed Workorders');
SET @REPORT_FOLDER_ID := (SELECT LAST_INSERT_ID());


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Closed Workorders by Type','Closed Workorders by Type',1,@WO_TYPE_REPORT_FIELD_ID,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 2)');

INSERT INTO Report_Criteria (ORGID,REPORT_ID,CRITERIA_ID) VALUES (${orgId},@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${workorder_actualWorkEnd},49,'30');


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());


INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Closed Workorders by Team','Closed Workorders by Team',3,@WO_GROUP_REPORT_FIELD_ID,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 2)');

INSERT INTO Report_Criteria (ORGID,REPORT_ID,CRITERIA_ID) VALUES (${orgId},@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${workorder_actualWorkEnd},49,'30');


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Closed Workorders by Category','Closed Workorders by Category',6,@WO_CATEGORY_REPORT_FIELD_ID,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 2)');

INSERT INTO Report_Criteria (ORGID,REPORT_ID,CRITERIA_ID) VALUES (${orgId},@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${workorder_actualWorkEnd},49,'30');


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Closed Workorders by Priority','Closed Workorders by Priority',3,@WO_PRIORITY_REPORT_FIELD_ID,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 2)');

INSERT INTO Report_Criteria (ORGID,REPORT_ID,CRITERIA_ID) VALUES (${orgId},@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${workorder_actualWorkEnd},49,'30');


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Closed Workorders by Due Date','Closed Workorders by Due Date',12,@WO_DUE_DATE_REPORT_FIELD_ID,12,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 2)');

INSERT INTO Report_Criteria (ORGID,REPORT_ID,CRITERIA_ID) VALUES (${orgId},@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${workorder_actualWorkEnd},49,'30');


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Closed Workorders by Created Date','Closed Workorders by Created Date',12,@WO_CREATED_TIME_REPORT_FIELD_ID,12,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 2)');

INSERT INTO Report_Criteria (ORGID,REPORT_ID,CRITERIA_ID) VALUES (${orgId},@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${workorder_actualWorkEnd},49,'30');


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Closed Workorders by Techinician','Closed Workorders by Techinician',1,@WO_ASSIGNED_TO_REPORT_FIELD_ID,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 2)');

INSERT INTO Report_Criteria (ORGID,REPORT_ID,CRITERIA_ID) VALUES (${orgId},@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${workorder_actualWorkEnd},49,'30');


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION,X_AXIS_LABEL,Y1_AXIS_LABEL,GROUP_BY,GROUP_BY_LABEL) VALUES
(${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Closed Workorders Trend','Closed Workorders Trend',3,@WO_ACTUAL_WORK_END_REPORT_FIELD_ID,12,'Date','No of Workorders',@WO_OVER_DUE_STATUS_FF_REPORT_FIELD_ID,'Actual Work End');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 2)');

INSERT INTO Report_Criteria (ORGID,REPORT_ID,CRITERIA_ID) VALUES (${orgId},@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${workorder_actualWorkEnd},49,'30');


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${workOrderModuleId},'Closed Workorders Trend',1,100,'Closed Workorders Trend',@OVERVIEW_DASHBOARD_ID,'{"layoutWidth":40,"layoutHeight":32,"xPosition":32,"yPosition":0,"layoutPosition":2}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ORGID,ID,REPORT_ID) VALUES (${orgId},@WIDGET_ID,@REPORT_ID);

-- closed workorders report ends

-- All workorders report starts

INSERT INTO Report_Folder (ORGID, MODULEID,NAME) VALUES (${orgId}, ${workOrderModuleId},'All Workorders');
SET @REPORT_FOLDER_ID := (SELECT LAST_INSERT_ID());


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'All Workorders by Category','All Workorders by Category',1,@WO_CATEGORY_REPORT_FIELD_ID,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${workorder_createdTime},49,'30');


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'All Workorders by Priority','All Workorders by Priority',1,@WO_PRIORITY_REPORT_FIELD_ID,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${workorder_createdTime},49,'30');


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'All Workorders by Type','All Workorders by Type',1,@WO_TYPE_REPORT_FIELD_ID,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${workorder_createdTime},49,'30');


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'All Workorders by Techinician','All Workorders by Techinician',1,@WO_ASSIGNED_TO_REPORT_FIELD_ID,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${workorder_createdTime},49,'30');


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'All Workorders by Team','All Workorders by Team',1,@WO_GROUP_REPORT_FIELD_ID,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${workorder_createdTime},49,'30');


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'All Workorders by Due Date','All Workorders by Due Date',1,@WO_DUE_DATE_REPORT_FIELD_ID,12,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${workorder_createdTime},49,'30');


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'All Workorders by Created Date','All Workorders by Created Date',1,@WO_CREATED_TIME_REPORT_FIELD_ID,12,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${workorder_createdTime},49,'30');


-- All workorders report ends

-- Top N reports starts

INSERT INTO Report_Folder (ORGID, MODULEID,NAME) VALUES (${orgId}, ${workOrderModuleId},'Top N Reports');
SET @REPORT_FOLDER_ID := (SELECT LAST_INSERT_ID());


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Top N Technicians','Top N Technicians',1,@WO_ASSIGNED_TO_REPORT_FIELD_ID,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${workorder_createdTime},49,'30');


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,Y1_AXIS_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Top N Categories','Top N Categories',1,@WO_CATEGORY_REPORT_FIELD_ID,'No of Workorders');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${workorder_createdTime},49,'30');

-- Top N reports ends

-- Efficiency reports starts

INSERT INTO Report_Folder (ORGID, MODULEID,NAME) VALUES (${orgId}, ${workOrderModuleId},'Efficiency');
SET @REPORT_FOLDER_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AXIS_LABEL,Y1_AXIS,Y1_AGGREGATE_FUNCTION,Y1_AXIS_LABEL,Y1_AXIS_UNIT) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Avg Resolution Time by Technician','Avg Resolution Time by Technician',9,@WO_ASSIGNED_TO_REPORT_FIELD_ID,'Technician',@WO_AVG_COMPLETION_TIME_BY_HOUR_FF_REPORT_FIELD_ID,2,'Avg Resolution Time','Hrs');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${workorder_createdTime},49,'30');

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1 and 2 and 3 and 4)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,1,'workorder.status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 2)');
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,2,'workorder.actualworkstart','Tickets.ACTUAL_WORK_START',2,'Tickets.ACTUAL_WORK_START IS NOT NULL');
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,3,'workorder.actualworkend','Tickets.ACTUAL_WORK_END',2,'Tickets.ACTUAL_WORK_END IS NOT NULL');
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,4,'workorder.asignedto','Tickets.ASSIGNED_TO_ID',2,'Tickets.ASSIGNED_TO_ID IS NOT NULL');

INSERT INTO Report_Criteria (ORGID,REPORT_ID,CRITERIA_ID) VALUES (${orgId},@REPORT_ID,@CRITERIA_ID);


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${workOrderModuleId},'Avg Resolution Time by Technician',1,100,'Avg Resolution Time by Technician',@OVERVIEW_DASHBOARD_ID,'{"layoutWidth":32,"layoutHeight":32,"xPosition":64,"yPosition":32,"layoutPosition":5}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ORGID,ID,REPORT_ID) VALUES (${orgId},@WIDGET_ID,@REPORT_ID);

-- Efficiency reports ends

-- Inflow trends starts

INSERT INTO Report_Folder (ORGID, MODULEID,NAME) VALUES (${orgId}, ${workOrderModuleId},'Inflow Trend');
SET @REPORT_FOLDER_ID := (SELECT LAST_INSERT_ID());


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Work Orders Inflow Trend - By date','Work Orders Inflow Trend - By date',3,@WO_CREATED_TIME_REPORT_FIELD_ID,12);
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${workorder_createdTime},49,'30');


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${workOrderModuleId},'Workorder Inflow Trend',1,100,'Workorder Inflow Trend',@OVERVIEW_DASHBOARD_ID,'{"layoutWidth":96,"layoutHeight":32,"xPosition":0,"yPosition":96,"layoutPosition":9}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ORGID,ID,REPORT_ID) VALUES (${orgId},@WIDGET_ID,@REPORT_ID);

INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Work Orders Inflow Trend - By Month','Work Orders Inflow Trend - By Month',3,@WO_CREATED_TIME_REPORT_FIELD_ID,10);
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR) VALUES (${orgId},@REPORT_ID,${workorder_createdTime},44);

-- Inflow trends end

-- My Reports starts

INSERT INTO Report_Folder (ORGID, MODULEID,NAME) VALUES (${orgId}, ${workOrderModuleId},'My Reports');
SET @REPORT_FOLDER_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Open Workorders by Category','Open Workorders by Category',1,@WO_CATEGORY_REPORT_FIELD_ID);
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1 and 2)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 1)');
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,VAL,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,2,'assignedTo','Tickets.ASSIGNED_TO_ID',36,'${LOGGED_USER}','Tickets.ASSIGNED_TO_ID = ?');

INSERT INTO Report_Criteria (ORGID,REPORT_ID,CRITERIA_ID) VALUES (${orgId},@REPORT_ID,@CRITERIA_ID);


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${workOrderModuleId},'My Open Workorders by Category',1,100,'My Open Workorders by Category',@TECHNICIAN_DASHBOARD_ID,'{"layoutWidth":32,"layoutHeight":32,"xPosition":64,"yPosition":32,"layoutPosition":2}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ORGID,ID,REPORT_ID) VALUES (${orgId},@WIDGET_ID,@REPORT_ID);

INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Open Workorders by Priority','Open Workorders by Priority',2,@WO_PRIORITY_REPORT_FIELD_ID);
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1 and 2)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 1)');
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,VAL,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,2,'assignedTo','Tickets.ASSIGNED_TO_ID',36,'${LOGGED_USER}','Tickets.ASSIGNED_TO_ID = ?');

INSERT INTO Report_Criteria (ORGID,REPORT_ID,CRITERIA_ID) VALUES (${orgId},@REPORT_ID,@CRITERIA_ID);


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${workOrderModuleId},'Open Workorders by Priority',1,100,'Open Workorders by Priority',@TECHNICIAN_DASHBOARD_ID,'{"layoutWidth":32,"layoutHeight":32,"xPosition":24,"yPosition":0,"layoutPosition":5}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ORGID,ID,REPORT_ID) VALUES (${orgId},@WIDGET_ID,@REPORT_ID);

INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION,X_AXIS_LABEL,GROUP_BY,GROUP_BY_LABEL) VALUES (${orgId},${workOrderModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Closed Workorders Trend','Closed Workorders Trend',3,@WO_ACTUAL_WORK_END_REPORT_FIELD_ID,12,'Actual Work End',@WO_OVER_DUE_STATUS_FF_REPORT_FIELD_ID,'Actual Work End');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1 and 2)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,1,'status','Tickets.STATUS_ID',35,'Tickets.STATUS_ID IN (SELECT ID FROM TicketStatus WHERE TicketStatus.STATUS_TYPE = 1)');
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,VAL,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,2,'assignedTo','Tickets.ASSIGNED_TO_ID',36,'${LOGGED_USER}','Tickets.ASSIGNED_TO_ID = ?');

INSERT INTO Report_Criteria (ORGID,REPORT_ID,CRITERIA_ID) VALUES (${orgId},@REPORT_ID,@CRITERIA_ID);

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${workorder_actualWorkEnd},49,'30');

INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${workOrderModuleId},'My Closed Workorders Trend',1,100,'My Closed Workorders Trend',@TECHNICIAN_DASHBOARD_ID,'{"layoutWidth":40,"layoutHeight":32,"xPosition":56,"yPosition":0,"layoutPosition":4}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ORGID,ID,REPORT_ID) VALUES (${orgId},@WIDGET_ID,@REPORT_ID);

-- My Reports ends




-- alarm Module Population Starts


INSERT INTO Dashboard (ORGID,MODULEID,DASHBOARD_NAME,PUBLISH_STATUS,LINK_NAME,DISPLAY_ORDER) VALUES (${orgId},${alarmModuleId},'Portfolio',0,'portfolio',1);
SET @PORTFOLIO_DASHBOARD_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Dashboard (ORGID,MODULEID,DASHBOARD_NAME,PUBLISH_STATUS,LINK_NAME,DISPLAY_ORDER) VALUES (${orgId},${alarmModuleId},'Building Dashboard',0,'buildingdashboard',2);
SET @ALARM_BUILDING_DASHBOARD_ID := (SELECT LAST_INSERT_ID());

-- static widget starts

INSERT INTO Widget (ORGID,MODULEID,TYPE,DATA_REFRESH_INTERTVEL,DASHBOARD_ID,META_JSON) VALUES (${orgId},${alarmModuleId},0,100,@PORTFOLIO_DASHBOARD_ID,'{"layoutWidth":72,"layoutHeight":32,"xPosition":0,"yPosition":0,"layoutPosition":1}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Static (ORGID,ID,STATIC_KEY) VALUES (${orgId},@WIDGET_ID,'mapwidget');

INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${alarmModuleId},'Open Alarms',0,100,'Open Alarms',@PORTFOLIO_DASHBOARD_ID,'{"layoutWidth":24,"layoutHeight":32,"xPosition":72,"yPosition":0,"layoutPosition":4}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Static (ORGID,ID,STATIC_KEY) VALUES (${orgId},@WIDGET_ID,'openalarms');

INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${alarmModuleId},'Recent Alarms',2,100,'Recent Alarms',@PORTFOLIO_DASHBOARD_ID,'{"layoutWidth":64,"layoutHeight":32,"xPosition":0,"yPosition":32,"layoutPosition":6}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_List_View (ORGID,ID,MODULE_NAME,VIEW_NAME) VALUES (${orgId},@WIDGET_ID,'alarm','active');


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${alarmModuleId},'Open Alarms',0,100,'Open Alarms',@ALARM_BUILDING_DASHBOARD_ID,'{"layoutWidth":24,"layoutHeight":32,"xPosition":32,"yPosition":0,"layoutPosition":4}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Static (ORGID,ID,STATIC_KEY) VALUES (${orgId},@WIDGET_ID,'buildingopenalarms');

INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${alarmModuleId},'Recent Alarms',2,100,'Recent Alarms',@ALARM_BUILDING_DASHBOARD_ID,'{"layoutWidth":56,"layoutHeight":32,"xPosition":40,"yPosition":32,"layoutPosition":5}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_List_View (ORGID,ID,MODULE_NAME,VIEW_NAME) VALUES (${orgId},@WIDGET_ID,'alarm','active');

-- static widget ends

-- alarm field population starts

INSERT INTO Report_Field (ORGID,FIELD_LABEL,MODULE_FIELD_ID) VALUES (${orgId},'fa_severity',${alarm_severity});
SET @FA_SEVERITY_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (ORGID,FIELD_LABEL,MODULE_FIELD_ID) VALUES (${orgId},'fa_createdTime',${alarm_createdTime});
SET @FA_CREATED_TIME_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (ORGID,FIELD_LABEL,MODULE_FIELD_ID) VALUES (${orgId},'fa_acknowledgedBy',${alarm_acknowledgedBy});
SET @FA_ACKNOWLEDGED_BY_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (ORGID,FIELD_LABEL,MODULE_FIELD_ID) VALUES (${orgId},'fa_clearedBy',${alarm_clearedBy});
SET @FA_CLEARED_BY_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (ORGID,FIELD_LABEL,MODULE_FIELD_ID) VALUES (${orgId},'fa_resource',${alarm_resource});
SET @FA_RESOURCE_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (ORGID,FIELD_LABEL,MODULE_FIELD_ID) VALUES (${orgId},'fa_category',${alarm_category});
SET @FA_CATEGORY_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Formula_Field (ORGID,MODULEID,NAME,DATA_TYPE,FORMULA) VALUES (${orgId},${alarmModuleId},'Response time by Min',2,'(ACKNOWLEDGED_TIME - CREATED_TIME)/1000/60');
INSERT INTO Report_Field (ORGID,FIELD_LABEL,FORMULA_FIELD_ID) VALUES (${orgId},'Response time by Min',(SELECT LAST_INSERT_ID()));
SET @FA_AVG_RESPONSE_TIME_FF_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Formula_Field (ORGID,MODULEID,NAME,DATA_TYPE,FORMULA) VALUES (${orgId},${alarmModuleId},'Resolution time by Min',2,'(CLEARED_TIME - CREATED_TIME)/1000/60');
INSERT INTO Report_Field (ORGID,FIELD_LABEL,FORMULA_FIELD_ID) VALUES (${orgId},'Resolution time by Min',(SELECT LAST_INSERT_ID()));
SET @FA_AVG_RESOLUTION_TIME_FF_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

-- alarm field population ends

-- portfolio report starts

INSERT INTO Report_Folder (ORGID, MODULEID,NAME) VALUES (${orgId}, ${alarmModuleId},'Portfolio');
SET @REPORT_FOLDER_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AXIS_LABEL,Y1_AXIS_LABEL) VALUES (${orgId},${alarmModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Alarm Summary','Alarms Summary by Severity',4,@FA_SEVERITY_REPORT_FIELD_ID,'Severity','No of Alarms');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${alarm_createdTime},49,'30');


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION,X_AXIS_LABEL,Y1_AXIS_LABEL) VALUES (${orgId},${alarmModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Alarms By Buildings','Alarms By Buildings',2,@FA_RESOURCE_REPORT_FIELD_ID,22,'Buildings','No of Alarms');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR) VALUES (${orgId},@REPORT_ID,${alarm_createdTime},44);

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,1,'severity','Alarms.SEVERITY',10,'Alarms.SEVERITY NOT IN (SELECT ID FROM Alarm_Severity WHERE Alarm_Severity.SEVERITY = "Clear" and Alarm_Severity.ORGID = ${orgId})');

INSERT INTO Report_Criteria (ORGID,REPORT_ID,CRITERIA_ID) VALUES (${orgId},@REPORT_ID,@CRITERIA_ID);

INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${alarmModuleId},'Alarm Summary',1,100,'Alarm Summary',@PORTFOLIO_DASHBOARD_ID,'{"layoutWidth":32,"layoutHeight":32,"xPosition":64,"yPosition":32,"layoutPosition":4}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ORGID,ID,REPORT_ID) VALUES (${orgId},@WIDGET_ID,@REPORT_ID);

INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION,X_AXIS_LABEL,Y1_AXIS_LABEL,GROUP_BY,GROUP_BY_LABEL) VALUES (${orgId},${alarmModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Alarms by Building with Severity','Alarms by Building with Severity',4,@FA_RESOURCE_REPORT_FIELD_ID,22,'Buildings','No of Alarms',@FA_SEVERITY_REPORT_FIELD_ID,'Severity');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR) VALUES (${orgId},@REPORT_ID,${alarm_createdTime},44);

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,1,'severity','Alarms.SEVERITY',10,'Alarms.SEVERITY NOT IN (SELECT ID FROM Alarm_Severity WHERE Alarm_Severity.SEVERITY = "Clear" and Alarm_Severity.ORGID = ${orgId})');

INSERT INTO Report_Criteria (ORGID,REPORT_ID,CRITERIA_ID) VALUES (${orgId},@REPORT_ID,@CRITERIA_ID);


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${alarmModuleId},'Building Alarm Stats',1,100,'Building Alarm Stats',@PORTFOLIO_DASHBOARD_ID,'{"layoutWidth":40,"layoutHeight":40,"xPosition":0,"yPosition":64,"layoutPosition":2}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ORGID,ID,REPORT_ID) VALUES (${orgId},@WIDGET_ID,@REPORT_ID);

INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION,X_AXIS_LABEL,Y1_AXIS,Y1_AGGREGATE_FUNCTION,Y1_AXIS_LABEL,Y1_AXIS_UNIT,GROUP_BY,GROUP_BY_LABEL) VALUES  (${orgId},${alarmModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Avg Response Time by Building','Avg Response Time by Building',5,@FA_RESOURCE_REPORT_FIELD_ID,22,'Buildings',@FA_AVG_RESPONSE_TIME_FF_REPORT_FIELD_ID,2,'Avg Response Time','minute',@FA_CATEGORY_REPORT_FIELD_ID,'Category');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR) VALUES (${orgId},@REPORT_ID,${alarm_createdTime},44);

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1 and 2)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,1,'createdTime','Alarms.CREATED_TIME',2,'Alarms.CREATED_TIME IS NOT NULL');
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,2,'acknowledgedTime','Alarms.ACKNOWLEDGED_TIME',2,'Alarms.ACKNOWLEDGED_TIME IS NOT NULL');

INSERT INTO Report_Criteria (ORGID,REPORT_ID,CRITERIA_ID) VALUES (${orgId},@REPORT_ID,@CRITERIA_ID);


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${alarmModuleId},'Average Response Time',1,100,'Average Response Time',@PORTFOLIO_DASHBOARD_ID,'{"layoutWidth":56,"layoutHeight":40,"xPosition":40,"yPosition":64,"layoutPosition":1}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ORGID,ID,REPORT_ID) VALUES (${orgId},@WIDGET_ID,@REPORT_ID);

-- portfolio report ends


-- building report starts

INSERT INTO Report_Folder (ORGID, MODULEID,NAME) VALUES (${orgId}, ${alarmModuleId},'Building Reports');
SET @REPORT_FOLDER_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AXIS_LABEL,Y1_AXIS_LABEL) VALUES (${orgId},${alarmModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Alarm Summary','Alarms Summary by Severity',4,@FA_SEVERITY_REPORT_FIELD_ID,'Severity','No of Alarms');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_SpaceFilter(ORGID,REPORT_ID,BUILDING_ID) VALUES(${orgId},@REPORT_ID,-1);

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${alarm_createdTime},49,'30');

INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${alarmModuleId},'Alarm Summary',1,100,'Alarm Summary',@ALARM_BUILDING_DASHBOARD_ID,'{"layoutWidth":32,"layoutHeight":32,"xPosition":0,"yPosition":0,"layoutPosition":1}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ORGID,ID,REPORT_ID) VALUES (${orgId},@WIDGET_ID,@REPORT_ID);

INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AXIS_LABEL,Y1_AXIS,Y1_AGGREGATE_FUNCTION,Y1_AXIS_LABEL,Y1_AXIS_UNIT) VALUES (${orgId},${alarmModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Average Response Time By Technicians','Average Response Time By Technicians',9,@FA_ACKNOWLEDGED_BY_REPORT_FIELD_ID,'Acknowledged By',@FA_AVG_RESPONSE_TIME_FF_REPORT_FIELD_ID,2,'mins', 'minute');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_SpaceFilter(ORGID,REPORT_ID,BUILDING_ID) VALUES(${orgId},@REPORT_ID,-1);

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${alarm_createdTime},49,'30');

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1 and 2)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,1,'createdTime','Alarms.CREATED_TIME',2,'Alarms.CREATED_TIME IS NOT NULL');
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,2,'acknowledgedTime','Alarms.ACKNOWLEDGED_TIME',2,'Alarms.ACKNOWLEDGED_TIME IS NOT NULL');

INSERT INTO Report_Criteria (ORGID,REPORT_ID,CRITERIA_ID) VALUES (${orgId},@REPORT_ID,@CRITERIA_ID);


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${alarmModuleId},'Avg Response Time By Technicians',1,100,'Avg Response Time By Technicians',@ALARM_BUILDING_DASHBOARD_ID,'{"layoutWidth":40,"layoutHeight":32,"xPosition":56,"yPosition":0,"layoutPosition":3}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ORGID,ID,REPORT_ID) VALUES (${orgId},@WIDGET_ID,@REPORT_ID);

INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AXIS_LABEL,Y1_AXIS,Y1_AGGREGATE_FUNCTION,Y1_AXIS_LABEL,Y1_AXIS_UNIT) VALUES (${orgId},${alarmModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Average Resolution Time By Technicians','Average Resolution Time By Technicians',9,@FA_CLEARED_BY_REPORT_FIELD_ID,'Cleared By',@FA_AVG_RESOLUTION_TIME_FF_REPORT_FIELD_ID,2,'mins', 'minute');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_SpaceFilter(ORGID,REPORT_ID,BUILDING_ID) VALUES(${orgId},@REPORT_ID,-1);

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${alarm_createdTime},49,'30');

INSERT INTO Criteria (ORGID,PATTERN) VALUES (${orgId},'(1 and 2 and 3)');
SET @CRITERIA_ID := (SELECT LAST_INSERT_ID());
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,1,'createdTime','Alarms.CREATED_TIME',2,'Alarms.CREATED_TIME IS NOT NULL');
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,2,'clearedBy','Alarms.CLEARED_BY',2,'Alarms.CLEARED_BY IS NOT NULL');
INSERT INTO Conditions (ORGID,PARENT_CRITERIA_ID,SEQUENCE,FIELD_NAME,COLUMN_NAME,OPERATOR,COMPUTED_WHERE_CLAUSE) VALUES (${orgId},@CRITERIA_ID,3,'clearedTime','Alarms.CLEARED_TIME',2,'Alarms.CLEARED_TIME IS NOT NULL');

INSERT INTO Report_Criteria (ORGID,REPORT_ID,CRITERIA_ID) VALUES (${orgId},@REPORT_ID,@CRITERIA_ID);

INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${alarmModuleId},'Avg Resolution time By Technicians',1,100,'Avg Resolution time By Technicians',@ALARM_BUILDING_DASHBOARD_ID,'{"layoutWidth":40,"layoutHeight":32,"xPosition":0,"yPosition":32,"layoutPosition":2}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ORGID,ID,REPORT_ID) VALUES (${orgId},@WIDGET_ID,@REPORT_ID);

-- building report ends

-- alarm Module Population Ends



-- energy module population starts

INSERT INTO Dashboard (ORGID,MODULEID,DASHBOARD_NAME,PUBLISH_STATUS,LINK_NAME,DISPLAY_ORDER) VALUES (${orgId},${energyDataModuleId},'Portfolio',0,'portfolio',1);
SET @PORTFOLIO_DASHBOARD_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Dashboard (ORGID,MODULEID,DASHBOARD_NAME,PUBLISH_STATUS,LINK_NAME,DISPLAY_ORDER) VALUES (${orgId},${energyDataModuleId},'Building Dashboard',0,'buildingdashboard',2);
SET @BUILDING_DASHBOARD_ID := (SELECT LAST_INSERT_ID());




INSERT INTO Report_Field (ORGID,FIELD_LABEL,MODULE_FIELD_ID) VALUES (${orgId},'ed_totalEnergyConsumptionDelta',${energydata_totalEnergyConsumptionDelta});
SET @ED_TOTAL_CONS_DELTA_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (ORGID,FIELD_LABEL,MODULE_FIELD_ID) VALUES (${orgId},'ed_ttime',${energydata_ttime});
SET @ED_TTIME_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (ORGID,FIELD_LABEL,MODULE_FIELD_ID) VALUES (${orgId},'em_purposeSpace',${energymeter_purposeSpace});
SET @EM_PURPOSE_SPACE_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Report_Field (ORGID,FIELD_LABEL,MODULE_FIELD_ID) VALUES (${orgId},'em_purpose',${energymeter_purpose});
SET @EM_PURPOSE_REPORT_FIELD_ID = (SELECT LAST_INSERT_ID());


-- portfolio Report Starts 

INSERT INTO Report_Folder (ORGID, MODULEID,NAME) VALUES (${orgId}, ${energyDataModuleId},'Portfolio');
SET @REPORT_FOLDER_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION,X_AXIS_LABEL,Y1_AXIS,Y1_AGGREGATE_FUNCTION,Y1_AXIS_LABEL) VALUES (${orgId},${energyDataModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Consumption by Buildings','Consumption by Buildings',2,@EM_PURPOSE_SPACE_REPORT_FIELD_ID,22,'Operational Space',@ED_TOTAL_CONS_DELTA_REPORT_FIELD_ID,3,'Energy');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${energydata_ttime},49,30);


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${energyDataModuleId},'Consumption by Buildings',1,100,'Consumption by Buildings',@PORTFOLIO_DASHBOARD_ID,'{"layoutWidth":40,"layoutHeight":32,"xPosition":0,"yPosition":0,"layoutPosition":1}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ORGID,ID,REPORT_ID) VALUES (${orgId},@WIDGET_ID,@REPORT_ID);

INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION,X_AXIS_LABEL,Y1_AXIS,Y1_AGGREGATE_FUNCTION,Y1_AXIS_LABEL,Y1_AXIS_UNIT) VALUES (${orgId},${energyDataModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Cost by Buildings','Cost by Buildings',9,@EM_PURPOSE_SPACE_REPORT_FIELD_ID,22,'Operational Space',@ED_TOTAL_CONS_DELTA_REPORT_FIELD_ID,3,'Cost','cost');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${energydata_ttime},49,30);


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${energyDataModuleId},'Cost by Buildings',1,100,'Cost by Buildings',@PORTFOLIO_DASHBOARD_ID,'{"layoutWidth":56,"layoutHeight":32,"xPosition":40,"yPosition":0,"layoutPosition":2}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ORGID,ID,REPORT_ID) VALUES (${orgId},@WIDGET_ID,@REPORT_ID);

INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION,X_AXIS_LABEL,Y1_AXIS,Y1_AGGREGATE_FUNCTION,Y1_AXIS_LABEL) VALUES (${orgId},${energyDataModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Overall Energy Consumption','Overall Energy Consumption',12,@ED_TTIME_REPORT_FIELD_ID,12,'Time',@ED_TOTAL_CONS_DELTA_REPORT_FIELD_ID,3,'Energy');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${energydata_ttime},49,30);

INSERT INTO Report_SpaceFilter (ORGID,REPORT_ID,SITE_ID) VALUES (${orgId},@REPORT_ID,-1);

INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${energyDataModuleId},'Overall Energy Consumption',1,100,'Overall Energy Consumption',@PORTFOLIO_DASHBOARD_ID,'{"layoutWidth":96,"layoutHeight":40,"xPosition":0,"yPosition":32,"layoutPosition":3}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ORGID,ID,REPORT_ID) VALUES (${orgId},@WIDGET_ID,@REPORT_ID);

INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION,X_AXIS_LABEL,Y1_AXIS,Y1_AGGREGATE_FUNCTION,Y1_AXIS_LABEL,Y1_AXIS_UNIT) VALUES (${orgId},${energyDataModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Use Wise Ranking','Use Wise Ranking',2,@EM_PURPOSE_REPORT_FIELD_ID,24,'Service',@ED_TOTAL_CONS_DELTA_REPORT_FIELD_ID,3,'Energy','kwh');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${energydata_ttime},49,30);

INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${energyDataModuleId},'Use Wise Ranking',1,100,'Use Wise Ranking',@PORTFOLIO_DASHBOARD_ID,'{"layoutWidth":40,"layoutHeight":32,"xPosition":0,"yPosition":72,"layoutPosition":4}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ORGID,ID,REPORT_ID) VALUES (${orgId},@WIDGET_ID,@REPORT_ID);

INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION,X_AXIS_LABEL,Y1_AXIS,Y1_AGGREGATE_FUNCTION,Y1_AXIS_LABEL,Y1_AXIS_UNIT) VALUES (${orgId},${energyDataModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Energy Consumption Ranking','Energy Consumption Ranking',9,@EM_PURPOSE_SPACE_REPORT_FIELD_ID,22,'Operational Space',@ED_TOTAL_CONS_DELTA_REPORT_FIELD_ID,3,'Ranking','eui');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${energydata_ttime},49,30);

INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${energyDataModuleId},'Energy Consumption Ranking',1,100,'Energy Consumption Ranking',@PORTFOLIO_DASHBOARD_ID,'{"layoutWidth":56,"layoutHeight":32,"xPosition":40,"yPosition":72,"layoutPosition":5}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ORGID,ID,REPORT_ID) VALUES (${orgId},@WIDGET_ID,@REPORT_ID);

INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION,X_AXIS_LABEL,Y1_AXIS,Y1_AGGREGATE_FUNCTION,Y1_AXIS_LABEL) VALUES (${orgId},${energyDataModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Energy Comparision by Baseline','Energy Comparision by Baseline',12,@ED_TTIME_REPORT_FIELD_ID,12,'Time',@ED_TOTAL_CONS_DELTA_REPORT_FIELD_ID,3,'Energy');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${energydata_ttime},22,null);

INSERT INTO Report_SpaceFilter (ORGID,REPORT_ID,SITE_ID) VALUES (${orgId},@REPORT_ID,-1);

INSERT INTO Report_BaseLine_Rel (ORGID,BASE_LINE_ID,REPORT_ID,ADJUST_TYPE) VALUES (${orgId},${baseline_PreviousDay},@REPORT_ID,1);


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${energyDataModuleId},'Energy Comparision by Baseline',1,100,'Energy Comparision by Baseline',@PORTFOLIO_DASHBOARD_ID,'{"layoutWidth":96,"layoutHeight":40,"xPosition":0,"yPosition":104,"layoutPosition":6}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ORGID,ID,REPORT_ID) VALUES (${orgId},@WIDGET_ID,@REPORT_ID);

-- portfolio Report Ends


-- Building Report Starts

INSERT INTO Report_Folder (ORGID, MODULEID,NAME) VALUES (${orgId}, ${energyDataModuleId},'Building Reports');
SET @REPORT_FOLDER_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION,X_AXIS_LABEL,Y1_AXIS,Y1_AGGREGATE_FUNCTION,Y1_AXIS_LABEL,Y1_AXIS_UNIT) VALUES (${orgId},${energyDataModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Energy Consumption','Energy Consumption',12,@ED_TTIME_REPORT_FIELD_ID,19,'Time',@ED_TOTAL_CONS_DELTA_REPORT_FIELD_ID,3,'Energy','kwh');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${energydata_ttime},22,null);

INSERT INTO Report_SpaceFilter (ORGID,REPORT_ID,BUILDING_ID) VALUES (${orgId},@REPORT_ID,-1);

INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${energyDataModuleId},'Energy Consumption',1,100,'Energy Consumption',@BUILDING_DASHBOARD_ID,'{"layoutWidth":64,"layoutHeight":40,"xPosition":0,"yPosition":0,"layoutPosition":3}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ORGID,ID,REPORT_ID) VALUES (${orgId},@WIDGET_ID,@REPORT_ID);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION,X_AXIS_LABEL,Y1_AXIS,Y1_AGGREGATE_FUNCTION,Y1_AXIS_LABEL,Y1_AXIS_UNIT) VALUES (${orgId},${energyDataModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Energy Comparision','Energy Comparision',12,@ED_TTIME_REPORT_FIELD_ID,12,'Time',@ED_TOTAL_CONS_DELTA_REPORT_FIELD_ID,3,'Energy','kwh');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${energydata_ttime},49,30);

INSERT INTO Report_SpaceFilter (ORGID,REPORT_ID,BUILDING_ID) VALUES (${orgId},@REPORT_ID,-1);

INSERT INTO Report_BaseLine_Rel (ORGID,BASE_LINE_ID,REPORT_ID,ADJUST_TYPE) VALUES (${orgId},${baseline_PreviousMonth},@REPORT_ID,1);


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${energyDataModuleId},'Energy Comparision',1,100,'Energy Comparision',@BUILDING_DASHBOARD_ID,'{"layoutWidth":96,"layoutHeight":40,"xPosition":0,"yPosition":40,"layoutPosition":1}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ORGID,ID,REPORT_ID) VALUES (${orgId},@WIDGET_ID,@REPORT_ID);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION,X_AXIS_LABEL,Y1_AXIS,Y1_AGGREGATE_FUNCTION,Y1_AXIS_LABEL,Y1_AXIS_UNIT) VALUES (${orgId},${energyDataModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Service Usage','Service Usage',2,@EM_PURPOSE_REPORT_FIELD_ID,24,'Service',@ED_TOTAL_CONS_DELTA_REPORT_FIELD_ID,3,'Energy','kwh');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${energydata_ttime},49,30);

INSERT INTO Report_SpaceFilter (ORGID,REPORT_ID,BUILDING_ID) VALUES (${orgId},@REPORT_ID,-1);


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${energyDataModuleId},'Service Usage',1,100,'Service Usage',@BUILDING_DASHBOARD_ID,'{"layoutWidth":32,"layoutHeight":40,"xPosition":64,"yPosition":0,"layoutPosition":2}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ORGID,ID,REPORT_ID) VALUES (${orgId},@WIDGET_ID,@REPORT_ID);

INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION,X_AXIS_LABEL,Y1_AXIS,Y1_AGGREGATE_FUNCTION,Y1_AXIS_LABEL,Y1_AXIS_UNIT) VALUES (${orgId},${energyDataModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Daily Energy Breakdown','Daily Energy Breakdown',3,@ED_TTIME_REPORT_FIELD_ID,12,'Time',@ED_TOTAL_CONS_DELTA_REPORT_FIELD_ID,3,'Energy','kwh');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${energydata_ttime},49,30);

INSERT INTO Report_SpaceFilter (ORGID,REPORT_ID,BUILDING_ID) VALUES (${orgId},@REPORT_ID,-1);


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${energyDataModuleId},'Daily Energy Breakdown',1,100,'Daily Energy Breakdown',@BUILDING_DASHBOARD_ID,'{"layoutWidth":96,"layoutHeight":32,"xPosition":0,"yPosition":80,"layoutPosition":4}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ORGID,ID,REPORT_ID) VALUES (${orgId},@WIDGET_ID,@REPORT_ID);

INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION,X_AXIS_LABEL,Y1_AXIS,Y1_AGGREGATE_FUNCTION,Y1_AXIS_LABEL,Y1_AXIS_UNIT) VALUES (${orgId},${energyDataModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Heatmap','Heatmap',11,@ED_TTIME_REPORT_FIELD_ID,20,'Time',@ED_TOTAL_CONS_DELTA_REPORT_FIELD_ID,3,'Energy','kwh');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${energydata_ttime},44,null);

INSERT INTO Report_SpaceFilter (ORGID,REPORT_ID,BUILDING_ID) VALUES (${orgId},@REPORT_ID,-1);


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${energyDataModuleId},'Heatmap',1,100,'Heatmap',@BUILDING_DASHBOARD_ID,'{"layoutWidth":96,"layoutHeight":40,"xPosition":0,"yPosition":46,"layoutPosition":5}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ORGID,ID,REPORT_ID) VALUES (${orgId},@WIDGET_ID,@REPORT_ID);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION,X_AXIS_LABEL,Y1_AXIS,Y1_AGGREGATE_FUNCTION,Y1_AXIS_LABEL,Y1_AXIS_UNIT) VALUES (${orgId},${energyDataModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Year Wise Comparison','Year Wise Comparison',5,@ED_TTIME_REPORT_FIELD_ID,15,'Time',@ED_TOTAL_CONS_DELTA_REPORT_FIELD_ID,3,'Energy','kwh');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${energydata_ttime},44,null);

INSERT INTO Report_SpaceFilter (ORGID,REPORT_ID,BUILDING_ID) VALUES (${orgId},@REPORT_ID,-1);

INSERT INTO Report_BaseLine_Rel (ORGID,BASE_LINE_ID,REPORT_ID,ADJUST_TYPE) VALUES (${orgId},${baseline_PreviousYear},@REPORT_ID,1);


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${energyDataModuleId},'Year Wise Comparison',1,100,'Year Wise Comparison',@BUILDING_DASHBOARD_ID,'{"layoutWidth":56,"layoutHeight":32,"xPosition":0,"yPosition":152,"layoutPosition":8}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ORGID,ID,REPORT_ID) VALUES (${orgId},@WIDGET_ID,@REPORT_ID);


INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION,X_AXIS_LABEL,Y1_AXIS,Y1_AGGREGATE_FUNCTION,Y1_AXIS_LABEL,Y1_AXIS_UNIT) VALUES (${orgId},${energyDataModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'End Use Breakdown','End Use Breakdown',7,@ED_TTIME_REPORT_FIELD_ID,12,'Time',@ED_TOTAL_CONS_DELTA_REPORT_FIELD_ID,3,'Energy','kwh');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${energydata_ttime},49,30);

INSERT INTO Report_SpaceFilter (ORGID,REPORT_ID,BUILDING_ID,GROUP_BY) VALUES (${orgId},@REPORT_ID,-1,'service');


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${energyDataModuleId},'End Use Breakdown',1,100,'End Use Breakdown',@BUILDING_DASHBOARD_ID,'{"layoutWidth":96,"layoutHeight":40,"xPosition":0,"yPosition":112,"layoutPosition":6}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ORGID,ID,REPORT_ID) VALUES (${orgId},@WIDGET_ID,@REPORT_ID);

INSERT INTO Report_Entity (ORGID) VALUES (${orgId});
SET @REPORT_ENTITY_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report (ORGID,MODULEID,REPORT_FOLDER_ID,REPORT_ENTITY_ID,NAME,DESCRIPTION,CHART_TYPE,X_AXIS,X_AGGREGATE_FUNCTION,X_AXIS_LABEL,Y1_AXIS,Y1_AGGREGATE_FUNCTION,Y1_AXIS_LABEL,Y1_AXIS_UNIT) VALUES (${orgId},${energyDataModuleId},@REPORT_FOLDER_ID,@REPORT_ENTITY_ID,'Cost usage by End use','Cost usage by End use',4,@ED_TTIME_REPORT_FIELD_ID,12,'Time',@ED_TOTAL_CONS_DELTA_REPORT_FIELD_ID,3,'Cost','cost');
SET @REPORT_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Report_DateFilter (ORGID,REPORT_ID,FIELD_ID,OPERATOR,VAL) VALUES (${orgId},@REPORT_ID,${energydata_ttime},49,30);

INSERT INTO Report_SpaceFilter (ORGID,REPORT_ID,BUILDING_ID,GROUP_BY) VALUES (${orgId},@REPORT_ID,-1,'service');


INSERT INTO Widget (ORGID,MODULEID,WIDGET_NAME,TYPE,DATA_REFRESH_INTERTVEL,HEADER_TEXT,DASHBOARD_ID,META_JSON) VALUES (${orgId},${energyDataModuleId},'Cost usage by End use',1,100,'Cost usage by End use',@BUILDING_DASHBOARD_ID,'{"layoutWidth":40,"layoutHeight":32,"xPosition":56,"yPosition":152,"layoutPosition":7}');
set @WIDGET_ID = (SELECT LAST_INSERT_ID());

INSERT INTO Widget_Chart (ORGID,ID,REPORT_ID) VALUES (${orgId},@WIDGET_ID,@REPORT_ID);

-- Building Report Ends

-- energy module population Ends

INSERT INTO OrgInfo (ORGID,NAME,VALUE) VALUES (${orgId},'newdashboard','wo,em,fa');

