SET @READING_MODULE_TYPE := 3;
SET @AHU_MODULE_ID := (SELECT MODULEID from Modules where NAME = "ahu" AND ORGID = ${orgId});
SET @AHU_CATEGORY_ID := (SELECT ID from Asset_Categories where NAME = "AHU" AND ORGID = ${orgId});

INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME, TABLE_NAME, MODULE_TYPE) VALUES (${orgId}, 'ahureadinggeneral', 'AHU Readings General', 'AHU_Readings_General', @READING_MODULE_TYPE);
SET @AHU_READING_GENERAL := (SELECT LAST_INSERT_ID());
INSERT INTO SubModulesRel (ORGID,PARENT_MODULE_ID, CHILD_MODULE_ID) VALUES (${orgId},@AHU_MODULE_ID, @AHU_READING_GENERAL);

INSERT INTO Asset_Category_Readings (ORGID,PARENT_CATEGORY_ID, READING_MODULE_ID) VALUES (${orgId},@AHU_CATEGORY_ID, @AHU_READING_GENERAL);
/* First AHU Reading Table Start */
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_GENERAL, 'parentId', 'Parent', 9, 'PARENT_ID', 2, true, false, true);
INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_GENERAL, 'sourceType', 'Source Type', 3, 'SOURCE_TYPE', 12, false, false, true);
INSERT INTO SystemEnumFields (FIELDID, ORGID, ENUM_NAME) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'SourceType');
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_GENERAL, 'sourceId', 'Source Id', 9, 'SOURCE_ID', 2, false, false, true);
INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_GENERAL, 'actualTtime', 'Actual Timestamp', 9, 'ACTUAL_TTIME', 6, true, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_GENERAL, 'ttime', 'Timestamp', 9, 'TTIME', 6, true, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_GENERAL, 'date', 'Date', 1, 'TTIME_DATE', 1, true, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_GENERAL, 'month', 'Month', 9, 'TTIME_MONTH', 2, true, false, true);
INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_GENERAL, 'week', 'Week', 9, 'TTIME_WEEK', 2, true, false, true);
INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_GENERAL, 'day', 'Day', 9, 'TTIME_DAY', 2, true, false, true);
INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_GENERAL, 'hour', 'Hour', 9, 'TTIME_HOUR', 2, true, false, true);
INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_GENERAL,'runCommand','Run Command',5,'RUN_COMMAND',4,TRUE,FALSE,FALSE);
INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'On', 'Off');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_GENERAL,'runStatus','Run Status',5,'RUN_STATUS',4,TRUE,FALSE,FALSE);
INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'On', 'Off');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_GENERAL,'autoManualStatus','Auto/Manual Status ',5,'AUTO_MANUAL_STATUS',4,TRUE,FALSE,FALSE);
 INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Auto', 'Manual');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_GENERAL,'tripStatus','Trip Status',5,'TRIP_STATUS',4,TRUE,FALSE,FALSE);
 INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Trip', 'Normal');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_GENERAL,'runHour','Run Hour',9,'RUN_HOUR',3,TRUE,FALSE,FALSE);
INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 5, 18);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_GENERAL,'filterDifferentialPressure','Filter Differential Pressure',9,'FILTER_DIFFERENTIAL_PRESSURE',3,TRUE,FALSE,FALSE);
INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 11, 61);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_GENERAL,'filterDirtyStatus','Filter Dirty Status',5,'FILTER_DIRTY_STATUS',4,TRUE,FALSE,FALSE);
 INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Choke', 'Normal');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_GENERAL,'preFilterDifferentialPressure','Pre Filter Differential Pressure',9,'PRE_FILTER_DIFFERENTIAL_PRESSURE',3,TRUE,FALSE,FALSE);
INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 11, 61);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_GENERAL,'preFilterStatus','Pre Filter Status',5,'PRE_FILTER_STATUS',4,TRUE,FALSE,FALSE);
 INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Choke', 'Normal');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_GENERAL,'bagFilterDifferentialPressure','Bag Filter Differential Pressure',9,'BAG_FILTER_DIFFERENTIAL_PRESSURE',3,TRUE,FALSE,FALSE);
INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 11, 61);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_GENERAL,'bagFilterStatus','Bag Filter Status',5,'BAG_FILTER_STATUS',4,TRUE,FALSE,FALSE);
 INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Choke', 'Normal');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_GENERAL,'chilledWaterEnteringTemperature','Chilled Water Entering Temperature',9,'CHILLED_WATER_ENTERING_TEMPERATURE',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 2, 4);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_GENERAL,'chilledWaterLeavingTemperature','Chilled Water Leaving Temperature',9,'CHILLED_WATER_LEAVING_TEMPERATURE',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 2, 4);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_GENERAL,'chilledWaterDeltaTemperature','Chilled Water Delta Temperature',9,'CHILLED_WATER_DELTA_TEMPERATURE',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 2, 4);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_GENERAL,'chilledWaterFlowDifferentialPressure','Chilled Water Flow Differential Pressure ',9,'CHILLED_WATER_FLOW_DIFFERENTIAL_PRESSURE',3,TRUE,FALSE,FALSE);
INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 11, 61);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_GENERAL,'chilledWaterStrainerDifferentialPressure','Chilled Water Strainer Differential Pressure',9,'CHILLED_WATER_STRAINER_DIFFERENTIAL_PRESSURE',3,TRUE,FALSE,FALSE);
INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 11, 61);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_GENERAL,'coolingCoilValveCommand','Cooling Coil Valve Command',5,'COOLING_COIL_VALVE_COMMAND',4,TRUE,FALSE,FALSE);
INSERT INTO BooleanFields (FIELDID, ORGID,  TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Open', 'Close');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_GENERAL,'coolingCoilValveStatus','Cooling Coil Valve Status ',5,'COOLING_COIL_VALVE_STATUS',4,TRUE,FALSE,FALSE);
INSERT INTO BooleanFields (FIELDID, ORGID,  TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Open', 'Close');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_GENERAL,'coolingCoilValveControl','Cooling Coil Valve Control',9,'COOLING_COIL_VALVE_CONTROL',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_GENERAL,'coolingCoilValveFeedback','Cooling Coil Valve FeedBack ',9,'COOLING_COIL_VALVE_FEEDBACK',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_GENERAL,'airFlowCoilDifferentialPressure','AirFlow Coil Differential Pressure ',9,'AIRFLOW_COIL_DIFFERINATIAL_PRESSURE',3,TRUE,FALSE,FALSE);
INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 11, 61);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_GENERAL,'enthalphyHeatWheelAutoManualStatus','Enthalphy Heat Wheel Auto/Manual Status',5,'ENTHALPHY_HEAT_WHEEL_AUTO_MANUAL_STATUS',4,TRUE,FALSE,FALSE);
INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Auto' , 'Manul');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_GENERAL,'enthalphyHeatWheelCommand','Enthalphy Heat Wheel Command',5,'ENTHALPHY_HEAT_WHEEL_COMMAND',4,TRUE,FALSE,FALSE);
INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'On', 'Off');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_GENERAL,'enthalphyHeatWheelRunStatus','Enthalphy Heat Wheel Run Status',5,'ENTHALPHY_HEAT_WHEEL_RUN_STATUS',4,TRUE,FALSE,FALSE);
INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'On', 'Off');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_GENERAL,'sensibleHeatWheelAutoManualStatus','Sensible Heat Wheel Auto/Manual Status',5,'SENSIBLE_HEAT_WHEEL_AUTO_MANUAL_STATUS',4,TRUE,FALSE,FALSE);
INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Auto' , 'Manul');


INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_GENERAL,'sensibleHeatWheelCommand','Sensible Heat Wheel Command',5,'SENSIBLE_HEAT_WHEEL_COMMAND',4,TRUE,FALSE,FALSE);
INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'On', 'Off');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_GENERAL,'sensibleHeatWheelRunStatus','Sensible Heat Wheel Run Status',5,'SENSIBLE_HEAT_WHEEL_RUN_STATUS',4,TRUE,FALSE,FALSE);
INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'On', 'Off');
/* First AHU Reading Table Start */

/* Second AHU Reading Table Start */
INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME, TABLE_NAME, MODULE_TYPE) VALUES (${orgId}, 'ahureadingexhaustair', 'AHU Readings Exhaust Air', 'AHU_Readings_Exhaust_Air', @READING_MODULE_TYPE);
SET @AHU_READING_EXHAUST_AIR := (SELECT LAST_INSERT_ID());
INSERT INTO SubModulesRel (ORGID,PARENT_MODULE_ID, CHILD_MODULE_ID) VALUES (${orgId},@AHU_MODULE_ID, @AHU_READING_EXHAUST_AIR);

INSERT INTO Asset_Category_Readings (ORGID,PARENT_CATEGORY_ID, READING_MODULE_ID) VALUES (${orgId},@AHU_CATEGORY_ID, @AHU_READING_EXHAUST_AIR);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_EXHAUST_AIR, 'parentId', 'Parent', 9, 'PARENT_ID', 2, true, false, true);
INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_EXHAUST_AIR, 'sourceType', 'Source Type', 3, 'SOURCE_TYPE', 12, false, false, true);
INSERT INTO SystemEnumFields (FIELDID, ORGID, ENUM_NAME) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'SourceType');
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_EXHAUST_AIR, 'sourceId', 'Source Id', 9, 'SOURCE_ID', 2, false, false, true);
INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_EXHAUST_AIR, 'actualTtime', 'Actual Timestamp', 9, 'ACTUAL_TTIME', 6, true, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_EXHAUST_AIR, 'ttime', 'Timestamp', 9, 'TTIME', 6, true, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_EXHAUST_AIR, 'date', 'Date', 1, 'TTIME_DATE', 1, true, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_EXHAUST_AIR, 'month', 'Month', 9, 'TTIME_MONTH', 2, true, false, true);
INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_EXHAUST_AIR, 'week', 'Week', 9, 'TTIME_WEEK', 2, true, false, true);
INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_EXHAUST_AIR, 'day', 'Day', 9, 'TTIME_DAY', 2, true, false, true);
INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_EXHAUST_AIR, 'hour', 'Hour', 9, 'TTIME_HOUR', 2, true, false, true);
INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});


INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_EXHAUST_AIR,'exhaustAirDamperCommand','Exhaust Air Damper Command',5,'EXHAUST_AIR_DAMPER_COMMAND',4,TRUE,FALSE,FALSE);
 INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Open', 'Close');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_EXHAUST_AIR,'exhaustAirDamperStatus','Exhaust Air Damper Status',5,'EXHAUST_AIR_DAMPER_STATUS',4,TRUE,FALSE,FALSE);
 INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Open', 'Close');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_EXHAUST_AIR,'exhaustAirDamperControl','Exhaust Air Damper Control',9,'EXHAUST_AIR_DAMPER_CONTROL',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_EXHAUST_AIR,'exhaustAirDamperFeedback','Exhaust Air Damper Feedback',9,'EXHAUST_AIR_DAMPER_FEEDBACK',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_EXHAUST_AIR,'returnAirTemperature','Return Air Temperature',9,'RETURN_AIR_TEMPERATURE',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 2, 4);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_EXHAUST_AIR,'returnAirTemperatureSetpoint','Return Air Temperature Setpoint',9,'RETURN_AIR_TEMPERATURE_SETPOINT',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 2, 4);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_EXHAUST_AIR,'returnAirHumidity','Return Air Humidity',9,'RETURN_AIR_HUMIDITY',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_EXHAUST_AIR,'returnAirHumiditySetpoint','Return Air Humidity Setpoint',9,'RETURN_AIR_HUMIDITY_SETPOINT',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_EXHAUST_AIR,'returnAirDamperCommand','Return Air Damper Command',5,'RETURN_AIR_DAMPER_COMMAND',4,TRUE,FALSE,FALSE);
 INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Open', 'Close');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_EXHAUST_AIR,'returnAirDamperStatus','Return Air Damper Status',5,'RETURN_AIR_DAMPER_STATUS',4,TRUE,FALSE,FALSE);
 INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Open', 'Close');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_EXHAUST_AIR,'returnAirDamperControl','Return Air Damper Control',9,'RETURN_AIR_DAMPER_CONTROL',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_EXHAUST_AIR,'returnAirDamperFeedback','Return Air Damper Feedback',9,'RETURN_AIR_DAMPER_FEEDBACK',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_EXHAUST_AIR,'returnAirFlowRate','Return Air Flow Rate ',9,'RETURN_AIR_FLOW_RATE',3,TRUE,FALSE,FALSE);
  INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 18, 100);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_EXHAUST_AIR,'returnAirFlowStatus','Return Air Flow Status ',5,'RETURN_AIR_FLOW_STATUS',4,TRUE,FALSE,FALSE);
INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'On', 'Off');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_EXHAUST_AIR,'returnAirFlowFailAlarm','Return Air Flow Fail Alarm',5,'RETURN_AIR_FLOW_FAIL_ALARM',4,TRUE,FALSE,FALSE);
INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'Fail', 'Normal');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_EXHAUST_AIR,'returnFanAutoManualStatus','Return Fan Auto/Manual Status',5,'RETURN_FAN_AUTO_MANUAL_STATUS',4,TRUE,FALSE,FALSE);
 INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Auto', 'Manual');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_EXHAUST_AIR,'returnFanCommand','Return Fan Command',5,'RETURN_FAN_COMMAND',4,TRUE,FALSE,FALSE);
INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'On', 'Off');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_EXHAUST_AIR,'returnFanRunStatus','Return Fan Run Status',5,'RETURN_FAN_RUN_STATUS',4,TRUE,FALSE,FALSE);
INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'On', 'Off');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_EXHAUST_AIR,'returnFanMotorEnergy','Return Fan Motor Energy',9,'RETURN_FAN_MOTOR_ENERGY',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 1, 1);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_EXHAUST_AIR,'returnFanMotorPower','Return Fan Motor Power',9,'RETURN_FAN_MOTOR_POWER',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 8, 46);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_EXHAUST_AIR,'returnFanMotorDriveEndTemperature','Return Fan Motor Drive End Temperature',9,'RETURN_FAN_MOTOR_DRIVE_END_TEMPERATURE',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 2, 4);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_EXHAUST_AIR,'returnFanMotorDriveEndVibration','Return Fan Motor Drive End Vibration',9,'RETURN_FAN_MOTOR_DRIVE_END_VIBRATION',3,TRUE,FALSE,FALSE);
INSERT INTO NumberFields (FIELDID, ORGID, UNIT_ID, METRIC) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  51, 9);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_EXHAUST_AIR,'returnFanMotorNonDriveEndTemperature','Return Fan Motor Non-Drive End Temperature',9,'RETURN_FAN_MOTOR_NONDRIVE_END_TEMPERATURE',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 2, 4);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_EXHAUST_AIR,'returnFanMotorNonDriveEndVibration','Return Fan Motor Non-Drive End Vibration',9,'RETURN_FAN_MOTOR_NONDRIVE_END_VIBRATION',3,TRUE,FALSE,FALSE);
INSERT INTO NumberFields (FIELDID, ORGID, UNIT_ID, METRIC) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  51, 9);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_EXHAUST_AIR,'returnFanVfdControl','Return Fan VFD Control',9,'RETURN_FAN_VFD_CONTROL',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_EXHAUST_AIR,'returnFanVfdFeedback','Return Fan VFD Feedback',9,'RETURN_FAN_VFD_FEEDBACK',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_EXHAUST_AIR,'returnFanVfdFrequency','Return Fan VFD Frequency',9,'RETURN_FAN_VFD_FREQUENCY',3,TRUE,FALSE,FALSE);
INSERT INTO NumberFields (FIELDID, ORGID, UNIT_ID, METRIC) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  51, 9);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_EXHAUST_AIR,'returnFanVfdSpeed','Return Fan VFD Speed',9,'RETURN_FAN_VFD_SPEED',3,TRUE,FALSE,FALSE);
INSERT INTO NumberFields (FIELDID, ORGID, METRIC) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 22);


INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_EXHAUST_AIR,'returnFanVfdAutoManualStatus','Return Fan VFD Auto/Manual Status',5,'RETURN_FAN_VFD_AUTO_MANUAL_STATUS',4,TRUE,FALSE,FALSE);
 INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Auto', 'Manual');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_EXHAUST_AIR,'returnFanVfdRunStatus','Return Fan VFD Run Status',5,'RETURN_FAN_VFD_RUN_STATUS',4,TRUE,FALSE,FALSE);
INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'On', 'Off');


/* Second AHU Reading Table End */

/* Third AHU Reading Table  STart*/
INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME, TABLE_NAME, MODULE_TYPE) VALUES (${orgId}, 'ahureadingsupplyair', 'AHU Readings Supply Air', 'AHU_Readings_Supply_Air', @READING_MODULE_TYPE);
SET @AHU_READING_SUPPLY_AIR := (SELECT LAST_INSERT_ID());
INSERT INTO SubModulesRel (ORGID,PARENT_MODULE_ID, CHILD_MODULE_ID) VALUES (${orgId},@AHU_MODULE_ID, @AHU_READING_SUPPLY_AIR);

INSERT INTO Asset_Category_Readings (ORGID,PARENT_CATEGORY_ID, READING_MODULE_ID) VALUES (${orgId},@AHU_CATEGORY_ID, @AHU_READING_SUPPLY_AIR);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_SUPPLY_AIR, 'parentId', 'Parent', 9, 'PARENT_ID', 2, true, false, true);
INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_SUPPLY_AIR, 'sourceType', 'Source Type', 3, 'SOURCE_TYPE', 12, false, false, true);
INSERT INTO SystemEnumFields (FIELDID, ORGID, ENUM_NAME) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'SourceType');
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_SUPPLY_AIR, 'sourceId', 'Source Id', 9, 'SOURCE_ID', 2, false, false, true);
INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_SUPPLY_AIR, 'actualTtime', 'Actual Timestamp', 9, 'ACTUAL_TTIME', 6, true, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_SUPPLY_AIR, 'ttime', 'Timestamp', 9, 'TTIME', 6, true, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_SUPPLY_AIR, 'date', 'Date', 1, 'TTIME_DATE', 1, true, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_SUPPLY_AIR, 'month', 'Month', 9, 'TTIME_MONTH', 2, true, false, true);
INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_SUPPLY_AIR, 'week', 'Week', 9, 'TTIME_WEEK', 2, true, false, true);
INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_SUPPLY_AIR, 'day', 'Day', 9, 'TTIME_DAY', 2, true, false, true);
INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_SUPPLY_AIR, 'hour', 'Hour', 9, 'TTIME_HOUR', 2, true, false, true);
INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});



INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'outsideAirTemperature','Outside Air Temperature',9,'OUTSIDE_AIR_TEMPERATURE',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 2, 4);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'outsideAirHumidity','Outside Air Humidity',9,'OUTSIDE_AIR_HUMIDITY',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'outsideAirDamperControl','Outside Air Damper Control',9,'OUTSIDE_AIR_DAMPER_CONTROL',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'outsideAirDamperFeedback','Outside Air Damper Feedback',9,'OUTSIDE_AIR_DAMPER_FEEDBACK',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'supplyAirDamperControl','Supply Air Damper Control',9,'SUPPLY_AIR_DAMPER_CONTROL',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'supplyAirDamperFeedback','Supply Air Damper Feedback',9,'SUPPLY_AIR_DAMPER_FEEDBACK',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'supplyAirTemperature','Supply Air Temperature',9,'SUPPLY_AIR_TEMPERATURE',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 2, 4);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'supplyAirTemperatureSetpoint','Supply Air Temperature Setpoint',9,'SUPPLY_AIR_TEMPERATURE_SETPOINT',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 2, 4);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'supplyAirHumidity','Supply Air Humidity',9,'SUPPLY_AIR_HUMIDITY',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'supplyAirHumiditySetpoint','Supply Air Humidity Setpoint',9,'SUPPLY_AIR_HUMIDITY_SETPOINT',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'supplyAirPressure','Supply Air Pressure',9,'SUPPLY_AIR_PRESSURE',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 11, 105);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'supplyAirPressureSetpoint','Supply Air Pressure Setpoint',9,'SUPPLY_AIR_PRESSURE_SETPOINT',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 11, 105);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'supplyAirFlowRate','Supply Air Flow Rate ',9,'SUPPLY_AIR_FLOW_RATE',3,TRUE,FALSE,FALSE);
  INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 18, 100);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'supplyFanMotorEnergy','Supply Fan Motor Energy',9,'SUPPLY_FAN_MOTOR_ENERGY',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 1, 1);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'supplyFanMotorPower','Supply Fan Motor Power',9,'SUPPLY_FAN_MOTOR_POWER',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 8, 46);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'supplyFanMotorDriveEndTemperature','Supply Fan Motor Drive End Temperature',9,'SUPPLY_FAN_MOTOR_DRIVE_END_TEMPERATURE',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 2, 4);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'supplyFanMotorDriveEndVibration','Supply Fan Motor Drive End Vibration',9,'SUPPLY_FAN_MOTOR_DRIVE_END_VIBRATION',3,TRUE,FALSE,FALSE);
INSERT INTO NumberFields (FIELDID, ORGID, UNIT_ID, METRIC) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  51, 9);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'supplyFanMotorNonDriveEndTemperature','Supply Fan Motor Non-Drive End Temperature',9,'SUPPLY_FAN_MOTOR_NONDRIVE_END_TEMPERATURE',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 2, 4);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'supplyFanMotorNonDriveEndVibration','Supply Fan Motor Non-Drive End Vibration',9,'SUPPLY_FAN_MOTOR_NONDRIVE_END_VIBRATION',3,TRUE,FALSE,FALSE);
INSERT INTO NumberFields (FIELDID, ORGID, UNIT_ID, METRIC) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  51, 9);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'supplyFanVfdControl','Supply Fan VFD Control',9,'SUPPLY_FAN_VFD_CONTROL',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'supplyFanVfdFeedback','Supply Fan VFD Feedback',9,'SUPPLY_FAN_VFD_FEEDBACK',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'supplyFanVfdFrequency','Supply Fan VFD Frequency',9,'SUPPLY_FAN_VFD_FREQUENCY',3,TRUE,FALSE,FALSE);
INSERT INTO NumberFields (FIELDID, ORGID, UNIT_ID, METRIC) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  51, 9);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'supplyFanVfdSpeed','Supply Fan VFD Speed',9,'SUPPLY_FAN_VFD_SPEED',3,TRUE,FALSE,FALSE);
INSERT INTO NumberFields (FIELDID, ORGID, METRIC) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 22);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'supplyFanVfdAutoManualStatus','Supply Fan VFD Auto/Manual Status',5,'SUPPLY_FAN_VFD_AUTO_MANUAL_STATUS',4,TRUE,FALSE,FALSE);
INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Auto', 'Manual');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'supplyFanVfdRunStatus','Supply Fan VFD Run Status',5,'SUPPLY_FAN_VFD_RUN_STATUS',4,TRUE,FALSE,FALSE);
INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'On', 'Off');


INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'outsideAirDamperCommand','Outside Air Damper Command',5,'OUTSIDE_AIR_DAMPER_COMMAND',4,TRUE,FALSE,FALSE);
INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'Open', 'Close');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'outsideAirDamperStatus','Outside Air Damper Status',5,'OUTSIDE_AIR_DAMPER_STATUS',4,TRUE,FALSE,FALSE);
INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'Open', 'Close');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'supplyAirDamperCommand','Supply Air Damper Command',5,'SUPPLY_AIR_DAMPER_COMMAND',4,TRUE,FALSE,FALSE);
INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'Open', 'Close');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'supplyAirDamperStatus','Supply Air Damper Status',5,'SUPPLY_AIR_DAMPER_STATUS',4,TRUE,FALSE,FALSE);
INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'Open', 'Close');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'supplyAirFlowStatus','Supply Air Flow Status',5,'SUPPLY_AIR_FLOW_STATUS',4,TRUE,FALSE,FALSE);
INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'On', 'Off');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'supplyAirFlowFailAlarm','Supply Air Flow Fail Alarm',5,'SUPPLY_AIR_FLOW_FAIL_ALARM',4,TRUE,FALSE,FALSE);
INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'Fail', 'Normal');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'supplyFanAuto/ManualStatus','Supply Fan Auto/Manual Status',5,'SUPPLY_FAN_AUTO_MANUAL_STATUS',4,TRUE,FALSE,FALSE);
INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'Auto', 'Manual');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'supplyFanCommand','Supply Fan Command',5,'SUPPLY_FAN_COMMAND',4,TRUE,FALSE,FALSE);
INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'On', 'Off');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@AHU_READING_SUPPLY_AIR,'supplyFanRunStatus','Supply Fan Run Status',5,'SUPPLY_FAN_RUN_STATUS',4,TRUE,FALSE,FALSE);
INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'On', 'Off');
/* Third AHU Reading Table  End*/

/* Fourth Ahu Reading table start */
INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME, TABLE_NAME, MODULE_TYPE) VALUES (${orgId}, 'ahureadingmixair', 'AHU Readings Mix Air', 'AHU_Readings_Mix_Air', @READING_MODULE_TYPE);
SET @AHU_READING_MIX_AIR := (SELECT LAST_INSERT_ID());
INSERT INTO SubModulesRel (ORGID,PARENT_MODULE_ID, CHILD_MODULE_ID) VALUES (${orgId},@AHU_MODULE_ID, @AHU_READING_MIX_AIR);

INSERT INTO Asset_Category_Readings (ORGID,PARENT_CATEGORY_ID, READING_MODULE_ID) VALUES (${orgId},@AHU_CATEGORY_ID, @AHU_READING_MIX_AIR);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_MIX_AIR, 'parentId', 'Parent', 9, 'PARENT_ID', 2, true, false, true);
INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_MIX_AIR, 'sourceType', 'Source Type', 3, 'SOURCE_TYPE', 12, false, false, true);
INSERT INTO SystemEnumFields (FIELDID, ORGID, ENUM_NAME) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'SourceType');
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_MIX_AIR, 'sourceId', 'Source Id', 9, 'SOURCE_ID', 2, false, false, true);
INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_MIX_AIR, 'actualTtime', 'Actual Timestamp', 9, 'ACTUAL_TTIME', 6, true, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_MIX_AIR, 'ttime', 'Timestamp', 9, 'TTIME', 6, true, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_MIX_AIR, 'date', 'Date', 1, 'TTIME_DATE', 1, true, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_MIX_AIR, 'month', 'Month', 9, 'TTIME_MONTH', 2, true, false, true);
INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_MIX_AIR, 'week', 'Week', 9, 'TTIME_WEEK', 2, true, false, true);
INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_MIX_AIR, 'day', 'Day', 9, 'TTIME_DAY', 2, true, false, true);
INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AHU_READING_MIX_AIR, 'hour', 'Hour', 9, 'TTIME_HOUR', 2, true, false, true);
INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId}, @AHU_READING_MIX_AIR,'mixedAirTemperature','Mixed Air Temperature',9,'MIXED_AIR_TEMPERATURE',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 2, 4);

 INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId}, @AHU_READING_MIX_AIR,'mixedAirHumidity','Mixed Air Humidity',9,'MIXED_AIR_HUMIDITY',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId}, @AHU_READING_MIX_AIR,'mixedAirDamperCommand','Mixed Air Damper Command',5,'MIXED_AIR_DAMPER_COMMAND',4,TRUE,FALSE,FALSE);
 INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Open', 'Close');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId}, @AHU_READING_MIX_AIR,'mixedAirDamperStatus','Mixed Air Damper Status',5,'MIXED_AIR_DAMPER_STATUS',4,TRUE,FALSE,FALSE);
 INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Open', 'Close');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId}, @AHU_READING_MIX_AIR,'mixedAirDamperControl','Mixed Air Damper Control',9,'MIXED_AIR_DAMPER_CONTROL',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId}, @AHU_READING_MIX_AIR,'mixedAirDamperFeedback','Mixed Air Damper Feedback',9,'MIXED_AIR_DAMPER_FEEDBACK',3,TRUE,FALSE,FALSE);
 INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);

/* Fourth Ahu Reading table End */

/*AHU reading Ends*/
 
 
--INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME, TABLE_NAME, EXTENDS_ID, MODULE_TYPE, IS_TRASH_ENABLED) VALUES (${orgId}, 'fahu', 'FAHU', 'FAHU', @ASSETS_MODULE_ID, @BASE_ENTITY_MODULE_TYPE, true);
--SET @FAHU_MODULE_ID := (SELECT LAST_INSERT_ID());

--INSERT INTO Asset_Categories (ORGID, MODULEID, NAME, DISPLAY_NAME, CATEGORY_TYPE, PARENT_CATEGORY_ID, ASSET_MODULEID, IS_DEFAULT) VALUES (${orgId}, @ASSET_CATEGORY_MODULE_ID, 'FAHU', 'FAHU', 1, @HVAC_CATEGORY_ID, @FAHU_MODULE_ID, true);
--SET @FAHU_CATEGORY_ID := (SELECT LAST_INSERT_ID());
 
/*FAHU reading Starts*/
 
--SET @FAHU_MODULE_ID := (SELECT MODULEID from Modules where NAME = "fahu" AND ORGID = ${orgId});
--SET @FAHU_CATEGORY_ID := (SELECT ID from Asset_Categories where NAME = "FAHU" AND ORGID = ${orgId});
--
--INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME, TABLE_NAME, MODULE_TYPE) VALUES (${orgId}, 'fahureadinggeneral', 'FAHU Readings General', 'FAHU_Readings_General', @READING_MODULE_TYPE);
--SET @FAHU_READING_GENERAL := (SELECT LAST_INSERT_ID());
--INSERT INTO SubModulesRel (ORGID,PARENT_MODULE_ID, CHILD_MODULE_ID) VALUES (${orgId},@FAHU_MODULE_ID, @FAHU_READING_GENERAL);
--
--INSERT INTO Asset_Category_Readings (ORGID,PARENT_CATEGORY_ID, READING_MODULE_ID) VALUES (${orgId},@FAHU_CATEGORY_ID, @FAHU_READING_GENERAL);
--
--/* First FAHU Reading Table Start */
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FAHU_READING_GENERAL, 'parentId', 'Parent', 9, 'PARENT_ID', 2, true, false, true);
--INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FAHU_READING_GENERAL, 'sourceType', 'Source Type', 3, 'SOURCE_TYPE', 12, false, false, true);
--INSERT INTO SystemEnumFields (FIELDID, ORGID, ENUM_NAME) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'SourceType');
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FAHU_READING_GENERAL, 'sourceId', 'Source Id', 9, 'SOURCE_ID', 2, false, false, true);
--INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FAHU_READING_GENERAL, 'actualTtime', 'Actual Timestamp', 9, 'ACTUAL_TTIME', 6, true, false, true);
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FAHU_READING_GENERAL, 'ttime', 'Timestamp', 9, 'TTIME', 6, true, false, true);
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FAHU_READING_GENERAL, 'date', 'Date', 1, 'TTIME_DATE', 1, true, false, true);
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FAHU_READING_GENERAL, 'month', 'Month', 9, 'TTIME_MONTH', 2, true, false, true);
--INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FAHU_READING_GENERAL, 'week', 'Week', 9, 'TTIME_WEEK', 2, true, false, true);
--INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FAHU_READING_GENERAL, 'day', 'Day', 9, 'TTIME_DAY', 2, true, false, true);
--INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FAHU_READING_GENERAL, 'hour', 'Hour', 9, 'TTIME_HOUR', 2, true, false, true);
--INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'runCommand','Run Command',5,'RUN_COMMAND',4,TRUE,FALSE,FALSE);
--INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'On', 'Off');
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'runStatus','Run Status',5,'RUN_STATUS',4,TRUE,FALSE,FALSE);
--INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'On', 'Off');
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'runHourStatus','Auto/Manual Status ',5,'AUTO_MANUAL_STATUS',4,TRUE,FALSE,FALSE);
-- INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Auto', 'Manual');
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'tripStatus','Trip Status',5,'TRIP_STATUS',4,TRUE,FALSE,FALSE);
-- INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Trip', 'Normal');
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'runHour','Run Hour',9,'RUN_HOUR',3,TRUE,FALSE,FALSE);
--INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 5, 18);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'filterDifferentialPressure','Filter Differential Pressure',9,'FILTER_DIFFERENTIAL_PRESSURE',3,TRUE,FALSE,FALSE);
--INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 11, 61);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'filterDirtyStatus','Filter Dirty Status',5,'FILTER_DIRTY_STATUS',4,TRUE,FALSE,FALSE);
-- INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Choke', 'Normal');
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'preFilterDifferentialPressure','Pre Filter Differential Pressure',9,'PRE_FILTER_DIFFERENTIAL_PRESSURE',3,TRUE,FALSE,FALSE);
--INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 11, 61);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'preFilterStatus','Pre Filter Status',5,'PRE_FILTER_STATUS',4,TRUE,FALSE,FALSE);
-- INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Choke', 'Normal');
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'bagFilterDifferentialPressure','Bag Filter Differential Pressure',9,'BAG_FILTER_DIFFERENTIAL_PRESSURE',3,TRUE,FALSE,FALSE);
--INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 11, 61);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'bagFilterStatus','Bag Filter Status',5,'BAG_FILTER_STATUS',4,TRUE,FALSE,FALSE);
-- INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Choke', 'Normal');
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'chilledWaterEnteringTemperature','Chilled Water Entering Temperature',9,'CHILLED_WATER_ENTERING_TEMPERATURE',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 2, 4);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'chilledWaterLeavingTemperature','Chilled Water Leaving Temperature',9,'CHILLED_WATER_LEAVING_TEMPERATURE',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 2, 4);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'chilledWaterDeltaTemperature','Chilled Water Delta Temperature',9,'CHILLED_WATER_DELTA_TEMPERATURE',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 2, 4);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'chilledWaterFlowDifferentialPressure','Chilled Water Flow Differential Pressure ',9,'CHILLED_WATER_FLOW_DIFFERENTIAL_PRESSURE',3,TRUE,FALSE,FALSE);
--INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 11, 61);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'chilledWaterStrainerDifferentialPressure','Chilled Water Strainer Differential Pressure',9,'CHILLED_WATER_STRAINER_DIFFERENTIAL_PRESSURE',3,TRUE,FALSE,FALSE);
--INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 11, 61);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'coolingCoilValveCommand','Cooling Coil Valve Command',5,'COOLING_COIL_VALVE_COMMAND',4,TRUE,FALSE,FALSE);
--INSERT INTO BooleanFields (FIELDID, ORGID,  TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Open', 'Close');
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'coolingCoilValveStatus','Cooling Coil Valve Status ',5,'COOLING_COIL_VALVE_STATUS',4,TRUE,FALSE,FALSE);
--INSERT INTO BooleanFields (FIELDID, ORGID,  TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Open', 'Close');
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'coolingCoilValveControl','Cooling Coil Valve Control',9,'COOLING_COIL_VALVE_CONTROL',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'coolingCoilValveFeedback','Cooling Coil Valve FeedBack ',9,'COOLING_COIL_VALVE_FEEDBACK',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'airFlowCoilDifferentialPressure','AirFlow Coil Differinatial Pressure ',9,'AIRFLOW_COIL_DIFFERINATIAL_PRESSURE',3,TRUE,FALSE,FALSE);
--INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 11, 61);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'enthalphyHeatWheelAutoManualStatus','Enthalphy Heat Wheel Auto/Manual Status',5,'ENTHALPHY_HEAT_WHEEL_AUTO_MANUAL_STATUS',4,TRUE,FALSE,FALSE);
--INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Auto' , 'Manul');
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'enthalphyHeatWheelCommand','Enthalphy Heat Wheel Command',5,'ENTHALPHY_HEAT_WHEEL_COMMAND',4,TRUE,FALSE,FALSE);
--INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'On', 'Off');
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'enthalphyHeatWheelRunStatus','Enthalphy Heat Wheel Run Status',5,'ENTHALPHY_HEAT_WHEEL_RUN_STATUS',4,TRUE,FALSE,FALSE);
--INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'On', 'Off');
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'sensibleHeatWheelAutoManualStatus','Sensible Heat Wheel Auto/Manual Status',5,'SENSIBLE_HEAT_WHEEL_AUTO_MANUAL_STATUS',4,TRUE,FALSE,FALSE);
--INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Auto' , 'Manul');
--
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'sensibleHeatWheelCommand','Sensible Heat Wheel Command',5,'SENSIBLE_HEAT_WHEEL_COMMAND',4,TRUE,FALSE,FALSE);
--INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'On', 'Off');
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'sensibleHeatWheelRunStatus','Sensible Heat Wheel Run Status',5,'SENSIBLE_HEAT_WHEEL_RUN_STATUS',4,TRUE,FALSE,FALSE);
--INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'On', 'Off');
--/* First FAHU Reading Table Start */
--
--/* Second FAHU Reading Table Start */
--INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME, TABLE_NAME, MODULE_TYPE) VALUES (${orgId}, 'fahureadingreturnair', 'FAHU Readings Return Air', 'FAHU_Readings_Return_Air', @READING_MODULE_TYPE);
--SET @FAHU_READING_GENERAL := (SELECT LAST_INSERT_ID());
--INSERT INTO SubModulesRel (ORGID,PARENT_MODULE_ID, CHILD_MODULE_ID) VALUES (${orgId},@FAHU_MODULE_ID, @FAHU_READING_GENERAL);
--
--INSERT INTO Asset_Category_Readings (ORGID,PARENT_CATEGORY_ID, READING_MODULE_ID) VALUES (${orgId},@FAHU_CATEGORY_ID, @FAHU_READING_GENERAL);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FAHU_READING_GENERAL, 'parentId', 'Parent', 9, 'PARENT_ID', 2, true, false, true);
--INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FAHU_READING_GENERAL, 'sourceType', 'Source Type', 3, 'SOURCE_TYPE', 12, false, false, true);
--INSERT INTO SystemEnumFields (FIELDID, ORGID, ENUM_NAME) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'SourceType');
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FAHU_READING_GENERAL, 'sourceId', 'Source Id', 9, 'SOURCE_ID', 2, false, false, true);
--INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FAHU_READING_GENERAL, 'actualTtime', 'Actual Timestamp', 9, 'ACTUAL_TTIME', 6, true, false, true);
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FAHU_READING_GENERAL, 'ttime', 'Timestamp', 9, 'TTIME', 6, true, false, true);
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FAHU_READING_GENERAL, 'date', 'Date', 1, 'TTIME_DATE', 1, true, false, true);
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FAHU_READING_GENERAL, 'month', 'Month', 9, 'TTIME_MONTH', 2, true, false, true);
--INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FAHU_READING_GENERAL, 'week', 'Week', 9, 'TTIME_WEEK', 2, true, false, true);
--INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FAHU_READING_GENERAL, 'day', 'Day', 9, 'TTIME_DAY', 2, true, false, true);
--INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FAHU_READING_GENERAL, 'hour', 'Hour', 9, 'TTIME_HOUR', 2, true, false, true);
--INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});
--
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'returnAirDamperCommand','Return Air Damper Command',5,'RETURN_AIR_DAMPER_COMMAND',4,TRUE,FALSE,FALSE);
-- INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Open', 'Close');
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'returnAirDamperStatus','Return Air Damper Status',5,'RETURN_AIR_DAMPER_STATUS',4,TRUE,FALSE,FALSE);
-- INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Open', 'Close');
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'returnAirDamperControl','Return Air Damper Control',9,'RETURN_AIR_DAMPER_CONTROL',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'returnAirDamperFeedback','Return Air Damper Feedback',9,'RETURN_AIR_DAMPER_FEEDBACK',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'returnAirTemperature','Return Air Temperature',9,'RETURN_AIR_TEMPERATURE',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 2, 4);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'returnAirTemperatureSetpoint','Return Air Temperature Setpoint',9,'RETURN_AIR_TEMPERATURE_SETPOINT',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 2, 4);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'exhaustAirHumidity','Exhaust Air Humidity',9,'EXHAUST_AIR_HUMIDITY',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'exhaustAirHumiditySetpoint','Exhaust Air Humidity Setpoint',9,'EXHAUST_AIR_HUMIDITY_SETPOINT',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'exhaustAirDamperCommand','Exhaust Air Damper Command',5,'EXHAUST_AIR_DAMPER_COMMAND',4,TRUE,FALSE,FALSE);
-- INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Open', 'Close');
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'exhaustAirDamperStatus','Exhaust Air Damper Status',5,'EXHAUST_AIR_DAMPER_STATUS',4,TRUE,FALSE,FALSE);
-- INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Open', 'Close');
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'exhaustAirDamperControl','Exhaust Air Damper Control',9,'EXHAUST_AIR_DAMPER_CONTROL',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'exhaustAirDamperFeedback','Exhaust Air Damper Feedback',9,'EXHAUST_AIR_DAMPER_FEEDBACK',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'exhaustAirFlowRate','Exhaust Air Flow Rate ',9,'EXHAUST_AIR_FLOW_RATE',3,TRUE,FALSE,FALSE);
--  INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 18, 100);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'exhaustAirFlowStatus','Exhaust Air Flow Status ',5,'EXHAUST_AIR_FLOW_STATUS',4,TRUE,FALSE,FALSE);
--INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'On', 'Off');
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'exhaustAirFlowFailalarm','Exhaust Air Flow Fail Alarm',5,'EXHAUST_AIR_FLOW_FAIL_ALARM',4,TRUE,FALSE,FALSE);
--INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'Fail', 'Normal');
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'exhaustFanAutoManualStatus','Exhaust Fan Auto/Manual Status',5,'EXHAUST_FAN_AUTO_MANUAL_STATUS',4,TRUE,FALSE,FALSE);
-- INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Auto', 'Manual');
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'exhaustFanCommand','Exhaust Fan Command',5,'EXHAUST_FAN_COMMAND',4,TRUE,FALSE,FALSE);
--INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'On', 'Off');
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'exhaustFanRunStatus','Exhaust Fan Run Status',5,'EXHAUST_FAN_RUN_STATUS',4,TRUE,FALSE,FALSE);
--INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'On', 'Off');
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'exhaustFanMotorEnergy','Exhaust Fan Motor Energy',9,'EXHAUST_FAN_MOTOR_ENERGY',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 1, 1);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'exhaustFanMotorPower','Exhaust Fan Motor Power',9,'EXHAUST_FAN_MOTOR_POWER',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 8, 46);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'exhaustFanMotorDriveEndTemperature','Exhaust Fan Motor Drive End Temperature',9,'EXHAUST_FAN_MOTOR_DRIVE_END_TEMPERATURE',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 2, 4);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'exhaustFanMotorDriveEndVibration','Exhaust Fan Motor Drive End Vibration',9,'EXHAUST_FAN_MOTOR_DRIVE_END_VIBRATION',3,TRUE,FALSE,FALSE);
--INSERT INTO NumberFields (FIELDID, ORGID, UNIT_ID, METRIC) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  51, 9);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'exhaustFanMotorNonDriveEndTemperature','Exhaust Fan Motor Non-Drive End Temperature',9,'EXHAUST_FAN_MOTOR_NONDRIVE_END_TEMPERATURE',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 2, 4);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'exhaustFanMotorNonDriveEndVibration','Exhaust Fan Motor Non-Drive End Vibration',9,'EXHAUST_FAN_MOTOR_NONDRIVE_END_VIBRATION',3,TRUE,FALSE,FALSE);
--INSERT INTO NumberFields (FIELDID, ORGID, UNIT_ID, METRIC) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  51, 9);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'exhaustFanVfdControl','Exhaust Fan VFD Control',9,'EXHAUST_FAN_VFD_CONTROL',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'exhaustFanVfdFeedback','Exhaust Fan VFD Feedback',9,'EXHAUST_FAN_VFD_FEEDBACK',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'exhaustFanVfdFrequency','Exhaust Fan VFD Frequency',9,'EXHAUST_FAN_VFD_FREQUENCY',3,TRUE,FALSE,FALSE);
--INSERT INTO NumberFields (FIELDID, ORGID, UNIT_ID, METRIC) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  51, 9);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'exhaustFanVfdSpeed','Exhaust Fan VFD Speed',9,'EXHAUST_FAN_VFD_SPEED',3,TRUE,FALSE,FALSE);
--INSERT INTO NumberFields (FIELDID, ORGID, METRIC) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 22);
--
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'exhaustFanVfdAutoManualStatus','Exhaust Fan VFD Auto/Manual Status',5,'EXHAUST_FAN_VFD_AUTO_MANUAL_STATUS',4,TRUE,FALSE,FALSE);
-- INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'Auto', 'Manual');
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_GENERAL,'exhaustFanVfdRunStatus','Exhaust Fan VFD Run Status',5,'EXHAUST_FAN_VFD_RUN_STATUS',4,TRUE,FALSE,FALSE);
--INSERT INTO BooleanFields (FIELDID, ORGID, TRUE_VAL, FALSE_VAL) VALUES ((SELECT LAST_INSERT_ID()), ${orgId} , 'On', 'Off');
--/* Second FAHU Reading Table End */
--
--/* Third FAHU Reading Table  STart*/
--INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME, TABLE_NAME, MODULE_TYPE) VALUES (${orgId}, 'fahureadingsupplyair', 'FAHU Readings Supply Air', 'FAHU_Readings_Supply_Air', @READING_MODULE_TYPE);
--SET @FAHU_READING_SUPPLY_AIR := (SELECT LAST_INSERT_ID());
--INSERT INTO SubModulesRel (ORGID,PARENT_MODULE_ID, CHILD_MODULE_ID) VALUES (${orgId},@FAHU_MODULE_ID, @FAHU_READING_SUPPLY_AIR);
--
--INSERT INTO Asset_Category_Readings (ORGID,PARENT_CATEGORY_ID, READING_MODULE_ID) VALUES (${orgId},@FAHU_CATEGORY_ID, @FAHU_READING_SUPPLY_AIR);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FAHU_READING_SUPPLY_AIR, 'parentId', 'Parent', 9, 'PARENT_ID', 2, true, false, true);
--INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FAHU_READING_SUPPLY_AIR, 'sourceType', 'Source Type', 3, 'SOURCE_TYPE', 12, false, false, true);
--INSERT INTO SystemEnumFields (FIELDID, ORGID, ENUM_NAME) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'SourceType');
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FAHU_READING_SUPPLY_AIR, 'sourceId', 'Source Id', 9, 'SOURCE_ID', 2, false, false, true);
--INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FAHU_READING_SUPPLY_AIR, 'actualTtime', 'Actual Timestamp', 9, 'ACTUAL_TTIME', 6, true, false, true);
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FAHU_READING_SUPPLY_AIR, 'ttime', 'Timestamp', 9, 'TTIME', 6, true, false, true);
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FAHU_READING_SUPPLY_AIR, 'date', 'Date', 1, 'TTIME_DATE', 1, true, false, true);
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FAHU_READING_SUPPLY_AIR, 'month', 'Month', 9, 'TTIME_MONTH', 2, true, false, true);
--INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FAHU_READING_SUPPLY_AIR, 'week', 'Week', 9, 'TTIME_WEEK', 2, true, false, true);
--INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FAHU_READING_SUPPLY_AIR, 'day', 'Day', 9, 'TTIME_DAY', 2, true, false, true);
--INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @FAHU_READING_SUPPLY_AIR, 'hour', 'Hour', 9, 'TTIME_HOUR', 2, true, false, true);
--INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});
--
--
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_SUPPLY_AIR,'outsideAirTemperature','Outside Air Temperature',9,'OUTSIDE_AIR_TEMPERATURE',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 2, 4);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_SUPPLY_AIR,'outsideAirHumidity','Outside Air Humidity',9,'OUTSIDE_AIR_HUMIDITY',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_SUPPLY_AIR,'outsideAirDamperControl','Outside Air Damper Control',9,'OUTSIDE_AIR_DAMPER_CONTROL',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_SUPPLY_AIR,'outsideAirDamperFeedback','Outside Air Damper Feedback',9,'OUTSIDE_AIR_DAMPER_FEEDBACK',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_SUPPLY_AIR,'supplyAirDamperControl','Supply Air Damper Control',9,'SUPPLY_AIR_DAMPER_CONTROL',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_SUPPLY_AIR,'supplyAirDamperFeedback','Supply Air Damper Feedback',9,'SUPPLY_AIR_DAMPER_FEEDBACK',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_SUPPLY_AIR,'supplyAirTemperature','Supply Air Temperature',9,'SUPPLY_AIR_TEMPERATURE',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 2, 4);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_SUPPLY_AIR,'supplyAirTemperatureSetpoint','Supply Air Temperature Setpoint',9,'SUPPLY_AIR_TEMPERATURE_SETPOINT',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 2, 4);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_SUPPLY_AIR,'supplyAirHumidity','Supply Air Humidity',9,'SUPPLY_AIR_HUMIDITY',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_SUPPLY_AIR,'supplyAirHumiditySetpoint','Supply Air Humidity Setpoint',9,'SUPPLY_AIR_HUMIDITY_SETPOINT',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_SUPPLY_AIR,'supplyAirPressure','Supply Air Pressure',9,'SUPPLY_AIR_PRESSURE',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 11, 105);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_SUPPLY_AIR,'supplyAirPressureSetpoint','Supply Air Pressure Setpoint',9,'SUPPLY_AIR_PRESSURE_SETPOINT',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 11, 105);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_SUPPLY_AIR,'supplyAirFlowRate','Supply Air Flow Rate ',9,'SUPPLY_AIR_FLOW_RATE',3,TRUE,FALSE,FALSE);
--  INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 18, 100);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_SUPPLY_AIR,'supplyFanMotorEnergy','Supply Fan Motor Energy',9,'SUPPLY_FAN_MOTOR_ENERGY',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 1, 1);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_SUPPLY_AIR,'supplyFanMotorPower','Supply Fan Motor Power',9,'SUPPLY_FAN_MOTOR_POWER',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 8, 46);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_SUPPLY_AIR,'supplyFanMotorDriveEndTemperature','Supply Fan Motor Drive End Temperature',9,'SUPPLY_FAN_MOTOR_DRIVE_END_TEMPERATURE',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 2, 4);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_SUPPLY_AIR,'supplyFanMotorDriveEndVibration','Supply Fan Motor Drive End Vibration',9,'SUPPLY_FAN_MOTOR_DRIVE_END_VIBRATION',3,TRUE,FALSE,FALSE);
--INSERT INTO NumberFields (FIELDID, ORGID, UNIT_ID, METRIC) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  51, 9);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_SUPPLY_AIR,'supplyFanMotorNonDriveEndTemperature','Supply Fan Motor Non-Drive End Temperature',9,'SUPPLY_FAN_MOTOR_NONDRIVE_END_TEMPERATURE',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 2, 4);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_SUPPLY_AIR,'supplyFanMotorNonDriveEndVibration','Supply Fan Motor Non-Drive End Vibration',9,'SUPPLY_FAN_MOTOR_NONDRIVE_END_VIBRATION',3,TRUE,FALSE,FALSE);
--INSERT INTO NumberFields (FIELDID, ORGID, UNIT_ID, METRIC) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  51, 9);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_SUPPLY_AIR,'supplyFanVfdControl','Supply Fan VFD Control',9,'SUPPLY_FAN_VFD_CONTROL',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_SUPPLY_AIR,'supplyFanVfdFeedback','Supply Fan VFD Feedback',9,'SUPPLY_FAN_VFD_FEEDBACK',3,TRUE,FALSE,FALSE);
-- INSERT INTO NumberFields (FIELDID, ORGID, METRIC, UNIT_ID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  16, 87);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_SUPPLY_AIR,'supplyFanVfdFrequency','Supply Fan VFD Frequency',9,'SUPPLY_FAN_VFD_FREQUENCY',3,TRUE,FALSE,FALSE);
--INSERT INTO NumberFields (FIELDID, ORGID, UNIT_ID, METRIC) VALUES ((SELECT LAST_INSERT_ID()), ${orgId},  51, 9);
--
--INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, IS_DEFAULT, IS_MAIN_FIELD, REQUIRED) Values(${orgId},@FAHU_READING_SUPPLY_AIR,'supplyFanVfdSpeed','Supply Fan VFD Speed',9,'SUPPLY_FAN_VFD_SPEED',3,TRUE,FALSE,FALSE);
--INSERT INTO NumberFields (FIELDID, ORGID, METRIC) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 22);