SET @BASE_ENTITY_MODULE_TYPE := 1;
SET @PICK_LIST_MODULE_TYPE := 2;
SET @READING_MODULE_TYPE := 3;
SET @PHOTOS_MODULE_TYPE := 4;
SET @NOTES_MODULE_TYPE := 5;
SET @ATTACHMENTS_MODULE_TYPE := 6;
SET @SCHEDULED_FORMULA_TYPE := 7;
SET @LIVE_FORMULA_TYPE := 8;
SET @SYSTEM_SCHEDULED_FORMULA_TYPE := 9;
SET @CUSTOM_MODULE_TYPE := 10;
SET @PREDICTED_READING_MODULE_TYPE := 11;
SET @ACTIVITY_MODULE_TYPE := 12;
SET @TRANSACTION_MODULE_TYPE := 17;
SET @SUB_ENTITY_MODULE_TYPE := 18;
SET @SUPPORTING_ENTITY_MODULE_TYPE := 19;
SET @DOCUMENT_MODULE_TYPE := 20;
SET @RATING_MODULE_TYPE := 22;
SET @READING_AGGREGATION := 23;


SET @SITE_MODULE_ID := (SELECT MODULEID from Modules where name = 'site' and orgid = ${orgId});
SET @BASE_SPACE_MODULE_ID := (SELECT MODULEID from Modules where name = 'basespace' and orgid = ${orgId});
SET @RESOURCE_MODULE_ID := (SELECT MODULEID from Modules where name = 'resource' and orgid = ${orgId});
SET @ASSET_CATEGORY_MODULE_ID := (SELECT MODULEID from Modules where name = 'assetcategory' and orgid = ${orgId});

