SET @AGENT_ALARM_MODULEID := (SELECT MODULEID from Modules where name = 'agentAlarm' and ORGID = ${orgId});

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AGENT_ALARM_MODULEID, 'notified', 'Notified', 5, 'NOTIFIED', 4, false, false, true);
INSERT INTO BooleanFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});


