SET @BASE_ENTITY_MODULE_TYPE := 1;
SET @PICK_LIST_MODULE_TYPE := 2;
SET @READING_MODULE_TYPE := 3;
SET @PHOTOS_MODULE_TYPE := 4;
SET @NOTES_MODULE_TYPE := 5;
SET @ATTACHMENTS_MODULE_TYPE := 6;
SET @SCHEDULED_FORMULA_TYPE := 7;
SET @LIVE_FORMULA_TYPE := 8;
SET @SYSTEM_SCHEDULED_FORMULA_TYPE := 9;
SET @CUSTOM_MODULE_TYPE := 10;
SET @PREDICTED_READING_MODULE_TYPE := 11;
SET @ACTIVITY_MODULE_TYPE := 12;
SET @TRANSACTION_MODULE_TYPE := 17;
SET @SUB_ENTITY_MODULE_TYPE := 18;
SET @SUPPORTING_ENTITY_MODULE_TYPE := 19;
SET @DOCUMENT_MODULE_TYPE := 20;
SET @RATING_MODULE_TYPE := 22;
SET @READING_AGGREGATION := 23;
SET @SCORE_MODULE_TYPE := 25;
SET @LARGE_TEXT_DATA_TYPE := 28;


SET @SITE_MODULE_ID := (SELECT MODULEID from Modules where name = 'site' and orgid = ${orgId});
SET @BASE_SPACE_MODULE_ID := (SELECT MODULEID from Modules where name = 'basespace' and orgid = ${orgId});
SET @RESOURCE_MODULE_ID := (SELECT MODULEID from Modules where name = 'resource' and orgid = ${orgId});
SET @ASSET_CATEGORY_MODULE_ID := (SELECT MODULEID from Modules where name = 'assetcategory' and orgid = ${orgId});

INSERT INTO Modules (ORGID, NAME, DISPLAY_NAME, TABLE_NAME, MODULE_TYPE) VALUES (${orgId}, 'auditLogs', 'Audit Logs', 'Audit_Logs', @BASE_ENTITY_MODULE_TYPE);
SET @AUDIT_LOGS_MODULE_ID := (SELECT LAST_INSERT_ID());

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT, IS_MAIN_FIELD) VALUES (${orgId}, @AUDIT_LOGS_MODULE_ID, 'subject', 'Subject', 1, 'SUBJECT', 1, true, false, true, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AUDIT_LOGS_MODULE_ID, 'description', 'Description', 2, 'DESCRIPTION', 1, true, false, true);

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AUDIT_LOGS_MODULE_ID, 'recordType', 'Record Type', 5, 'RECORD_TYPE', 12, true, false, true);
INSERT INTO SystemEnumFields (FIELDID, ORGID, ENUM_NAME) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'AuditLogRecordType');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AUDIT_LOGS_MODULE_ID, 'typeName', 'Type Name', 1, 'TYPE_NAME', 1, true, false, true);
INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AUDIT_LOGS_MODULE_ID, 'recordId', 'Record Id', 9, 'RECORD_ID', 2, true, false, true);
INSERT INTO NumberFields (FIELDID, ORGID) VALUES ((SELECT LAST_INSERT_ID()), ${orgId});

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AUDIT_LOGS_MODULE_ID, 'performedBy', 'Performed By', 11, 'PERFORMED_BY', 7, false, false, true);
INSERT INTO LookupFields (FIELDID, ORGID, SPECIAL_TYPE) VALUES ((SELECT LAST_INSERT_ID()), ${orgId}, 'users');

INSERT INTO Fields (ORGID, MODULEID, NAME, DISPLAY_NAME, DISPLAY_TYPE, COLUMN_NAME, DATA_TYPE, REQUIRED, DISABLED, IS_DEFAULT) VALUES (${orgId}, @AUDIT_LOGS_MODULE_ID, 'time', 'Time', 7, 'TIME', 6, 1, 0, 1);

